// <auto-generated />
using System;
using Todo.Core.Common.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Todo.Core.Common.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.6");

            modelBuilder.Entity("Todo.Core.Modules.TodoItems.Entities.TodoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ArchivedOn")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("Ordinal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TodoListId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<int>("StoryPoints")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedOn")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TodoListId");

                    b.ToTable("TodoItems", (string)null);

                    b.HasDiscriminator<string>("Status").IsComplete(true).HasValue("TodoItem");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Todo.Core.Modules.TodoLists.Entities.TodoList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ArchivedOn")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<uint>("Ordinal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedOn")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TodoLists", (string)null);

                    b.HasDiscriminator<string>("Type").IsComplete(true).HasValue("TodoList");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Todo.Core.Modules.TodoLists.Entities.TodoListTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<int?>("TodoListId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TodoListId", "Locale")
                        .IsUnique();

                    b.ToTable("TodoListsTranslations", (string)null);
                });

            modelBuilder.Entity("Todo.Core.Modules.TodoItems.Entities.PendingTodoItem", b =>
                {
                    b.HasBaseType("Todo.Core.Modules.TodoItems.Entities.TodoItem");

                    b.HasDiscriminator().HasValue("Pending");
                });

            modelBuilder.Entity("Todo.Core.Modules.TodoItems.Entities.CompletedTodoItem", b =>
                {
                    b.HasBaseType("Todo.Core.Modules.TodoItems.Entities.TodoItem");

                    b.Property<DateTimeOffset>("ResolvedOn")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Resolved");
                });

            modelBuilder.Entity("Todo.Core.Modules.TodoLists.Entities.SharedTodoList", b =>
                {
                    b.HasBaseType("Todo.Core.Modules.TodoLists.Entities.TodoList");

                    b.HasDiscriminator().HasValue("Operational");
                });

            modelBuilder.Entity("Todo.Core.Modules.TodoLists.Entities.PersonalTodoList", b =>
                {
                    b.HasBaseType("Todo.Core.Modules.TodoLists.Entities.TodoList");

                    b.HasDiscriminator().HasValue("Strategic");
                });

            modelBuilder.Entity("Todo.Core.Modules.TodoItems.Entities.TodoItem", b =>
                {
                    b.HasOne("Todo.Core.Modules.TodoLists.Entities.TodoList", "TodoList")
                        .WithMany("TodoItems")
                        .HasForeignKey("TodoListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TodoList");
                });

            modelBuilder.Entity("Todo.Core.Modules.TodoLists.Entities.TodoListTranslation", b =>
                {
                    b.HasOne("Todo.Core.Modules.TodoLists.Entities.TodoList", null)
                        .WithMany("Translations")
                        .HasForeignKey("TodoListId");
                });

            modelBuilder.Entity("Todo.Core.Modules.TodoLists.Entities.TodoList", b =>
                {
                    b.Navigation("TodoItems");

                    b.Navigation("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
