//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Majal source generator
// </auto-generated>
//------------------------------------------------------------------------------

namespace Majal;

/// <summary>
/// Marker interface for domain value objects.
/// </summary>
public interface IValueObject
{ 
}