//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Majal source generator
// </auto-generated>
//------------------------------------------------------------------------------

namespace Majal;

/// <summary>
/// Apply to a class to indicate it is a DDD simple value object with a specific Value type.
/// </summary>
[global::System.AttributeUsage(global::System.AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
public sealed class SimpleValueObjectAttribute<TValue> : global::System.Attribute
{
}