using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;
using Majal.Common;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Majal.Generators.ValueObjects;

/// <summary>
/// Generates a partial class for every class marked with [SimpleValueObject].
/// The generated class implements IValueObject and adds equality, comparison, and hashing logic.
/// </summary>
[Generator]
public sealed class SimpleValueObjectGenerator : IIncrementalGenerator
{
    // Record struct to hold the data needed to generate the aggregate root class
    private readonly record struct SimpleValueObjectData(string Name, string Namespace, string ValueType)
    {
        public string Name { get; } = Name;
        public string Namespace { get; } = Namespace;
        public string ValueType { get; } = ValueType;
    }

    private const string SimpleValueObjectFilenameSuffix = ".SimpleValueObject.g.cs";
    private const string SimpleValueObjectAttributeFilename = "SimpleValueObjectAttribute.g.cs";
    private const string SimpleValueObjectMarkerInterfaceFilename = "ISimpleValueObject.g.cs";
    private const string ValueObjectAttributeName = "SimpleValueObjectAttribute";
    private const string ValueObjectAttributeFullName = "Majal.SimpleValueObjectAttribute`1";
    private const string AutoGeneratedHeader = "// <auto-generated />";
    private const string NullableEnable = "#nullable enable";


    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        RegisterPredefinedTypes(context);
        RegisterEntityGenerators(context);
    }

    /// <summary>
    /// Registers the predefined types (ISimpleValueObject, SimpleValueObjectAttribute)
    /// that will be available to all generated code.
    /// </summary>
    private static void RegisterPredefinedTypes(IncrementalGeneratorInitializationContext context)
    {
        // Register marker types and attributes that will be available to all generated code
        context.RegisterPostInitializationOutput(ctx =>
        {
            ctx.AddSource(SimpleValueObjectAttributeFilename,
                Sources.SimpleValueObjectAttributeSource);

            ctx.AddSource(SimpleValueObjectMarkerInterfaceFilename,
                Sources.SimpleValueObjectMarkerInterfaceSource);
        });
    }

    /// <summary>
    /// Registers the entity generator pipeline that processes classes marked with [SimpleValueObject].
    /// </summary>
    private static void RegisterEntityGenerators(IncrementalGeneratorInitializationContext context)
    {
        // Get classes with attributes
        var entitiesToGenerate = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                ValueObjectAttributeFullName,
                predicate: (node, _) => node is ClassDeclarationSyntax { AttributeLists.Count: > 0 },
                transform: GetDataToGenerate
            );

        // Filter to classes that carry the [SimpleValueObject] attribute
        var entities = entitiesToGenerate
            .Where(static m => m is not null)
            .Select(static (m, _) => m!.Value);

        // Generate source for each entity
        context.RegisterSourceOutput(entities, (spc, classSymbol) =>
        {
            var source = GeneratePartialClass(classSymbol);
            spc.AddSource($"{classSymbol.Name}{SimpleValueObjectFilenameSuffix}",
                SourceText.From(source, Encoding.UTF8));
        });
    }


    /// <summary>
    /// Extracts the necessary information from the class symbol to generate the SimpleValueObject class.
    /// </summary>
    /// <param name="context"></param>
    /// <param name="ct"></param>
    /// <returns>EntityToGenerate?</returns>
    private static SimpleValueObjectData? GetDataToGenerate(GeneratorAttributeSyntaxContext context,
        CancellationToken ct)
    {
        if (context.TargetSymbol is not INamedTypeSymbol classSymbol) return null;

        var typeName = classSymbol.Name;

        if (classSymbol.TypeParameters.Length > 0)
            typeName += $"<{string.Join(", ", classSymbol.TypeParameters.Select(t => t.Name))}>";

        var attributes = classSymbol.GetAttributes().ToArray();

        var entityAttribute = attributes
            .FirstOrDefault(a => a.AttributeClass?.Name == ValueObjectAttributeName);

        if (entityAttribute?.AttributeClass is not { TypeArguments.Length: > 0 }) return null;

        return new SimpleValueObjectData(
            Name: typeName,
            Namespace: $"namespace {classSymbol.ContainingNamespace.ToDisplayString()};",
            ValueType: entityAttribute.AttributeClass.TypeArguments[0].ToDisplayString()
        );
    }


    /// <summary>
    /// Generates the common header for generated code files.
    /// </summary>
    private static void AppendCodeHeader(StringBuilder sb, SimpleValueObjectData data)
    {
        sb.AppendLine(AutoGeneratedHeader);
        sb.AppendLine();
        sb.AppendLine(NullableEnable);
        sb.AppendLine();
        sb.AppendLine(data.Namespace);
        sb.AppendLine();
    }

    /// <summary>
    /// Appends the class definition line with appropriate interfaces.
    /// </summary>
    private static void AppendClassDeclaration(StringBuilder sb, SimpleValueObjectData data)
    {
        List<string> interfaces =
        [
            "global::Majal.ISimpleValueObject",
            "global::System.IComparable",
            $"global::System.IComparable<{data.Name}>"
        ];

        sb.AppendLine($"public partial class {data.Name} : {string.Join(", ", interfaces)}");
        sb.AppendLine("{");
        sb.AppendLine();
    }

    /// <summary>
    /// Appends the private fields.
    /// </summary>
    private static void AppendPrivateFields(StringBuilder sb)
    {
        sb.AppendLine("    private global::System.Int32? _cachedHashCode;");
        sb.AppendLine();
    }

    /// <summary>
    /// Appends the Value property for generic value objects.
    /// </summary>
    private static void AppendValueProperty(StringBuilder sb, SimpleValueObjectData data)
    {
        sb.AppendLine($"    public {data.ValueType}? Value {{ get; }}");
        sb.AppendLine();
    }

    /// <summary>
    /// Appends the GetEqualityComponents method.
    /// </summary>
    private static void AppendGetEqualityComponents(StringBuilder sb)
    {
        sb.AppendLine(
            "    private global::System.Collections.Generic.IEnumerable<global::System.Object?> GetEqualityComponents()");
        sb.AppendLine("{");
        sb.AppendLine("         yield return Value;");
        sb.AppendLine("}");
        sb.AppendLine();
    }

    /// <summary>
    /// Appends the constructor.
    /// </summary>
    private static void AppendConstructor(StringBuilder sb, SimpleValueObjectData data)
    {
        sb.AppendLine($"    public {data.Name}({data.ValueType} value)");
        sb.AppendLine("    {");
        sb.AppendLine("        Value = value;");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    /// <summary>
    /// Appends the Equals method override.
    /// </summary>
    private static void AppendEquals(StringBuilder sb, SimpleValueObjectData data)
    {
        sb.AppendLine("    public override global::System.Boolean Equals(global::System.Object? obj)");
        sb.AppendLine("    {");
        sb.AppendLine($"        if (obj is not {data.Name} other) return false;");
        sb.AppendLine("        return GetEqualityComponents().SequenceEqual(other.GetEqualityComponents());");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    /// <summary>
    /// Appends the equality operators (== and !=).
    /// </summary>
    private static void AppendEqualityOperators(StringBuilder sb, SimpleValueObjectData data)
    {
        sb.AppendLine($"    public static global::System.Boolean operator ==({data.Name} a, {data.Name} b)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (a is null && b is null) return true;");
        sb.AppendLine("        if (a is null || b is null) return false;");
        sb.AppendLine("        return a.Equals(b);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    public static global::System.Boolean operator !=({data.Name} a, {data.Name} b)");
        sb.AppendLine("    {");
        sb.AppendLine("        return !(a == b);");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    /// <summary>
    /// Appends the GetHashCode override with caching.
    /// </summary>
    private static void AppendGetHashCode(StringBuilder sb)
    {
        sb.AppendLine("    public override global::System.Int32 GetHashCode()");
        sb.AppendLine("    {");
        sb.AppendLine("        if (!_cachedHashCode.HasValue)");
        sb.AppendLine("        {");
        sb.AppendLine("            _cachedHashCode = GetEqualityComponents()");
        sb.AppendLine("                .Aggregate(1, (current, obj) =>");
        sb.AppendLine("                {");
        sb.AppendLine("                    unchecked");
        sb.AppendLine("                    {");
        sb.AppendLine("                        return current * 23 + (obj?.GetHashCode() ?? 0);");
        sb.AppendLine("                    }");
        sb.AppendLine("                });");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        return _cachedHashCode.Value;");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    /// <summary>
    /// Appends the CompareTo methods for IComparable implementation.
    /// </summary>
    private static void AppendCompareTo(StringBuilder sb, SimpleValueObjectData data)
    {
        sb.AppendLine($"    public global::System.Int32 CompareTo({data.Name}? other)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (other is null) return 1;");
        sb.AppendLine();
        sb.AppendLine("        if (ReferenceEquals(this, other)) return 0;");
        sb.AppendLine();
        sb.AppendLine("        if (this.GetType() != other.GetType())");
        sb.AppendLine(
            "            return global::System.String.Compare(this.GetType().FullName, other.GetType().FullName, global::System.StringComparison.Ordinal);");
        sb.AppendLine();
        sb.AppendLine("        return GetEqualityComponents()");
        sb.AppendLine("                 .OfType<global::System.IComparable>()");
        sb.AppendLine(
            "                 .Zip(other.GetEqualityComponents().OfType<global::System.IComparable>(), (a, b) => a?.CompareTo(b) ?? (b is null ? 0 : -1))");
        sb.AppendLine("                 .FirstOrDefault();");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    public global::System.Int32 CompareTo(global::System.Object? other)");
        sb.AppendLine("    {");
        sb.AppendLine($"        return CompareTo(other as {data.Name});");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    /// <summary>
    /// Appends the implicit conversion operator for generic value objects.
    /// </summary>
    private static void AppendImplicitOperator(StringBuilder sb, SimpleValueObjectData data)
    {
        sb.AppendLine($"    public static implicit operator {data.ValueType}?({data.Name}? valueObject)");
        sb.AppendLine("    {");
        sb.AppendLine("        return valueObject?.Value;");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    /// <summary>
    /// Appends the ToString override.
    /// </summary>
    private static void AppendToString(StringBuilder sb)
    {
        sb.AppendLine("    public override global::System.String ToString()");
        sb.AppendLine("    {");
        sb.AppendLine("        return Value?.ToString() ?? this.ToString();");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    /// <summary>
    /// Generates the common footer for generated code files.
    /// </summary>
    private static void AppendCodeFooter(StringBuilder sb)
    {
        sb.AppendLine("}");
        sb.AppendLine();
    }

    /// <summary>
    /// Generates the partial class that implements IValueObject and equality/comparison logic.
    /// </summary>
    private static string GeneratePartialClass(SimpleValueObjectData data)
    {
        var sb = new StringBuilder();

        AppendCodeHeader(sb, data);

        AppendClassDeclaration(sb, data);

        AppendPrivateFields(sb);

        AppendValueProperty(sb, data);

        AppendConstructor(sb, data);

        AppendEquals(sb, data);

        AppendEqualityOperators(sb, data);

        AppendGetHashCode(sb);

        AppendCompareTo(sb, data);

        AppendGetEqualityComponents(sb);

        AppendImplicitOperator(sb, data);

        AppendToString(sb);

        AppendCodeFooter(sb);

        return sb.ToString();
    }
}