using Majal.Common.Abstractions;
using static Majal.Common.Abstractions.Constants;

namespace Majal.Generators.ValueObjects;

public class ValueObjectTemplate : BaseTemplate
{
    public bool EnableEfCore { get; init; }
    public ValueObjectGenerator.ValueObjectData Data { get; init; }

    public const string FactoryMethodName = "Create";
    public const string EqualityMethodName = "GetEqualityComponents";
    public const string EfCoreValueConverterTypeName = "EfCoreValueConverter";


    public override string TransformText()
    {
        Clear();

        WriteLine("// <auto-generated />");
        WriteLine("");
        WriteLine("#nullable enable");
        WriteLine("");
        WriteLine(Data.Namespace);
        WriteLine("");
        
        WriteLine("/// <summary>");
        WriteLine($"/// Provides value-object infrastructure for <see cref=\"{Data.TypeName}\"/>.");
        WriteLine("/// </summary>");
        GenerateClassCode();

        return ToString();
    }

    private void GenerateClassCode()
    {
        List<string> interfaces =
        [
            $"{SystemNamespace}.IEquatable<{Data.TypeName}>",
            $"{SystemNamespace}.IComparable",
            $"{SystemNamespace}.IComparable<{Data.TypeName}>",
        ];

        List<string> attributes = [];

        if (Data.Value?.GenericType is { } type)
        {
            interfaces.Add($"{MajalNamespace}.IValueObject<{type}>");
            interfaces.Add($"{SystemNamespace}.IParsable<{Data.TypeName}>");

            var jsonConverterType = $"typeof({Data.TypeName}.JsonValueObjectConverter)";
            attributes.Add($"{JsonSerializationNamespace}.JsonConverterAttribute({jsonConverterType})");

            var typeConverter = $"typeof({Data.TypeName}.ValueObjectTypeConverter)";
            attributes.Add($"{ComponentModelNamespace}.TypeConverterAttribute({typeConverter})");
        }
        else
        {
            interfaces.Add($"{MajalNamespace}.IValueObject");
        }

        foreach (var attribute in attributes)
        {
            WriteLine($"[{attribute}]");
        }

        var typeKeyword = Data.IsStruct ? "struct" : "class";
       
        WriteLine($"public partial {typeKeyword} {Data.TypeName} : {string.Join(", ", interfaces)}");
        WriteLine("{");
        PushIndent();
        GenerateValueObjectImplementation();
        GenerateCommonImplementation();
        PopIndent();
        WriteLine("}");
    }


    private void GenerateValueObjectImplementation()
    {
        if (Data.Value?.GenericType is { } type)
        {
            WriteLine("/// <summary>Gets the underlying primitive value encapsulated by this value object.</summary>");
            WriteLine($"public required {type} Value {{ get; init; }}");
            WriteLine("");

            if (!Data.Methods.Any(m =>
                    m.ReturnType.Equals(Data.TypeName) && m is
                        { Name: FactoryMethodName, IsStatic: true, Parameters.Count: 1 }))
            {
                WriteLine("/// <summary>");
                WriteLine($"/// Creates a new <see cref=\"{Data.TypeName}\"/> wrapping the specified <paramref name=\"value\"/>.");
                WriteLine("/// </summary>");
                WriteLine($"/// <param name=\"value\">The primitive value to wrap.</param>");
                WriteLine($"/// <returns>A new <see cref=\"{Data.TypeName}\"/> instance.</returns>");
                Write($"public static {Data.TypeName} {FactoryMethodName}({type} value) => ");
                WriteLine("new() { Value = value };");
                WriteLine("");
            }

            if (!Data.Methods.Any(m => m is { Name: EqualityMethodName, IsStatic: false, Parameters.Count: 0 }))
            {
                WriteLine("/// <summary>Returns the sequence of components used for structural equality comparisons.</summary>");
                Write($"private {GenericsNamespace}.IEnumerable<{ObjectType}?> {EqualityMethodName}()");
                WriteLine(" { yield return Value; }");
                WriteLine("");
            }


            WriteLine("/// <summary>Implicitly converts a <see cref=\"Value\"/> to its underlying primitive type.</summary>");
            WriteLine($"public static implicit operator {type}({Data.TypeName} valueObject) => valueObject.Value;");
            WriteLine("");

            WriteLine("/// <summary>Explicitly converts a primitive value to a <see cref=\"Value\"/>.</summary>");
            WriteLine($"public static explicit operator {Data.TypeName}({type} value) => {FactoryMethodName}(value);");
            WriteLine("");

            GenerateIParseableCode();

            GenerateTypeConverter();

            GenerateJsonConverter();

            if (EnableEfCore)
            {
                const string converter = $"v => v.Value, v => {FactoryMethodName}(v)";
                WriteLine("/// <summary>Provides an EF Core <c>ValueConverter</c> for persisting this value object as its primitive type.</summary>");
                WriteLine($"public sealed class {EfCoreValueConverterTypeName}() :");
                PushIndent();
                WriteLine($"{EfCoreValueConversion}.ValueConverter<{Data.TypeName}, {type}>({converter})");
                PopIndent();
                WriteLine("{");
                WriteLine("}");
                WriteLine("");
            }

            WriteLine("");
        }

        if (!Data.Methods.Any(m => m is { Name: nameof(ToString), IsStatic: false, Parameters.Count: 0 }))
        {
            if (Data.Properties.Count > 0)
            {
                WriteLine("/// <inheritdoc />");
                WriteLine($"public override {StringType} ToString()");
                WriteLine("{");
                PushIndent();
                WriteLine($"var sb = new {SystemNamespace}.Text.StringBuilder();");
                WriteLine("""sb.Append("{ ");""");
                for (var i = 0; i < Data.Properties.Count; i++)
                {
                    var prop = Data.Properties[i];
                    WriteLine($"""sb.Append("{prop.Name} = ");""");
                    WriteLine($"if (({ObjectType}?){prop.Name} is {CollectionNamespace}.IEnumerable enumerable{i} && ({ObjectType}){prop.Name} is not {StringType})");
                    WriteLine("{");
                    PushIndent();
                    WriteLine("""sb.Append("[");""");
                    WriteLine($"""sb.Append({StringType}.Join(", ", {LinqNamespace}.Enumerable.Cast<{ObjectType}>(enumerable{i})));""");
                    WriteLine("""sb.Append("]");""");
                    PopIndent();
                    WriteLine("}");
                    WriteLine("else");
                    WriteLine("{");
                    PushIndent();
                    WriteLine($"sb.Append({prop.Name});");
                    PopIndent();
                    WriteLine("}");

                    if (i < Data.Properties.Count - 1) WriteLine(""" sb.Append(", "); """);
                    WriteLine("");
                }

                WriteLine("""sb.Append(" }");""");
                WriteLine("return sb.ToString();");
                PopIndent();
                WriteLine("}");
                WriteLine("");
            }
            else if (Data.Value?.GenericType is not null)
            {
                WriteLine("/// <inheritdoc />");
                WriteLine($"public override {StringType} ToString()");
                WriteLine("{");
                PushIndent();
                WriteLine(
                    $"if ((({ObjectType})Value) is {CollectionNamespace}.IEnumerable enumerable && (({ObjectType})Value) is not {StringType})");
                WriteLine("{");
                PushIndent();
                WriteLine(
                    $$"""return "[" + {{StringType}}.Join(", ", {{LinqNamespace}}.Enumerable.Cast<{{ObjectType}}>(enumerable)) + "]"; """);
                PopIndent();
                WriteLine("}");
                WriteLine("");
                var returnStatement = Data.Value.GenericType is "string" ? "Value" : "Value.ToString()";
                WriteLine($"return {returnStatement};");
                PopIndent();
                WriteLine("}");
                WriteLine("");
            }
        }

        WriteLine("");
        return;


        void GenerateTypeConverter()
        {
            string[] implementations =
            [
                $"{ComponentModelNamespace}.TypeConverter"
            ];

            WriteLine("/// <summary>A <see cref=\"global::System.ComponentModel.TypeConverter\"/> that converts string values to this value object and back.</summary>");
            WriteLine($"public sealed class ValueObjectTypeConverter : {string.Join(", ", implementations)} ");
            WriteLine("{");
            PushIndent();

            {
                string[] parameters =
                [
                    $"{ComponentModelNamespace}.ITypeDescriptorContext? context",
                    $"{TypeType} sourceType"
                ];

                WriteLine("/// <inheritdoc />");
                WriteLine($"public override {BoolType} CanConvertFrom({string.Join(", ", parameters)})");
                WriteLine("{");
                PushIndent();
                WriteLine("return sourceType == typeof(string) || base.CanConvertFrom(context, sourceType);");
                PopIndent();
                WriteLine("}");
                WriteLine("");
            }

            {
                string[] parameters =
                [
                    $"{ComponentModelNamespace}.ITypeDescriptorContext? context",
                    $"{GlobalizationNamespace}.CultureInfo? culture",
                    $"{ObjectType} value"
                ];

                WriteLine("/// <inheritdoc />");
                WriteLine($"public override {ObjectType}? ConvertFrom({string.Join(", ", parameters)})");
                WriteLine("{");
                PushIndent();
                WriteLine("return value is string s ? ");
                PushIndent();
                WriteLine($"{Data.TypeName}.Parse(s) : base.ConvertFrom(context, culture, value);");
                PopIndent();
                PopIndent();
                WriteLine("}");
                WriteLine("");

                PopIndent();
                WriteLine("}");
                WriteLine("");
            }
        }

        void GenerateJsonConverter()
        {
            string[] implementations =
            [
                $"{JsonSerializationNamespace}.JsonConverter<{Data.TypeName}>"
            ];

            WriteLine("/// <summary>A <see cref=\"global::System.Text.Json.Serialization.JsonConverter\"/> for serializing this value object as a JSON string.</summary>");
            WriteLine($"public sealed class JsonValueObjectConverter : {string.Join(", ", implementations)} ");
            WriteLine("{");
            PushIndent();
            {
                string[] parameters =
                [
                    $"ref {JsonNamespace}.Utf8JsonReader reader",
                    $"{SystemNamespace}.Type typeToConvert",
                    $"{JsonNamespace}.JsonSerializerOptions options"
                ];

                WriteLine("/// <inheritdoc />");
                WriteLine($"public override {Data.TypeName} Read({string.Join(", ", parameters)})");
                WriteLine("{");
                PushIndent();
                WriteLine("var value = reader.GetString();");
                WriteLine($"var culture =  {GlobalizationNamespace}.CultureInfo.InvariantCulture;");
                WriteLine("");
                WriteLine($"if ({Data.TypeName}.TryParse(value, culture, out var result))");
                PushIndent();
                WriteLine("return result;");
                PopIndent();
                WriteLine("");
                WriteLine($$"""var errorMessage = $"Unable to parse '{value}' as {{Data.TypeName}}."; """);
                WriteLine($"throw new {JsonNamespace}.JsonException(errorMessage);");
                PopIndent();
                WriteLine("}");
                WriteLine("");
            }


            {
                string[] parameters =
                [
                    $"{JsonNamespace}.Utf8JsonWriter writer",
                    $"{Data.TypeName} value",
                    $"{JsonNamespace}.JsonSerializerOptions options"
                ];

                WriteLine("/// <inheritdoc />");
                WriteLine($"public override void Write({string.Join(", ", parameters)})");
                WriteLine("{");
                PushIndent();
                WriteLine("writer.WriteStringValue(value.ToString());");
                PopIndent();
                WriteLine("}");
                WriteLine("");

                PopIndent();
                WriteLine("}");
                WriteLine("");
            }
        }

        void GenerateIParseableCode()
        {
            {
                string[] parameters =
                [
                    $"{StringType} s",
                    $"{SystemNamespace}.IFormatProvider? provider"
                ];

                WriteLine("/// <inheritdoc />");
                WriteLine($"public static {Data.TypeName} Parse({string.Join(", ", parameters)})");
                WriteLine("{");
                PushIndent();
                WriteLine("if (TryParse(s, provider, out var result)) return result;");
                WriteLine("");
                WriteLine($$"""var errorMessage = $"'{s}' is not a valid {{Data.TypeName}}.";""");
                WriteLine($"throw new {SystemNamespace}.FormatException(errorMessage);");
                PopIndent();
                WriteLine("}");
                WriteLine("");
            }

            if (!Data.Methods.Any(m => m is { Name: "TryParse", IsStatic: true, Parameters.Count: 3 }))
            {
                string[] parameters =
                [
                    $"[{CodeAnalysisNamespace}.NotNullWhen(true)] {StringType}? s",
                    $"{SystemNamespace}.IFormatProvider? provider",
                    $"[{CodeAnalysisNamespace}.MaybeNullWhen(false)] out {Data.TypeName} result"
                ];

                WriteLine("/// <inheritdoc />");
                WriteLine($"public static {BoolType} TryParse({string.Join(", ", parameters)})");
                WriteLine("{");
                PushIndent();
                WriteLine("result = default;");
                WriteLine($"if ({StringType}.IsNullOrWhiteSpace(s)) return false;");

                if (type == "string")
                {
                    WriteLine("return true;");
                }
                else
                {
                    WriteLine($"if ({type}.TryParse(s, provider, out var value))");
                    WriteLine("{");
                    PushIndent();
                    WriteLine($"result = {FactoryMethodName}(value);");
                    WriteLine("return true;");
                    PopIndent();
                    WriteLine("}");
                    WriteLine("return false;");
                }

                PopIndent();
                WriteLine("}");
                WriteLine("");
            }


            WriteLine("/// <inheritdoc />");
            WriteLine($"public static {Data.TypeName} Parse({StringType} s) => ");
            PushIndent();
            WriteLine($"Parse(s, {GlobalizationNamespace}.CultureInfo.CurrentCulture);");
            PopIndent();
            WriteLine("");

            {
                string[] parameters =
                [
                    $"[{CodeAnalysisNamespace}.NotNullWhen(true)] {StringType}? s",
                    $"[{CodeAnalysisNamespace}.MaybeNullWhen(false)] out {Data.TypeName} result"
                ];

                WriteLine("/// <inheritdoc />");
                WriteLine($"public static {BoolType} TryParse({string.Join(", ", parameters)}) =>");
                PushIndent();
                WriteLine($"TryParse(s, {GlobalizationNamespace}.CultureInfo.CurrentCulture, out result);");
                PopIndent();
                WriteLine("");
            }
        }
    }

    private void GenerateCommonImplementation()
    {
        var nullable = !Data.IsStruct ? "?" : "";

        WriteLine("/// <inheritdoc />");
        WriteLine($"public override {IntType} GetHashCode()");
        WriteLine("{");
        PushIndent();
        WriteLine($"var hashCode = new {SystemNamespace}.HashCode();");
        WriteLine($"foreach (var obj in {EqualityMethodName}())");
        WriteLine("{");
        PushIndent();
        WriteLine($"if (obj is {CollectionNamespace}.IEnumerable enumerable && obj is not {StringType})");
        WriteLine("{");
        PushIndent();
        WriteLine("foreach (var item in enumerable)");
        WriteLine("{");
        PushIndent();
        WriteLine("hashCode.Add(item);");
        PopIndent();
        WriteLine("}");
        PopIndent();
        WriteLine("}");
        WriteLine("else");
        WriteLine("{");
        PushIndent();
        WriteLine("hashCode.Add(obj);");
        PopIndent();
        WriteLine("}");
        PopIndent();
        WriteLine("}");
        WriteLine("return hashCode.ToHashCode();");
        PopIndent();
        WriteLine("}");
        WriteLine("");

        WriteLine("/// <inheritdoc />");
        WriteLine($"public {IntType} CompareTo({Data.TypeName}{nullable} other)");
        WriteLine("{");
        PushIndent();

        if (!Data.IsStruct)
        {
            WriteLine("if (other is null) return 1;");
            WriteLine("if (ReferenceEquals(this, other)) return 0;");
        }

        WriteLine($"using var thisEnumerator = {EqualityMethodName}().GetEnumerator();");
        WriteLine($"using var otherEnumerator = other.{EqualityMethodName}().GetEnumerator();");
        WriteLine("");
        WriteLine("while (thisEnumerator.MoveNext() && otherEnumerator.MoveNext())");
        WriteLine("{");
        PushIndent();
        WriteLine("if (thisEnumerator.Current is null && otherEnumerator.Current is null) continue;");
        WriteLine("if (thisEnumerator.Current is null) return -1;");
        WriteLine("if (otherEnumerator.Current is null) return 1;");
        WriteLine("");
        WriteLine($"if (thisEnumerator.Current is {SystemNamespace}.IComparable comparable)");
        WriteLine("{");
        PushIndent();
        WriteLine("var result = comparable.CompareTo(otherEnumerator.Current);");
        WriteLine("if (result != 0) return result;");
        PopIndent();
        WriteLine("}");
        PopIndent();
        WriteLine("}");
        WriteLine("");
        WriteLine("return 0;");
        PopIndent();
        WriteLine("}");
        WriteLine("");

        WriteLine("/// <inheritdoc />");
        WriteLine($"public {IntType} CompareTo({ObjectType}? obj)");
        WriteLine("{");
        PushIndent();
        WriteLine($"return obj is {Data.TypeName} other ? this.CompareTo(other) : 0;");
        PopIndent();
        WriteLine("}");
        WriteLine("");

        WriteLine("/// <inheritdoc />");
        WriteLine($"public {BoolType} Equals({Data.TypeName}{nullable} other)");
        WriteLine("{");
        PushIndent();

        if (!Data.IsStruct)
        {
            WriteLine("if (other is null) return false;");
            WriteLine("if (ReferenceEquals(this, other)) return true;");
        }

        WriteLine($"using var thisEnumerator = this.{EqualityMethodName}().GetEnumerator();");
        WriteLine($"using var otherEnumerator = other.{EqualityMethodName}().GetEnumerator();");
        WriteLine("");
        WriteLine("while (thisEnumerator.MoveNext() && otherEnumerator.MoveNext())");
        WriteLine("{");
        PushIndent();
        WriteLine($"if (thisEnumerator.Current is {CollectionNamespace}.IEnumerable thisEnumerable &&");
        WriteLine($"    otherEnumerator.Current is {CollectionNamespace}.IEnumerable otherEnumerable &&");
        WriteLine($"    thisEnumerator.Current is not {StringType})");
        WriteLine("{");
        PushIndent();
        WriteLine($"if (!{LinqNamespace}.Enumerable.SequenceEqual(");
        PushIndent();
        WriteLine($"{LinqNamespace}.Enumerable.Cast<{ObjectType}>(thisEnumerable),");
        WriteLine($"{LinqNamespace}.Enumerable.Cast<{ObjectType}>(otherEnumerable)))");
        WriteLine("return false;");
        PopIndent();
        PopIndent();
        WriteLine("}");
        WriteLine($"else if (!{ObjectType}.Equals(thisEnumerator.Current, otherEnumerator.Current))");
        WriteLine("{");
        PushIndent();
        WriteLine("return false;");
        PopIndent();
        WriteLine("}");
        PopIndent();
        WriteLine("}");
        WriteLine("");
        WriteLine("return !thisEnumerator.MoveNext() && !otherEnumerator.MoveNext();");
        PopIndent();
        WriteLine("}");
        WriteLine("");

        WriteLine("/// <inheritdoc />");
        WriteLine($"public override {BoolType} Equals({ObjectType}? obj)");
        WriteLine("{");
        PushIndent();
        WriteLine($"return obj is {Data.TypeName} other && Equals(other);");
        PopIndent();
        WriteLine("}");
        WriteLine("");

        WriteLine("/// <inheritdoc />");
        WriteLine(
            $"public static {BoolType} operator ==({Data.TypeName}{nullable} left, {Data.TypeName}{nullable} right)");
        WriteLine("{");
        PushIndent();

        if (!Data.IsStruct)
        {
            WriteLine("if (left is null || right is null) return false;");
            WriteLine("if (ReferenceEquals(left, right)) return true;");
        }

        WriteLine("return left.Equals(right);");
        PopIndent();
        WriteLine("}");
        WriteLine("");

        WriteLine("/// <inheritdoc />");
        WriteLine(
            $"public static {BoolType} operator !=({Data.TypeName}{nullable} left, {Data.TypeName}{nullable} right)");
        WriteLine("{");
        PushIndent();
        WriteLine("return !(left == right);");
        PopIndent();
        WriteLine("}");
        WriteLine("");

        WriteLine("/// <inheritdoc />");
        WriteLine($"public static {BoolType} operator <({Data.TypeName} left, {Data.TypeName} right)");
        WriteLine("{");
        PushIndent();
        WriteLine("return left.CompareTo(right) < 0;");
        PopIndent();
        WriteLine("}");
        WriteLine("");

        WriteLine("/// <inheritdoc />");
        WriteLine($"public static {BoolType} operator >({Data.TypeName} left, {Data.TypeName} right)");
        WriteLine("{");
        PushIndent();
        WriteLine("return left.CompareTo(right) > 0;");
        PopIndent();
        WriteLine("}");
        WriteLine("");
    }
}