using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;
using Majal.Common;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Majal.Generators.ValueObjects;

/// <summary>
/// Generates a partial class for every class marked with [ValueObject].
/// The generated class implements IValueObject and adds equality, comparison, and hashing logic.
/// </summary>
[Generator]
public sealed class ValueObjectGenerator : IIncrementalGenerator
{
    private readonly record struct PropertyData(string Name, string Type)
    {
        public string Name { get; } = Name;
        public string Type { get; } = Type;
    }

    // Record struct to hold the data needed to generate the aggregate root class
    private readonly record struct ValueObjectData
    {
        public string Name { get; }
        public string Namespace { get; }
        public bool HasConstructor { get; }
        public EquatableList<PropertyData> Properties { get; }

        public ValueObjectData(string name, string @namespace, bool hasConstructor, PropertyData[] properties)
        {
            Name = name;
            Namespace = @namespace;
            HasConstructor = hasConstructor;
            Properties = new EquatableList<PropertyData>(properties);
        }
    }

    private const string ValueObjectFilenameSuffix = ".ValueObject.g.cs";
    private const string ValueObjectAttributeFilename = "ValueObjectAttribute.g.cs";
    private const string ValueObjectMarkerInterfaceFilename = "IValueObject.g.cs";
    private const string ValueObjectAttributeFullName = "Majal.ValueObjectAttribute";
    private const string AutoGeneratedHeader = "// <auto-generated />";
    private const string NullableEnable = "#nullable enable";


    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        RegisterPredefinedTypes(context);
        RegisterEntityGenerators(context);
    }

    /// <summary>
    /// Registers the predefined types (IValueObject, ValueObjectAttribute, ValueObjectAttribute`1)
    /// that will be available to all generated code.
    /// </summary>
    private static void RegisterPredefinedTypes(IncrementalGeneratorInitializationContext context)
    {
        // Register marker types and attributes that will be available to all generated code
        context.RegisterPostInitializationOutput(ctx =>
        {
            ctx.AddSource(ValueObjectAttributeFilename, Sources.ValueObjectAttributeSource);
            ctx.AddSource(ValueObjectMarkerInterfaceFilename, Sources.ValueObjectMarkerInterfaceSource);
        });
    }

    /// <summary>
    /// Registers the entity generator pipeline that processes classes marked with [ValueObject].
    /// </summary>
    private static void RegisterEntityGenerators(IncrementalGeneratorInitializationContext context)
    {
        // Get classes with attributes
        var valueObjectsToGenerate = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                ValueObjectAttributeFullName,
                predicate: (node, _) => node is ClassDeclarationSyntax { AttributeLists.Count: > 0 },
                transform: GetDataToGenerate
            );
        
        // Filter to classes that carry the [ValueObject] attribute
        var entities = valueObjectsToGenerate
            .Where(static m => m is not null)
            .Select(static (m, _) => m!.Value);

        // Generate source for each entity
        context.RegisterSourceOutput(entities, (spc, classSymbol) =>
        {
            var source = GeneratePartialClass(classSymbol);
            spc.AddSource($"{classSymbol.Name}{ValueObjectFilenameSuffix}", SourceText.From(source, Encoding.UTF8));
        });
    }


    /// <summary>
    /// Extracts the necessary information from the class symbol to generate the ValueObject class.
    /// </summary>
    /// <param name="context"></param>
    /// <param name="ct"></param>
    /// <returns>EntityToGenerate?</returns>
    private static ValueObjectData? GetDataToGenerate(GeneratorAttributeSyntaxContext context, CancellationToken ct)
    {
        if (context.TargetSymbol is not INamedTypeSymbol classSymbol) return null;

        var typeName = classSymbol.Name;

        if (classSymbol.TypeParameters.Length > 0)
            typeName += $"<{string.Join(", ", classSymbol.TypeParameters.Select(t => t.Name))}>";

        var properties = classSymbol.GetMembers()
            .OfType<IPropertySymbol>()
            .Where(p => p.GetMethod?.DeclaredAccessibility is Accessibility.Public)
            .Select(p => new PropertyData(p.Name, Type: p.Type.ToDisplayString()));

        return new ValueObjectData(
            name: typeName,
            @namespace: $"namespace {classSymbol.ContainingNamespace.ToDisplayString()};",
            hasConstructor: classSymbol.Constructors.Any(c => !c.IsImplicitlyDeclared),
            properties: [..properties]
        );
    }


    /// <summary>
    /// Generates the common header for generated code files.
    /// </summary>
    private static void AppendCodeHeader(StringBuilder sb, ValueObjectData data)
    {
        sb.AppendLine(AutoGeneratedHeader);
        sb.AppendLine();
        sb.AppendLine(NullableEnable);
        sb.AppendLine();
        sb.AppendLine(data.Namespace);
        sb.AppendLine();
    }

    /// <summary>
    /// Appends the class definition line with appropriate interfaces.
    /// </summary>
    private static void AppendClassDeclaration(StringBuilder sb, ValueObjectData data)
    {
        List<string> interfaces =
        [
            "global::Majal.IValueObject",
            "global::System.IComparable",
            $"global::System.IComparable<{data.Name}>"
        ];

        sb.AppendLine($"public partial class {data.Name} : {string.Join(", ", interfaces)}");
        sb.AppendLine("{");
        sb.AppendLine();
    }

    /// <summary>
    /// Appends the private fields.
    /// </summary>
    private static void AppendPrivateFields(StringBuilder sb)
    {
        sb.AppendLine("    private global::System.Int32? _cachedHashCode;");
        sb.AppendLine();
    }

    /// <summary>
    /// Appends the constructor.
    /// </summary>
    private static void AppendConstructor(StringBuilder sb, ValueObjectData data)
    {
        if (data.HasConstructor) return;

        sb.AppendLine($"    private {data.Name}()");
        sb.AppendLine("    {");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    /// <summary>
    /// Appends the Create Factory method.
    /// </summary>
    private static void AppendCreateFactoryMethod(StringBuilder sb, ValueObjectData data)
    {
        if (data.Properties.Count == 0) return;
        var parameters = string.Join(", ", data.Properties.Select(p => $"{p.Type} {p.Name.SnakeCase}"));
        sb.AppendLine($"    public static partial {data.Name} Create({parameters});");
        sb.AppendLine();
    }

    /// <summary>
    /// Appends the GetEqualityComponents method.
    /// </summary>
    private static void AppendGetEqualityComponents(StringBuilder sb)
    {
        sb.AppendLine(
            "    private partial global::System.Collections.Generic.IEnumerable<global::System.Object?> GetEqualityComponents();");
        sb.AppendLine();
    }

    /// <summary>
    /// Appends the Equals method override.
    /// </summary>
    private static void AppendEquals(StringBuilder sb, ValueObjectData data)
    {
        sb.AppendLine("    public override global::System.Boolean Equals(global::System.Object? obj)");
        sb.AppendLine("    {");
        sb.AppendLine($"        if (obj is not {data.Name} other) return false;");
        sb.AppendLine("        return GetEqualityComponents().SequenceEqual(other.GetEqualityComponents());");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    /// <summary>
    /// Appends the equality operators (== and !=).
    /// </summary>
    private static void AppendEqualityOperators(StringBuilder sb, ValueObjectData data)
    {
        sb.AppendLine($"    public static global::System.Boolean operator ==({data.Name} a, {data.Name} b)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (a is null && b is null) return true;");
        sb.AppendLine("        if (a is null || b is null) return false;");
        sb.AppendLine("        return a.Equals(b);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    public static global::System.Boolean operator !=({data.Name} a, {data.Name} b)");
        sb.AppendLine("    {");
        sb.AppendLine("        return !(a == b);");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    /// <summary>
    /// Appends the GetHashCode override with caching.
    /// </summary>
    private static void AppendGetHashCode(StringBuilder sb)
    {
        sb.AppendLine("    public override global::System.Int32 GetHashCode()");
        sb.AppendLine("    {");
        sb.AppendLine("        if (!_cachedHashCode.HasValue)");
        sb.AppendLine("        {");
        sb.AppendLine("            _cachedHashCode = GetEqualityComponents()");
        sb.AppendLine("                .Aggregate(1, (current, obj) =>");
        sb.AppendLine("                {");
        sb.AppendLine("                    unchecked");
        sb.AppendLine("                    {");
        sb.AppendLine("                        return current * 23 + (obj?.GetHashCode() ?? 0);");
        sb.AppendLine("                    }");
        sb.AppendLine("                });");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        return _cachedHashCode.Value;");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    /// <summary>
    /// Appends the CompareTo methods for IComparable implementation.
    /// </summary>
    private static void AppendCompareTo(StringBuilder sb, ValueObjectData data)
    {
        sb.AppendLine($"    public global::System.Int32 CompareTo({data.Name}? other)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (other is null) return 1;");
        sb.AppendLine();
        sb.AppendLine("        if (ReferenceEquals(this, other)) return 0;");
        sb.AppendLine();
        sb.AppendLine("        if (this.GetType() != other.GetType())");
        sb.AppendLine(
            "            return global::System.String.Compare(this.GetType().FullName, other.GetType().FullName, global::System.StringComparison.Ordinal);");
        sb.AppendLine();
        sb.AppendLine("        return GetEqualityComponents()");
        sb.AppendLine("                 .OfType<global::System.IComparable>()");
        sb.AppendLine(
            "                 .Zip(other.GetEqualityComponents().OfType<global::System.IComparable>(), (a, b) => a?.CompareTo(b) ?? (b is null ? 0 : -1))");
        sb.AppendLine("                 .FirstOrDefault();");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    public global::System.Int32 CompareTo(global::System.Object? other)");
        sb.AppendLine("    {");
        sb.AppendLine($"        return CompareTo(other as {data.Name});");
        sb.AppendLine("    }");
        sb.AppendLine();
    }


    /// <summary>
    /// Appends the ToString override.
    /// </summary>
    private static void AppendToString(StringBuilder sb, ValueObjectData data)
    {
        sb.AppendLine("    public override global::System.String ToString()");
        sb.AppendLine("    {");
        sb.AppendLine("        var sb = new global::System.Text.StringBuilder();");
        sb.AppendLine("""        sb.Append("{ ");""");

        var properties = data.Properties;
        var lastProperty = properties.LastOrDefault();

        foreach (var property in properties)
        {
            sb.AppendLine($$"""        sb.Append($"{{property.Name}} = {{{property.Name}}}");""");
            if (lastProperty != property)
                sb.AppendLine("""        sb.Append(", ");""");
        }

        sb.AppendLine("""        sb.Append(" }");""");
        sb.AppendLine("        return sb.ToString();");

        sb.AppendLine("    }");
        sb.AppendLine();
    }


    /// <summary>
    /// Generates the common footer for generated code files.
    /// </summary>
    private static void AppendCodeFooter(StringBuilder sb)
    {
        sb.AppendLine("}");
        sb.AppendLine();
    }

    /// <summary>
    /// Generates the partial class that implements IValueObject and equality/comparison logic.
    /// </summary>
    private static string GeneratePartialClass(ValueObjectData data)
    {
        var sb = new StringBuilder();

        AppendCodeHeader(sb, data);

        AppendClassDeclaration(sb, data);

        AppendConstructor(sb, data);

        AppendCreateFactoryMethod(sb, data);

        AppendPrivateFields(sb);

        AppendEquals(sb, data);

        AppendEqualityOperators(sb, data);

        AppendGetHashCode(sb);

        AppendCompareTo(sb, data);

        AppendGetEqualityComponents(sb);

        AppendToString(sb, data);

        AppendCodeFooter(sb);

        return sb.ToString();
    }
}