//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Majal source generator
// </auto-generated>
//------------------------------------------------------------------------------

namespace Majal;

/// <summary>
/// Options for configuring the EntityAttribute.
/// </summary>
[global::System.Flags]
public enum EntityOptions
{
    Default = 0,

    /// <summary>
    /// Indicates that the entity should have an Ordinal property for custom ordering.
    /// </summary>
    Ordinal = 1 << 0,

    /// <summary>
    /// Indicates that the entity should be auditable.
    /// </summary>
    Auditable = 1 << 1,

    /// <summary>
    /// Indicates that the entity should be archivable.
    /// </summary>
    Archivable = 1 << 2,

    /// <summary>
    /// Indicates that the entity should have all optional features (Ordinal, Auditable, Archivable).
    /// </summary>
    All = Auditable | Archivable | Ordinal
}

/// <summary>
/// Apply to a class to indicate it is a DDD entity with a specific Id type.
/// The generator will create a partial class with domain-event helpers.
/// </summary>
[global::System.AttributeUsage(global::System.AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
public sealed class EntityAttribute<TId>(global::Majal.EntityOptions options) : global::System.Attribute
{
    /// <summary>
    /// The options for configuring the entity generation.
    /// </summary>
    public global::Majal.EntityOptions Options { get; } = options;

    public EntityAttribute() : this(global::Majal.EntityOptions.Default)
    {
    }
}