//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Majal source generator
// </auto-generated>
//------------------------------------------------------------------------------

namespace Majal;

/// <summary>
/// Marker interface for domain aggregates entities.
/// </summary>
public interface IAggregateRoot<TDomainEvent>
{
    ///<summary>
    /// Gets the list of events associated with the aggregate root.
    ///</summary>
    global::System.Collections.Generic.IEnumerable<TDomainEvent> Events { get; }

    ///<summary>
    /// Publishes a domain event by adding it to the Events collection. 
    /// This method is typically called within the aggregate root's methods to record significant state changes or actions that occur within the aggregate.
    /// The published events can then be processed by event handlers or dispatched to other parts of the
    /// system for further handling, such as updating read models, triggering side effects, or integrating with external systems.
    ///</summary>
    void Publish(TDomainEvent @event);

    ///<summary>
    /// Clears all domain events from the Events collection.
    /// This method is typically called after the events have been successfully processed and persisted, 
    /// to reset the state of the aggregate root's event collection and prepare it for recording new events.
    /// </summary>
    void Clear();
}