//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Majal source generator
// </auto-generated>
//------------------------------------------------------------------------------

namespace Majal;

/// <summary>
/// Marker interface for ordinal domain entities.
/// </summary>
public interface IOrdinalEntity
{
    /// <summary>
    /// An optional property that can be used to define a custom ordering of entities. 
    /// This is particularly useful in scenarios where entities need to be displayed or processed in a specific sequence.
    /// The Ordinal property is typically a non-negative integer that indicates the position of the entity in the desired order. 
    /// It can be set and updated as needed to maintain the correct ordering of entities.
    /// </summary>
    global::System.UInt32 Ordinal { get; }
}