// <auto-generated />
using System;
using Majal.Sample.Common.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Majal.Sample.Common.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260502193818_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.6");

            modelBuilder.Entity("Majal.Sample.Modules.Issues.Entities.Issue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ArchivedOn")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("Ordinal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<int>("StoryPoints")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedOn")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Issues", (string)null);

                    b.HasDiscriminator<string>("Status").IsComplete(true).HasValue("Issue");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Majal.Sample.Modules.Projects.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ArchivedOn")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<uint>("Ordinal")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("UpdatedOn")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Majal.Sample.Modules.Projects.Entities.ProjectTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "Locale")
                        .IsUnique();

                    b.ToTable("ProjectsTranslations", (string)null);
                });

            modelBuilder.Entity("Majal.Sample.Modules.Issues.Entities.PendingIssue", b =>
                {
                    b.HasBaseType("Majal.Sample.Modules.Issues.Entities.Issue");

                    b.HasDiscriminator().HasValue("Pending");
                });

            modelBuilder.Entity("Majal.Sample.Modules.Issues.Entities.ResolvedIssue", b =>
                {
                    b.HasBaseType("Majal.Sample.Modules.Issues.Entities.Issue");

                    b.Property<DateTimeOffset>("ResolvedOn")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Resolved");
                });

            modelBuilder.Entity("Majal.Sample.Modules.Issues.Entities.Issue", b =>
                {
                    b.HasOne("Majal.Sample.Modules.Projects.Entities.Project", "Project")
                        .WithMany("Issues")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Majal.Sample.Modules.Projects.Entities.ProjectTranslation", b =>
                {
                    b.HasOne("Majal.Sample.Modules.Projects.Entities.Project", null)
                        .WithMany("Translations")
                        .HasForeignKey("ProjectId");
                });

            modelBuilder.Entity("Majal.Sample.Modules.Projects.Entities.Project", b =>
                {
                    b.Navigation("Issues");

                    b.Navigation("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
