using Majal.Common.Abstractions;
using static Majal.Common.Abstractions.Constants;

namespace Majal.Generators.Translatables;

public class TranslatableTemplate : BaseTemplate
{
    public TranslatableGenerator.TranslatableData Data { get; init; }

    public override string TransformText()
    {
        Clear();
        WriteLine("// <auto-generated />");
        WriteLine("");
        WriteLine("#nullable enable");
        WriteLine("");
        WriteLine(Data.Namespace);
        WriteLine("");

        var type = Data.Value?.GenericType ?? StringType;

        WriteLine("/// <summary>");
        WriteLine($"/// Provides locale-based filtering support for <see cref=\"{Data.TypeName}\"/>.");
        WriteLine("/// </summary>");
        WriteLine($"public partial class {Data.TypeName} : {MajalNamespace}.ITranslatable<{type}>");
        WriteLine("{");
        PushIndent();
        WriteLine("/// <inheritdoc />");
        WriteLine($"public required {type} Locale {{ get; set; }}");
        PopIndent();
        WriteLine("}");

        return ToString();
    }
}