using Majal.Common.Abstractions;

namespace Majal.Generators.Translatables;

public class TranslatableExtensionsTemplate : BaseTemplate
{
    public string Namespace { get; init; } = "Majal";
    public string[] Locales { get; init; } = [];
    public string LocaleType { get; init; } = "string";
    public string? ExceptionType { get; init; }
    public bool ExceptionHasStringConstructor { get; init; } = true;

    public override string TransformText()
    {
        Clear();
        WriteLine("// <auto-generated />");
        WriteLine("");
        WriteLine("#nullable enable");
        WriteLine("");
        WriteLine("using System;");
        WriteLine("using System.Collections.Generic;");
        WriteLine("using System.Linq;");
        WriteLine("");
        WriteLine($"namespace {Namespace};");
        WriteLine("");
        WriteLine("/// <summary>");
        WriteLine("/// Provides extension methods and supported locales for translatable entities.");
        WriteLine("/// </summary>");
        WriteLine("public static class TranslatableExtensions");
        WriteLine("{");
        PushIndent();

        var localesFormatted = string.Join(", ", Locales.Select(l => $"\"{l}\""));
        WriteLine("/// <summary>");
        WriteLine("/// The supported locales configured for the application.");
        WriteLine("/// </summary>");
        WriteLine($"public static readonly string[] Locales = [{localesFormatted}];");
        WriteLine("");

        var isStringLocale = LocaleType is "string" or "global::System.String";
        var localeComparison = isStringLocale
            ? "string.Equals(t.Locale, l, StringComparison.OrdinalIgnoreCase)"
            : "string.Equals(t.Locale?.ToString(), l, StringComparison.OrdinalIgnoreCase)";

        var isSupportedExpr = isStringLocale
            ? "locale is not null && Locales.Contains(locale, StringComparer.OrdinalIgnoreCase)"
            : "locale is not null && Locales.Contains(locale.ToString(), StringComparer.OrdinalIgnoreCase)";

        WriteLine("/// <summary>");
        WriteLine("/// Throws an exception if any supported locale is missing from the translations collection.");
        WriteLine("/// </summary>");
        WriteLine(
            $"public static void ThrowIfMissingTranslations(this IEnumerable<global::Majal.ITranslatable<{LocaleType}>> translations)");
        WriteLine("{");
        PushIndent();
        WriteLine("if (translations is null)");
        WriteLine("{");
        PushIndent();
        WriteLine("throw new ArgumentNullException(nameof(translations));");
        PopIndent();
        WriteLine("}");
        WriteLine("");
        WriteLine("if (translations.IsMissingTranslations())");
        WriteLine("{");
        PushIndent();
        if (!string.IsNullOrEmpty(ExceptionType))
        {
            if (ExceptionHasStringConstructor)
            {
                WriteLine($"throw new {ExceptionType}(");
                WriteLine("    $\"Missing translations, please provide translations for {string.Join(',', Locales)}\");");
            }
            else
            {
                WriteLine($"throw new {ExceptionType}();");
            }
        }
        else
        {
            WriteLine("throw new InvalidOperationException(");
            WriteLine("    $\"Missing translations, please provide translations for {string.Join(',', Locales)}\");");
        }
        PopIndent();
        WriteLine("}");
        PopIndent();
        WriteLine("}");
        WriteLine("");

        WriteLine("/// <summary>");
        WriteLine("/// Checks whether any supported locale is missing from the translations collection.");
        WriteLine("/// </summary>");
        WriteLine(
            $"public static bool IsMissingTranslations(this IEnumerable<global::Majal.ITranslatable<{LocaleType}>> translations)");
        WriteLine("{");
        PushIndent();
        WriteLine("if (translations is null) return true;");
        WriteLine($"return !Locales.All(l => translations.Any(t => {localeComparison}));");
        PopIndent();
        WriteLine("}");
        WriteLine("");

        WriteLine("/// <summary>");
        WriteLine("/// Checks whether the specified locale is supported.");
        WriteLine("/// </summary>");
        WriteLine($"public static bool IsLocaleSupported(this {LocaleType} locale) => {isSupportedExpr};");

        PopIndent();
        WriteLine("}");

        return ToString();
    }
}
