using System.Linq;
using Majal.Common.Abstractions;
using static Majal.Common.Abstractions.Constants;

namespace Majal.Generators.Translatables;

public class TranslatableExtensionsTemplate : BaseTemplate
{
    public string Namespace { get; init; } = "Majal";
    public string[] Locales { get; init; } = [];
    public string LocaleType { get; init; } = "string";

    public override string TransformText()
    {
        Clear();
        WriteLine("// <auto-generated />");
        WriteLine("");
        WriteLine("#nullable enable");
        WriteLine("");
        WriteLine("using System;");
        WriteLine("using System.Collections.Generic;");
        WriteLine("using System.Linq;");
        WriteLine("");
        WriteLine($"namespace {Namespace};");
        WriteLine("");
        WriteLine("/// <summary>");
        WriteLine("/// Provides extension methods and supported locales for translatable entities.");
        WriteLine("/// </summary>");
        WriteLine("public static class TranslatableExtensions");
        WriteLine("{");
        PushIndent();

        var localesFormatted = string.Join(", ", Locales.Select(l => $"\"{l}\""));
        WriteLine("/// <summary>");
        WriteLine("/// The supported locales configured for the application.");
        WriteLine("/// </summary>");
        WriteLine($"public static readonly string[] Locales = [{localesFormatted}];");
        WriteLine("");

        WriteLine("/// <summary>");
        WriteLine("/// Throws an exception if any supported locale is missing from the translations collection.");
        WriteLine("/// </summary>");
        WriteLine($"public static void ThrowIfMissingTranslations(this IEnumerable<global::Majal.ITranslatable<{LocaleType}>> translations)");
        WriteLine("{");
        PushIndent();
        WriteLine("if (translations.IsMissingTranslations())");
        WriteLine("{");
        PushIndent();
        WriteLine("throw new Exception(");
        WriteLine("    $\"Missing translations, please provide translations for {string.Join(',', Locales)}\");");
        PopIndent();
        WriteLine("}");
        PopIndent();
        WriteLine("}");
        WriteLine("");

        WriteLine("/// <summary>");
        WriteLine("/// Checks whether any supported locale is missing from the translations collection.");
        WriteLine("/// </summary>");
        WriteLine($"public static bool IsMissingTranslations(this IEnumerable<global::Majal.ITranslatable<{LocaleType}>> translations)");
        WriteLine("{");
        PushIndent();
        WriteLine("return !Locales.All(l => translations.Any(t => t.Locale.Equals(l, StringComparison.OrdinalIgnoreCase)));");
        PopIndent();
        WriteLine("}");
        WriteLine("");

        WriteLine("/// <summary>");
        WriteLine("/// Checks whether the specified locale is supported.");
        WriteLine("/// </summary>");
        WriteLine($"public static bool IsLocaleSupported(this {LocaleType} locale) => Locales.Contains(locale);");

        PopIndent();
        WriteLine("}");

        return ToString();
    }
}
