using Majal.Common.Abstractions;
using static Majal.EntityFrameworkCore.Common.EfCoreConstants;

namespace Majal.Generators.ValueObjects;

public class ValueObjectEfCoreConverterTemplate : BaseTemplate
{
    public const string EfCoreValueConverterTypeName = "EfCoreValueConverter";

    public ValueObjectEfCoreData Data { get; init; }

    public override string TransformText()
    {
        Clear();
        WriteLine("// <auto-generated />");
        WriteLine("");
        WriteLine("#nullable enable");
        WriteLine("");
        WriteLine(Data.Namespace);
        WriteLine("");

        var typeKeyword = Data.IsStruct ? "struct" : "class";
        WriteLine($"public partial {typeKeyword} {Data.TypeName}");
        WriteLine("{");
        PushIndent();
        WriteLine("/// <summary>Provides an EF Core <c>ValueConverter</c> for persisting this value object as its primitive type.</summary>");
        WriteLine($"public sealed class {EfCoreValueConverterTypeName}() :");
        PushIndent();
        WriteLine($"{EfCoreValueConversion}.ValueConverter<{Data.TypeName}, {Data.GenericType}>(v => v.Value, v => Create(v))");
        PopIndent();
        WriteLine("{");
        WriteLine("}");
        PopIndent();
        WriteLine("}");

        return ToString();
    }
}