//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Majal source generator
// </auto-generated>
//------------------------------------------------------------------------------

namespace Majal;

/// <summary>
/// Marker interface for archivable domain entities.
/// </summary>
public interface IArchivableEntity
{
    /// <summary>
    /// Indicates whether the entity is archived. 
    /// This property is typically used to soft-delete entities or to mark them as inactive without physically removing them from the database.
    /// When IsArchived is true, the entity is considered archived and should be excluded from active
    /// queries and operations, while still retaining its data for historical reference or potential restoration.
    /// </summary>
    global::System.Boolean IsArchived { get; }

    /// <summary>
    /// The date and time when the entity was archived. 
    /// This property is typically set when an entity is marked as archived and can be used for auditing purposes or to determine how long an entity has been archived.
    /// It is nullable to allow for entities that have not been archived.
    /// </summary>
    global::System.DateTime? ArchivedOn { get; }
}