//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Majal source generator
// </auto-generated>
//------------------------------------------------------------------------------

namespace Majal;

/// <summary>
/// Marker interface for domain entities.
/// </summary>
public interface IEntity<out TId>
{
    /// <summary>
    /// The unique identifier for the entity. This property is typically set at creation and is immutable.
    /// The type of the Id is determined by the generic parameter TId,
    /// allowing for flexibility in choosing different types of identifiers (e.g., int, Guid, string).
    /// </summary>
    TId Id { get; }
}