using Majal.Common.Abstractions;
using Majal.Generators.Dtos.Models;
using Microsoft.CodeAnalysis;
using static Majal.Common.Abstractions.Constants;

namespace Majal.Generators.Dtos;

public class DtoForTemplate : BaseTemplate
{
    public DtoData Data { get; init; }

    public override string TransformText()
    {
        Clear();

        WriteLine("// <auto-generated />");
        WriteLine("");
        WriteLine("#nullable enable");
        WriteLine("");
        WriteLine(Data.Namespace);
        WriteLine("");

        if (Data.ParentTypeDeclarations.Count > 0)
        {
            foreach (var declaration in Data.ParentTypeDeclarations)
            {
                WriteLine(declaration);
                WriteLine("{");
                PushIndent();
            }

            GenerateDto(Data);

            for (var i = 0; i < Data.ParentTypeDeclarations.Count; i++)
            {
                PopIndent();
                WriteLine("}");
            }
        }
        else
        {
            GenerateDto(Data);
        }

        return ToString();
    }

    private void GenerateDto(DtoData dto)
    {
        var typeKeyword = dto.IsRecord ? "record" : "class";

        if (!string.IsNullOrWhiteSpace(dto.XmlDocs))
        {
            WriteLine(dto.XmlDocs!);
        }

        if (dto.DerivedTypes.Count > 0)
        {
            Write($"[{JsonSerializationNamespace}.JsonPolymorphic(UnknownDerivedTypeHandling = ");
            WriteLine($"{JsonSerializationNamespace}.JsonUnknownDerivedTypeHandling.FailSerialization)]");

            foreach (var dt in dto.DerivedTypes)
            {
                Write($"[{JsonSerializationNamespace}.JsonDerivedType(typeof({dt.DtoName})");
                WriteLine($""", typeDiscriminator: "{ToSnakeCase(dt.Discriminator)}")]""");
            }
        }

        var isBase = dto.DerivedTypes.Count > 0 && string.IsNullOrWhiteSpace(dto.BaseDtoName);
        var inheritance = string.IsNullOrWhiteSpace(dto.BaseDtoName) ? "" : $" : {dto.BaseDtoName}";
        var modifier = "partial ";

        if (isBase) modifier = "abstract " + modifier;

        var accessModifier = dto.Accessibility switch
        {
            Accessibility.Private => "private",
            Accessibility.Internal => "internal",
            Accessibility.Protected => "protected",
            _ => "public"
        };

        WriteLine($"{accessModifier} {modifier}{typeKeyword} {dto.DtoName}{inheritance}");
        WriteLine("{");
        PushIndent();

        foreach (var param in dto.Parameters)
        {
            var propertyName = ToPascalCase(param.Declaration.Name);
            var requiredKeyword = param.IsNullable ? "" : "required ";
            if (!string.IsNullOrWhiteSpace(param.XmlDocs))
            {
                WriteLine(param.XmlDocs!);
            }

            WriteLine($"public {requiredKeyword}{param.Declaration.Type} {propertyName} {{ get; init; }}");
        }

        if (dto.ReconstructionArguments is not null)
        {
            WriteLine("");
            GenerateToSourceMethod(dto);
        }

        if (dto.NestedDtos.Count > 0)
        {
            WriteLine("");
            foreach (var nested in dto.NestedDtos)
            {
                GenerateDto(nested);
                WriteLine("");
            }
        }

        PopIndent();
        WriteLine("}");
    }

    private void GenerateToSourceMethod(DtoData dto)
    {
        WriteLine($"public {dto.SourceTypeName} To{dto.SourceSimpleName}() =>");
        PushIndent();
        WriteLine($"{dto.SourceTypeName}.{dto.FactoryMethodName}(");
        PushIndent();

        var arguments = dto.ReconstructionArguments!.Value;
        for (var i = 0; i < arguments.Count; i++)
        {
            var argument = arguments[i];
            var suffix = i < arguments.Count - 1 ? "," : "";

            if (argument.Kind != ReconstructKind.FlattenedValueObject)
            {
                WriteLine($"{argument.FactoryParameterName}: {BuildArgumentExpression(argument)}{suffix}");
                continue;
            }

            WriteLine($"{argument.FactoryParameterName}: {argument.TargetTypeName}.Create(");
            PushIndent();
            WriteArgumentLines(argument.FlattenedArguments!.Value,
                a => $"{a.SubFactoryParameterName}: this.{a.DtoPropertyName}");
            PopIndent();
            WriteLine($"){suffix}");
        }

        PopIndent();
        WriteLine(");");
        PopIndent();
    }

    private static string BuildArgumentExpression(FactoryArgument argument)
    {
        return argument.Kind switch
        {
            ReconstructKind.Direct => BuildDirectExpression(argument),
            ReconstructKind.ValueObject => BuildWrappedExpression(argument,
                value => $"{argument.TargetTypeName}.Create({value})"),
            ReconstructKind.NestedType => BuildWrappedExpression(argument,
                value => $"{value}.To{argument.TargetTypeName}()"),
            _ => $"this.{argument.DtoPropertyName}"
        };
    }

    private static string BuildDirectExpression(FactoryArgument argument)
    {
        var access = $"this.{argument.DtoPropertyName}";
        return argument.IsCollection
            ? ApplyCollectionConversion(access, argument.CollectionConversionKind)
            : access;
    }

    private static string BuildWrappedExpression(FactoryArgument argument, Func<string, string> wrap)
    {
        var access = $"this.{argument.DtoPropertyName}";

        if (argument.IsCollection)
        {
            var selectExpr = ApplyCollectionConversion(
                $"{LinqNamespace}.Enumerable.Select({access}, x => {wrap("x")})",
                argument.CollectionConversionKind);
            return argument.IsNullable ? $"{access} is null ? null : {selectExpr}" : selectExpr;
        }

        return argument.IsNullable ? $"{access} is null ? null : {wrap(access)}" : wrap(access);
    }

    private static string ApplyCollectionConversion(string expression, string conversionKind) =>
        string.IsNullOrEmpty(conversionKind)
            ? expression
            : $"{LinqNamespace}.Enumerable.{conversionKind}({expression})";

    private static string ToPascalCase(string input)
    {
        if (string.IsNullOrEmpty(input)) return input;
        return char.ToUpperInvariant(input[0]) + input.Substring(1);
    }

    private static string ToSnakeCase(string input)
    {
        if (string.IsNullOrEmpty(input)) return input;
        return char.ToLowerInvariant(input[0]) + input.Substring(1);
    }
}