using System;
using System.Collections.Generic;
using System.Linq;
using Majal.Common.Abstractions;
using Majal.Generators.Dtos.Models;
using Microsoft.CodeAnalysis;
using static Majal.Common.Abstractions.Constants;

namespace Majal.Generators.Dtos;

public class DtoForTemplate : BaseTemplate
{
    public DtoData Data { get; init; }

    public override string TransformText()
    {
        Clear();

        WriteLine("// <auto-generated />");
        WriteLine("");
        WriteLine("#nullable enable");
        WriteLine("");
        WriteLine(Data.Namespace);
        WriteLine("");

        if (Data.ParentTypeDeclarations.Count > 0)
        {
            foreach (var declaration in Data.ParentTypeDeclarations)
            {
                WriteLine(declaration);
                WriteLine("{");
                PushIndent();
            }

            GenerateDto(Data);

            for (var i = 0; i < Data.ParentTypeDeclarations.Count; i++)
            {
                PopIndent();
                WriteLine("}");
            }
        }
        else
        {
            GenerateDto(Data);
        }

        return ToString();
    }

    private void GenerateDto(DtoData dto)
    {
        var typeKeyword = dto.IsRecord ? "record" : "class";

        if (!string.IsNullOrWhiteSpace(dto.XmlDocs))
        {
            WriteLine(dto.XmlDocs!);
        }

        if (dto.DerivedTypes.Count > 0)
        {
            Write($"[{JsonSerializationNamespace}.JsonPolymorphic(UnknownDerivedTypeHandling = ");
            WriteLine($"{JsonSerializationNamespace}.JsonUnknownDerivedTypeHandling.FailSerialization)]");

            foreach (var dt in dto.DerivedTypes)
            {
                Write($"[{JsonSerializationNamespace}.JsonDerivedType(typeof({dt.DtoName})");
                WriteLine($""", typeDiscriminator: "{ToSnakeCase(dt.Discriminator)}")]""");
            }
        }

        var isBase = dto.DerivedTypes.Count > 0 && string.IsNullOrWhiteSpace(dto.BaseDtoName);
        var inheritedTypes = new List<string>();
        if (!string.IsNullOrWhiteSpace(dto.BaseDtoName)) inheritedTypes.Add(dto.BaseDtoName!);
        if (!string.IsNullOrWhiteSpace(dto.TranslatableLocaleType))
            inheritedTypes.Add($"{MajalNamespace}.ITranslatable<{dto.TranslatableLocaleType}>");

        var inheritance = inheritedTypes.Count == 0 ? "" : $" : {string.Join(", ", inheritedTypes)}";
        var modifier = "partial ";

        if (isBase) modifier = "abstract " + modifier;

        var accessModifier = dto.Accessibility switch
        {
            Accessibility.Private => "private",
            Accessibility.Internal => "internal",
            Accessibility.Protected => "protected",
            _ => "public"
        };

        WriteLine($"{accessModifier} {modifier}{typeKeyword} {dto.DtoName}{inheritance}");
        WriteLine("{");
        PushIndent();

        foreach (var param in dto.Parameters)
        {
            var propertyName = ToPascalCase(param.Declaration.Name);
            var requiredKeyword = param.IsNullable ? "" : "required ";
            if (!string.IsNullOrWhiteSpace(param.XmlDocs))
            {
                WriteLine(param.XmlDocs!);
            }

            WriteLine($"public {requiredKeyword}{param.Declaration.Type} {propertyName} {{ get; init; }}");
        }

        if (!string.IsNullOrWhiteSpace(dto.TranslatableLocaleType))
        {
            WriteLine($"public required {dto.TranslatableLocaleType} Locale {{ get; init; }}");
        }

        // Forward mapping: From and Projection
        if (dto.Directions.HasFlag(MapDirection.ToDto))
        {
            if (isBase && dto.SourceTypeName is not null)
            {
                WriteLine("");
                GeneratePolymorphicFromMethod(dto);
                WriteLine("");
                GeneratePolymorphicProjectionProperty(dto);
            }
            else if (!isBase && dto.SourceTypeName is not null && dto.ForwardMappings is not null)
            {
                WriteLine("");
                GenerateFromMethod(dto);
                WriteLine("");
                GenerateProjectionProperty(dto);
            }
        }

        // Reverse mapping: To
        if (dto.Directions.HasFlag(MapDirection.ToEntity))
        {
            if (dto.ReconstructionArguments is not null)
            {
                WriteLine("");
                GenerateToMethod(dto);
            }
        }

        if (dto.NestedDtos.Count > 0)
        {
            WriteLine("");
            foreach (var nested in dto.NestedDtos)
            {
                GenerateDto(nested);
                WriteLine("");
            }
        }

        PopIndent();
        WriteLine("}");
    }

    private void GeneratePolymorphicFromMethod(DtoData dto)
    {
        WriteLine($"public static {dto.DtoName} {FromName(dto)}({dto.SourceTypeName} source) =>");
        PushIndent();
        WriteLine("source switch");
        WriteLine("{");
        PushIndent();

        foreach (var dt in dto.DerivedTypes)
        {
            var sourceName = dt.SourceTypeName ?? dt.Discriminator;
            WriteLine($"{sourceName} p => {dt.DtoName}.FromEntity(p),");
        }

        WriteLine(
            $$"""_ => throw new global::System.ArgumentOutOfRangeException(nameof(source), source, $"Unknown derived type '{source.GetType()}'.")""");
        PopIndent();
        WriteLine("};");
        PopIndent();
        WriteLine("");
        WriteLine("public static " + dto.DtoName + "? " + FromName(dto) + "OrDefault(" + dto.SourceTypeName + "? source) =>");
        PushIndent();
        WriteLine($"source is null ? null : {FromName(dto)}(source);");
        PopIndent();
    }

    private void GeneratePolymorphicProjectionProperty(DtoData dto)
    {
        WriteLine(
            $"public static global::System.Linq.Expressions.Expression<global::System.Func<{dto.SourceTypeName}, {dto.DtoName}>> Projection =>");
        PushIndent();
        WriteLine("source =>");
        PushIndent();

        for (var i = 0; i < dto.DerivedTypes.Count; i++)
        {
            var dt = dto.DerivedTypes[i];
            var sourceName = dt.SourceTypeName ?? dt.Discriminator;
            var castSource = $"(({sourceName})source)";
            var nestedDto = dto.NestedDtos.FirstOrDefault(n => n.DtoName == dt.DtoName);
            var mappings = dt.ForwardMappings ?? nestedDto.ForwardMappings;

            Write($"source is {sourceName} ? ({dto.DtoName})new {dt.DtoName}");
            if (mappings is { Count: > 0 } validMappings)
            {
                WriteLine("");
                WriteLine("{");
                PushIndent();
                foreach (var mapping in validMappings)
                {
                    var projExpr =
                        System.Text.RegularExpressions.Regex.Replace(mapping.ProjectionExpression, @"\bsource\b",
                            castSource);
                    WriteLine($"{mapping.DtoPropertyName} = {projExpr},");
                }

                PopIndent();
                Write("} : ");
            }
            else
            {
                Write("() : ");
            }
        }

        WriteLine("null!;");
        PopIndent();
        PopIndent();
    }

    private void GenerateFromMethod(DtoData dto)
    {
        WriteLine($"public static {dto.DtoName} {FromName(dto)}({dto.SourceTypeName} source) =>");
        PushIndent();
        WriteLine("new()");
        WriteLine("{");
        PushIndent();

        foreach (var mapping in dto.ForwardMappings!.Value)
        {
            WriteLine($"{mapping.DtoPropertyName} = {mapping.AdaptExpression},");
        }

        PopIndent();
        WriteLine("};");
        PopIndent();
        WriteLine("");
        WriteLine($"public static {dto.DtoName}? {FromName(dto)}OrDefault({dto.SourceTypeName}? source) =>");
        PushIndent();
        var adaptArg = dto.IsSourceValueType ? "source.Value" : "source";
        WriteLine($"source is null ? null : {FromName(dto)}({adaptArg});");
        PopIndent();
    }

    private void GenerateProjectionProperty(DtoData dto)
    {
        var newKeyword = !string.IsNullOrWhiteSpace(dto.BaseDtoName) ? "new " : "";
        WriteLine(
            $"public static {newKeyword}global::System.Linq.Expressions.Expression<global::System.Func<{dto.SourceTypeName}, {dto.DtoName}>> Projection =>");
        PushIndent();
        WriteLine($"source => new {dto.DtoName}");
        WriteLine("{");
        PushIndent();

        foreach (var mapping in dto.ForwardMappings!.Value)
        {
            WriteLine($"{mapping.DtoPropertyName} = {mapping.ProjectionExpression},");
        }

        PopIndent();
        WriteLine("};");
        PopIndent();
    }

    private void GenerateToMethod(DtoData dto)
    {
        WriteLine($"public {dto.SourceTypeName} {ToName(dto)}() =>");
        PushIndent();
        WriteLine($"{dto.SourceTypeName}.{dto.FactoryMethodName}(");
        PushIndent();

        var arguments = dto.ReconstructionArguments!.Value;
        for (var i = 0; i < arguments.Count; i++)
        {
            var argument = arguments[i];
            var suffix = i < arguments.Count - 1 ? "," : "";

            if (argument.Kind != ReconstructKind.FlattenedValueObject)
            {
                WriteLine($"{argument.FactoryParameterName}: {BuildArgumentExpression(argument)}{suffix}");
                continue;
            }

            WriteLine($"{argument.FactoryParameterName}: {argument.TargetTypeName}.Create(");
            PushIndent();
            WriteArgumentLines(argument.FlattenedArguments!.Value,
                a => $"{a.SubFactoryParameterName}: this.{a.DtoPropertyName}");
            PopIndent();
            WriteLine($"){suffix}");
        }

        PopIndent();
        WriteLine(");");
        PopIndent();
    }

    private static string FromName(DtoData dto) => dto.IsSourceValueObject ? "FromValueObject" : "FromEntity";

    private static string ToName(DtoData dto) => dto.IsSourceValueObject ? "ToValueObject" : "ToEntity";

    private static string BuildArgumentExpression(FactoryArgument argument)
    {
        return argument.Kind switch
        {
            ReconstructKind.Direct => BuildDirectExpression(argument),
            ReconstructKind.ValueObject => BuildWrappedExpression(argument,
                value => $"{argument.TargetTypeName}.Create({value})"),
            ReconstructKind.NestedType => BuildWrappedExpression(argument,
                value => $"{value}.{(argument.IsNestedValueObject ? "ToValueObject" : "ToEntity")}()"),
            ReconstructKind.Locale => argument.TargetTypeName == "ToString"
                ? $"this.{argument.DtoPropertyName}.ToString()"
                : $"this.{argument.DtoPropertyName}",
            _ => $"this.{argument.DtoPropertyName}"
        };
    }

    private static string BuildDirectExpression(FactoryArgument argument)
    {
        var access = $"this.{argument.DtoPropertyName}";
        return argument.IsCollection
            ? ApplyCollectionConversion(access, argument.CollectionConversionKind)
            : access;
    }


    private static string BuildWrappedExpression(FactoryArgument argument, Func<string, string> wrap)
    {
        var access = $"this.{argument.DtoPropertyName}";

        if (argument.IsCollection)
        {
            var selectExpr = ApplyCollectionConversion(
                $"{LinqNamespace}.Enumerable.Select({access}, x => {wrap("x")})",
                argument.CollectionConversionKind);
            return argument.IsNullable ? $"{access} is null ? null : {selectExpr}" : selectExpr;
        }

        return argument.IsNullable ? $"{access} is null ? null : {wrap(access)}" : wrap(access);
    }

    private static string ApplyCollectionConversion(string expression, string conversionKind) =>
        string.IsNullOrEmpty(conversionKind)
            ? expression
            : $"{LinqNamespace}.Enumerable.{conversionKind}({expression})";

    private static string ToPascalCase(string input)
    {
        if (string.IsNullOrEmpty(input)) return input;
        return char.ToUpperInvariant(input[0]) + input.Substring(1);
    }

    private static string ToSnakeCase(string input)
    {
        if (string.IsNullOrEmpty(input)) return input;
        return char.ToLowerInvariant(input[0]) + input.Substring(1);
    }
}