using Majal.Common.Abstractions;
using static Majal.Common.Abstractions.Constants;
using static Majal.EntityFrameworkCore.Common.EfCoreConstants;

namespace Majal.Generators.Ordinals;

public class OrdinalEfCoreTemplate(OrdinalBatchOptions options) : BaseTemplate
{
    public override string TransformText()
    {
        Clear();
        WriteLine("// <auto-generated />");
        WriteLine("");
        WriteLine("namespace Majal;");
        WriteLine("");
        WriteLine("#nullable enable");
        WriteLine("");
        WriteLine("/// <summary>Provides EF Core extension methods for persisting <see cref=\"IOrdinal\"/> orderings.</summary>");
        WriteLine("public static class OrdinalEfCoreExtensions");
        WriteLine("{");
        PushIndent();

        WriteLine("/// <summary>The idsInOrder count above which ReorderAsync splits its work into batches.</summary>");
        WriteLine($"private const int ReorderBatchThreshold = {options.BatchThreshold};");
        WriteLine("");
        WriteLine("/// <summary>The number of ids updated per batch once ReorderBatchThreshold is exceeded.</summary>");
        WriteLine($"private const int ReorderBatchSize = {options.BatchSize};");
        WriteLine("");

        WriteLine("/// <summary>");
        WriteLine("/// Persists an ordinal ordering for entities matching the supplied ids, using one or more");
        WriteLine("/// set-based EF Core bulk updates issued via <c>ExecuteUpdateAsync</c>. No entities are loaded");
        WriteLine("/// into memory or attached to the change tracker.");
        WriteLine("/// </summary>");
        WriteLine("/// <remarks>");
        WriteLine("/// When <paramref name=\"idsInOrder\"/> has more entries than the configured batch threshold,");
        WriteLine("/// the update is split into fixed-size batches, each issued as its own <c>UPDATE</c> statement,");
        WriteLine("/// to keep the generated SQL CASE expression and IN list bounded. Regardless of batching, the");
        WriteLine("/// ordinal persisted for each entity is always its absolute (zero-based) position within");
        WriteLine("/// <paramref name=\"idsInOrder\"/>.");
        WriteLine("/// </remarks>");
        WriteLine("/// <exception cref=\"global::System.ArgumentNullException\">");
        WriteLine("/// <paramref name=\"source\"/> or <paramref name=\"idsInOrder\"/> is <see langword=\"null\"/>.");
        WriteLine("/// </exception>");
        WriteLine("/// <exception cref=\"global::System.ArgumentException\">");
        WriteLine("/// <paramref name=\"idsInOrder\"/> contains a <see langword=\"null\"/> id (when <typeparamref name=\"TId\"/>");
        WriteLine("/// is a reference type) or contains duplicate ids.");
        WriteLine("/// </exception>");
        WriteLine($"public static async {TasksNamespace}.Task ReorderAsync<TEntity, TId>(");
        WriteLine($"    this {LinqNamespace}.IQueryable<TEntity> source,");
        WriteLine($"    {GenericsNamespace}.IReadOnlyList<TId> idsInOrder,");
        WriteLine($"    {ThreadingNamespace}.CancellationToken cancellationToken = default)");
        WriteLine($"    where TEntity : class, {MajalNamespace}.IOrdinal, {MajalNamespace}.IEntity<TId>");
        WriteLine("{");
        PushIndent();
        WriteLine($"if (source is null) throw new {SystemNamespace}.ArgumentNullException(nameof(source));");
        WriteLine($"if (idsInOrder is null) throw new {SystemNamespace}.ArgumentNullException(nameof(idsInOrder));");
        WriteLine("if (idsInOrder.Count == 0) return;");
        WriteLine("");

        WriteLine("// Single pass: reject null ids (only reachable when TId is a reference type) and duplicates.");
        WriteLine($"var seenIds = new {GenericsNamespace}.HashSet<TId>();");
        WriteLine("for (var i = 0; i < idsInOrder.Count; i++)");
        WriteLine("{");
        PushIndent();
        WriteLine("var id = idsInOrder[i];");
        WriteLine($"if (id is null) throw new {SystemNamespace}.ArgumentException(\"idsInOrder must not contain null ids.\", nameof(idsInOrder));");
        WriteLine($"if (!seenIds.Add(id)) throw new {SystemNamespace}.ArgumentException(\"idsInOrder must not contain duplicate ids.\", nameof(idsInOrder));");
        PopIndent();
        WriteLine("}");
        WriteLine("");

        WriteLine("var batchSize = idsInOrder.Count > ReorderBatchThreshold ? ReorderBatchSize : idsInOrder.Count;");
        WriteLine("for (var batchStart = 0; batchStart < idsInOrder.Count; batchStart += batchSize)");
        WriteLine("{");
        PushIndent();
        WriteLine($"var batchCount = {SystemNamespace}.Math.Min(batchSize, idsInOrder.Count - batchStart);");
        WriteLine("var batchIds = new TId[batchCount];");
        WriteLine("for (var i = 0; i < batchCount; i++)");
        WriteLine("{");
        PushIndent();
        WriteLine("batchIds[i] = idsInOrder[batchStart + i];");
        PopIndent();
        WriteLine("}");
        WriteLine("");
        WriteLine("var ordinalSelector = BuildOrdinalMappingExpression<TEntity, TId>(batchIds, batchStart);");
        WriteLine("");
        WriteLine($"await {EfCoreNamespace}.EntityFrameworkQueryableExtensions.ExecuteUpdateAsync(");
        PushIndent();
        WriteLine($"{LinqNamespace}.Queryable.Where(source, e => batchIds.Contains(e.Id)),");
        WriteLine("setters => setters.SetProperty(e => e.Ordinal, ordinalSelector),");
        WriteLine("cancellationToken);");
        PopIndent();
        PopIndent();
        WriteLine("}");
        PopIndent();
        WriteLine("}");
        WriteLine("");

        WriteLine("/// <summary>");
        WriteLine("/// Builds a lambda mapping each entity's id to its absolute ordinal within the original");
        WriteLine("/// idsInOrder list, using only the ids in the current batch for equality comparisons.");
        WriteLine("/// </summary>");
        WriteLine($"private static {ExpressionsType}<{SystemNamespace}.Func<TEntity, {UIntType}>> BuildOrdinalMappingExpression<TEntity, TId>(");
        WriteLine($"    {GenericsNamespace}.IReadOnlyList<TId> batchIds, int batchStart)");
        WriteLine($"    where TEntity : {MajalNamespace}.IEntity<TId>");
        WriteLine("{");
        PushIndent();
        WriteLine($"var parameter = {ExpressionsType}.Parameter(typeof(TEntity), \"e\");");
        WriteLine($"var idAccess = {ExpressionsType}.Property(parameter, nameof({MajalNamespace}.IEntity<TId>.Id));");
        WriteLine("");
        WriteLine("// Nested Expression.Condition (rather than Expression.Switch) is used because EF Core's SQL");
        WriteLine("// translation of Expression.Switch inside SetProperty is not verified across providers;");
        WriteLine("// batching already bounds the nesting depth of each generated CASE expression.");
        WriteLine($"{ExpressionsType} body = {ExpressionsType}.Constant((uint)(batchStart + batchIds.Count - 1));");
        WriteLine("");
        WriteLine("for (var i = batchIds.Count - 2; i >= 0; i--)");
        WriteLine("{");
        PushIndent();
        WriteLine("var absoluteOrdinal = batchStart + i;");
        WriteLine($"var isMatch = {ExpressionsType}.Equal(");
        WriteLine($"    idAccess, {ExpressionsType}.Constant(batchIds[i], typeof(TId)));");
        WriteLine($"body = {ExpressionsType}.Condition(");
        WriteLine($"    isMatch, {ExpressionsType}.Constant((uint)absoluteOrdinal), body);");
        PopIndent();
        WriteLine("}");
        WriteLine("");
        WriteLine($"return {ExpressionsType}.Lambda<{SystemNamespace}.Func<TEntity, {UIntType}>>(body, parameter);");
        PopIndent();
        WriteLine("}");
        PopIndent();
        WriteLine("}");

        return ToString();
    }
}
