using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Majal;

/// <summary>
/// Generates a partial class for every class marked with [Entity].
/// The generated class implements IEntity and adds domain-event plumbing.
/// </summary>
[Generator]
public sealed class AggregateRootGenerator : IIncrementalGenerator
{
    // Constants for source generation
    private const string AggregateRootFilenameSuffix = ".AggregateRoot.g.cs";
    private const string AggregateRootMarkerFilename = "IAggregateRoot.g.cs";
    private const string AttributeFilename = "AggregateRootAttribute.g.cs";
    private const string EntityAttributeName = "EntityAttribute";
    private const string AggregateRootAttributeName = "AggregateRootAttribute";
    private const string AutoGeneratedHeader = "// <auto-generated />";
    private const string NullableEnable = "#nullable enable";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        RegisterPredefinedTypes(context);
        RegisterEntityGenerators(context);
    }

    /// <summary>
    /// Registers the predefined types (IEntity, IEvent, EntityAttribute) that will be available to all generated code.
    /// </summary>
    private static void RegisterPredefinedTypes(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
        {
            ctx.AddSource(AttributeFilename, SourceText.From(GenerateAttributesType(), Encoding.UTF8));
            ctx.AddSource(AggregateRootMarkerFilename, SourceText.From(GenerateEntityMarkerType(), Encoding.UTF8));
        });
    }


    /// <summary>
    /// Registers the entity generator pipeline that processes classes marked with [Entity].
    /// </summary>
    private static void RegisterEntityGenerators(IncrementalGeneratorInitializationContext context)
    {
        // Get classes with attributes
        var classesWithAttributes = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax { AttributeLists.Count: > 0 },
                transform: static (ctx, _) =>
                    ctx.SemanticModel.GetDeclaredSymbol((ClassDeclarationSyntax)ctx.Node) as INamedTypeSymbol)
            .Where(static symbol => symbol is not null);

        // Filter to classes that carry the [Entity] attribute
        var entities = classesWithAttributes
            .Where(s => HasEntityAttribute(s) && HasAggregateRootAttribute(s))
            .Select((classSymbol, _) => classSymbol!);

        // Generate source for each entity
        context.RegisterSourceOutput(entities, (spc, classSymbol) =>
        {
            var source = GeneratePartialClass(classSymbol);
            spc.AddSource($"{classSymbol.Name}{AggregateRootFilenameSuffix}", SourceText.From(source, Encoding.UTF8));
        });
    }

    /// <summary>
    /// Determines if a class has the EntityAttribute generic attribute.
    /// </summary>
    private static bool HasEntityAttribute(INamedTypeSymbol? classSymbol)
    {
        if (classSymbol == null) return false;
        return classSymbol
            .GetAttributes()
            .Any(a => a.AttributeClass is { Name: EntityAttributeName, IsGenericType: true, TypeArguments.Length: 1 });
    }

    /// <summary>
    /// Determines if a class has the EntityAttribute generic attribute.
    /// </summary>
    private static bool HasAggregateRootAttribute(INamedTypeSymbol? classSymbol)
    {
        if (classSymbol == null) return false;
        return classSymbol
            .GetAttributes()
            .Any(a => a.AttributeClass is
                { Name: AggregateRootAttributeName, IsGenericType: true, TypeArguments.Length: 1 });
    }

    /// <summary>
    /// Generates the partial class that implements IAggregateRoot of TDomainEvent and domain-event helpers.
    /// </summary>
    private static string GeneratePartialClass(INamedTypeSymbol classSymbol)
    {
        var genericEventType = GetGenericType(classSymbol);
        var typeName = GetFullTypeName(classSymbol);
        var namespaceName = GetNamespaceDeclaration(classSymbol);

        var sb = new StringBuilder();
        AppendCodeHeader(sb, namespaceName);
        AppendClassDeclaration(sb, typeName, genericEventType);

        sb.AppendLine("{");
        GenerateProperties(sb, genericEventType);
        GenerateMethods(sb, genericEventType);
        sb.AppendLine("}");
        sb.AppendLine();

        return sb.ToString();
    }

    /// <summary>
    /// Gets the full type name including generic parameters if present.
    /// </summary>
    private static string GetFullTypeName(INamedTypeSymbol classSymbol)
    {
        var typeName = classSymbol.Name;
        if (classSymbol.TypeParameters.Length > 0)
            typeName += $"<{string.Join(", ", classSymbol.TypeParameters.Select(t => t.Name))}>";

        return typeName;
    }

    /// <summary>
    /// Gets the namespace declaration formatted for the generated code.
    /// </summary>
    private static string GetNamespaceDeclaration(INamedTypeSymbol classSymbol)
    {
        return classSymbol.ContainingNamespace.IsGlobalNamespace
            ? string.Empty
            : $"namespace {classSymbol.ContainingNamespace.ToDisplayString()};";
    }

    /// <summary>
    /// Appends the standard code header with usings and namespace.
    /// </summary>
    private static void AppendCodeHeader(StringBuilder sb, string namespaceName)
    {
        sb.AppendLine(AutoGeneratedHeader);
        sb.AppendLine();
        sb.AppendLine(namespaceName);
        sb.AppendLine();
        sb.AppendLine(NullableEnable);
        sb.AppendLine();
    }

    /// <summary>
    /// Appends the class definition line with appropriate interfaces.
    /// </summary>
    private static void AppendClassDeclaration(StringBuilder sb, string typeName, string domainEventType)
    {
        List<string> interfaces = [$"global::Majal.IAggregateRoot<{domainEventType}>"];
        sb.AppendLine($"public partial class {typeName} : {string.Join(", ", interfaces)}");
    }

    /// <summary>
    /// Parses the AggregateRootAttribute to extract the generic type.
    /// </summary>
    private static string GetGenericType(INamedTypeSymbol classSymbol)
    {
        var aggregateRootAttribute = classSymbol.GetAttributes()
            .FirstOrDefault(a => a.AttributeClass?.Name == AggregateRootAttributeName);

        if (aggregateRootAttribute == null) return "global::System.Object";

        return aggregateRootAttribute.AttributeClass?.TypeArguments.Length > 0
            ? aggregateRootAttribute.AttributeClass.TypeArguments[0].ToDisplayString()
            : "global::System.Object"; // default fallback
    }

    /// <summary>
    /// Generates the properties for the aggregate root.
    /// </summary>
    private static void GenerateProperties(StringBuilder sb, string domainEventType)
    {
        AppendAggregateProperties(sb, domainEventType);
    }


    /// <summary>
    /// Appends aggregate root properties (Events collection).
    /// </summary>
    private static void AppendAggregateProperties(StringBuilder sb, string genericEventType)
    {
        sb.AppendLine();
        sb.AppendLine(
            $"    private readonly global::System.Collections.Generic.List<{genericEventType}> _events = [];");
        sb.AppendLine("    /// <inheritdoc />");
        sb.AppendLine(
            $"    public global::System.Collections.Generic.IEnumerable<{genericEventType}> Events => _events;");
        sb.AppendLine();
    }

    /// <summary>
    /// Generates the methods for the entity.
    /// </summary>
    private static void GenerateMethods(StringBuilder sb, string genericEventType)
    {
        AppendPublishMethod(sb, genericEventType);
        AppendClearMethod(sb);
    }

    /// <summary>
    /// Appends the Publish method for aggregate roots.
    /// </summary>
    private static void AppendPublishMethod(StringBuilder sb, string genericEventType)
    {
        sb.AppendLine();
        sb.AppendLine("    /// <inheritdoc />");
        sb.AppendLine($"    public void Publish({genericEventType} @event)");
        sb.AppendLine("    {");
        sb.AppendLine("        _events.Add(@event);");
        sb.AppendLine("    }");
    }


    /// <summary>
    /// Appends the Clear method for aggregate roots.
    /// </summary>
    private static void AppendClearMethod(StringBuilder sb)
    {
        sb.AppendLine();
        sb.AppendLine("    /// <inheritdoc />");
        sb.AppendLine("    public void Clear()");
        sb.AppendLine("    {");
        sb.AppendLine("        _events.Clear();");
        sb.AppendLine("    }");
    }

    /// <summary>
    /// Returns helper type definitions that are added during post-initialization.
    /// </summary>
    private static string GenerateEntityMarkerType()
    {
        // lang=c#
        return """
                namespace Majal
                {
                    /// <summary>
                    /// Marker interface for domain aggregates entities.
                    /// </summary>
                    public interface IAggregateRoot<TDomainEvent>
                    {
                        ///<summary>
                        /// Gets the list of events associated with the aggregate root.
                        ///</summary>
                        global::System.Collections.Generic.IEnumerable<TDomainEvent> Events { get; }
                        
                        ///<summary>
                        /// Publishes a domain event by adding it to the Events collection. 
                        /// This method is typically called within the aggregate root's methods to record significant state changes or actions that occur within the aggregate.
                        /// The published events can then be processed by event handlers or dispatched to other parts of the
                        /// system for further handling, such as updating read models, triggering side effects, or integrating with external systems.
                        ///</summary>
                        void Publish(TDomainEvent @event);

                        ///<summary>
                        /// Clears all domain events from the Events collection.
                        /// This method is typically called after the events have been successfully processed and persisted, 
                        /// to reset the state of the aggregate root's event collection and prepare it for recording new events.
                        /// </summary>
                        void Clear();
                    }
                }

               """;
    }


    /// <summary>
    /// Returns attribute type definitions that are added during post-initialization.
    /// </summary>
    private static string GenerateAttributesType()
    {
        // lang=c#
        return """
               namespace Majal
               {
                    /// <summary>
                    /// Apply to a class to indicate it is a DDD aggregate root type.
                    /// The generator will create a partial class with domain-event helpers.
                    /// </summary>
                    [global::System.AttributeUsage(global::System.AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
                    public sealed class AggregateRootAttribute<TDomainEvent> : global::System.Attribute
                    {
                    }
               }

               """;
    }
}