using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Majal;

/// <summary>
/// Generates a partial class for every class marked with [Entity].
/// The generated class implements IEntity and adds domain-event plumbing.
/// </summary>
[Generator]
public sealed class AggregateRootGenerator : IIncrementalGenerator
{
    // Constants for source generation
    private const string AggregateRootFilenameSuffix = ".AggregateRoot.g.cs";
    private const string AggregateRootMarkerFilename = "IAggregateRoot.g.cs";
    private const string EventFilename = "IEvent.g.cs";
    private const string AttributeFilename = "AggregateRootAttribute.g.cs";
    private const string EntityAttributeName = "EntityAttribute";
    private const string AggregateRootAttributeName = "AggregateRootAttribute";
    private const string AutoGeneratedHeader = "// <auto-generated />";
    private const string NullableEnable = "#nullable enable";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        RegisterPredefinedTypes(context);
        RegisterEntityGenerators(context);
    }

    /// <summary>
    /// Registers the predefined types (IEntity, IEvent, EntityAttribute) that will be available to all generated code.
    /// </summary>
    private static void RegisterPredefinedTypes(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
        {
            ctx.AddSource(EventFilename, SourceText.From(GenerateEventType(), Encoding.UTF8));
            ctx.AddSource(AttributeFilename, SourceText.From(GenerateAttributesType(), Encoding.UTF8));
            ctx.AddSource(AggregateRootMarkerFilename, SourceText.From(GenerateEntityMarkerType(), Encoding.UTF8));
        });
    }

    /// <summary>
    /// Registers the entity generator pipeline that processes classes marked with [Entity].
    /// </summary>
    private static void RegisterEntityGenerators(IncrementalGeneratorInitializationContext context)
    {
        // Get classes with attributes
        var classesWithAttributes = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax { AttributeLists.Count: > 0 },
                transform: static (ctx, _) =>
                    ctx.SemanticModel.GetDeclaredSymbol((ClassDeclarationSyntax)ctx.Node) as INamedTypeSymbol)
            .Where(static symbol => symbol is not null);

        // Filter to classes that carry the [Entity] attribute
        var entities = classesWithAttributes
            .Where(s => HasEntityAttribute(s) && HasAggregateRootAttribute(s))
            .Select((classSymbol, _) => classSymbol!);

        // Generate source for each entity
        context.RegisterSourceOutput(entities, (spc, classSymbol) =>
        {
            var source = GeneratePartialClass(classSymbol);
            spc.AddSource($"{classSymbol.Name}{AggregateRootFilenameSuffix}", SourceText.From(source, Encoding.UTF8));
        });
    }

    /// <summary>
    /// Determines if a class has the EntityAttribute generic attribute.
    /// </summary>
    private static bool HasEntityAttribute(INamedTypeSymbol? classSymbol)
    {
        if (classSymbol == null) return false;
        return classSymbol
            .GetAttributes()
            .Any(a => a.AttributeClass is
            { Name: EntityAttributeName, IsGenericType: true, TypeArguments.Length: 1 });
    }

    /// <summary>
    /// Determines if a class has the EntityAttribute generic attribute.
    /// </summary>
    private static bool HasAggregateRootAttribute(INamedTypeSymbol? classSymbol)
    {
        if (classSymbol == null) return false;
        return classSymbol
            .GetAttributes()
            .Any(a => a.AttributeClass is
            { Name: AggregateRootAttributeName, IsGenericType: false, TypeArguments.Length: 0 });
    }

    /// <summary>
    /// Generates the partial class that implements IEntity and domain-event helpers.
    /// </summary>
    private static string GeneratePartialClass(INamedTypeSymbol classSymbol)
    {
        var typeName = GetFullTypeName(classSymbol);
        var namespaceName = GetNamespaceDeclaration(classSymbol);

        var sb = new StringBuilder();
        AppendCodeHeader(sb, namespaceName);
        AppendClassDeclaration(sb, typeName);

        sb.AppendLine("{");
        GenerateProperties(sb);
        GenerateMethods(sb);
        sb.AppendLine("}");
        sb.AppendLine();

        return sb.ToString();
    }

    /// <summary>
    /// Gets the full type name including generic parameters if present.
    /// </summary>
    private static string GetFullTypeName(INamedTypeSymbol classSymbol)
    {
        var typeName = classSymbol.Name;
        if (classSymbol.TypeParameters.Length > 0)
        {
            typeName += $"<{string.Join(", ", classSymbol.TypeParameters.Select(t => t.Name))}>";
        }

        return typeName;
    }

    /// <summary>
    /// Gets the namespace declaration formatted for the generated code.
    /// </summary>
    private static string GetNamespaceDeclaration(INamedTypeSymbol classSymbol)
    {
        return classSymbol.ContainingNamespace.IsGlobalNamespace
            ? string.Empty
            : $"namespace {classSymbol.ContainingNamespace.ToDisplayString()};";
    }

    /// <summary>
    /// Appends the standard code header with usings and namespace.
    /// </summary>
    private static void AppendCodeHeader(StringBuilder sb, string namespaceName)
    {
        sb.AppendLine(AutoGeneratedHeader);
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine();
        sb.AppendLine(namespaceName);
        sb.AppendLine();
        sb.AppendLine(NullableEnable);
        sb.AppendLine();
    }

    /// <summary>
    /// Appends the class definition line with appropriate interfaces.
    /// </summary>
    private static void AppendClassDeclaration(StringBuilder sb, string typeName)
    {
        List<string> interfaces = ["IAggregateRoot"];
        sb.AppendLine($"public partial class {typeName} : {string.Join(", ", interfaces)}");
    }


    /// <summary>
    /// Generates the properties for the entity.
    /// </summary>
    private static void GenerateProperties(StringBuilder sb)
    {
        AppendAggregateProperties(sb);
    }


    /// <summary>
    /// Appends aggregate root properties (Events collection).
    /// </summary>
    private static void AppendAggregateProperties(StringBuilder sb)
    {
        sb.AppendLine();
        sb.AppendLine("    private readonly List<IEvent> _events = [];");
        sb.AppendLine("    /// <inheritdoc />");
        sb.AppendLine("    public IEnumerable<IEvent> Events => _events;");
        sb.AppendLine();
    }

    /// <summary>
    /// Generates the methods for the entity.
    /// </summary>
    private static void GenerateMethods(StringBuilder sb)
    {
        AppendPublishMethod(sb);
        AppendClearMethod(sb);
    }

    /// <summary>
    /// Appends the Publish method for aggregate roots.
    /// </summary>
    private static void AppendPublishMethod(StringBuilder sb)
    {
        sb.AppendLine();
        sb.AppendLine("    /// <inheritdoc />");
        sb.AppendLine("    public void Publish(IEvent @event)");
        sb.AppendLine("    {");
        sb.AppendLine("        _events.Add(@event);");
        sb.AppendLine("    }");
    }


    /// <summary>
    /// Appends the Clear method for aggregate roots.
    /// </summary>
    private static void AppendClearMethod(StringBuilder sb)
    {
        sb.AppendLine();
        sb.AppendLine("    /// <inheritdoc />");
        sb.AppendLine("    public void Clear()");
        sb.AppendLine("    {");
        sb.AppendLine("        _events.Clear();");
        sb.AppendLine("    }");
    }

    /// <summary>
    /// Returns helper type definitions that are added during post-initialization.
    /// </summary>
    private static string GenerateEntityMarkerType()
    {
        // lang=c#
        return """
                using System;
                using System.Collections.Generic;

                namespace Majal
                {
                    /// <summary>
                    /// Marker interface for domain aggregates entities.
                    /// </summary>
                    public interface IAggregateRoot
                    {
                        ///<summary>
                        /// Gets the list of events associated with the aggregate root.
                        ///</summary>
                        IEnumerable<IEvent> Events { get; }
                        
                        ///<summary>
                        /// Publishes a domain event by adding it to the Events collection. 
                        /// This method is typically called within the aggregate root's methods to record significant state changes or actions that occur within the aggregate.
                        /// The published events can then be processed by event handlers or dispatched to other parts of the
                        /// system for further handling, such as updating read models, triggering side effects, or integrating with external systems.
                        ///</summary>
                        void Publish(IEvent @event);

                        ///<summary>
                        /// Clears all domain events from the Events collection.
                        /// This method is typically called after the events have been successfully processed and persisted, 
                        /// to reset the state of the aggregate root's event collection and prepare it for recording new events.
                        /// </summary>
                        void Clear();
                    }
                }

               """;
    }


    /// <summary>
    /// Returns domain event type definitions that are added during post-initialization.
    /// </summary>
    private static string GenerateEventType()
    {
        // lang=c#
        return """
                namespace Majal
                {
                    /// <summary>
                    /// Marker interface for domain events.
                    /// </summary>
                    public interface IEvent { }
                    
                }

               """;
    }

    /// <summary>
    /// Returns attribute type definitions that are added during post-initialization.
    /// </summary>
    private static string GenerateAttributesType()
    {
        // lang=c#
        return """

               using System;

               namespace Majal
               {

                   /// <summary>
                   /// Apply to a class to indicate it is a DDD aggregate root type.
                   /// The generator will create a partial class with domain-event helpers.
                   /// </summary>
                   [AttributeUsage(AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
                   public sealed class AggregateRootAttribute : Attribute
                   {
                   }
               }

               """;
    }
}