using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Majal;

/// <summary>
/// Generates a partial class for every class marked with [Entity].
/// The generated class implements IEntity and adds domain-event plumbing.
/// </summary>
[Generator]
public sealed class EntityGenerator : IIncrementalGenerator
{
    // Constants for source generation
    private const string EntityFilenameSuffix = ".Entity.g.cs";
    private const string EntityMarkerFilename = "IEntity.g.cs";
    private const string AttributeFilename = "EntityAttribute.g.cs";
    private const string EntityAttributeName = "EntityAttribute";
    private const string AutoGeneratedHeader = "// <auto-generated />";
    private const string NullableEnable = "#nullable enable";

    [Flags]
    private enum EntityOptions
    {
        Default = 0,
        Ordinal = 1 << 0,
        Auditable = 1 << 1,
        Archivable = 1 << 2,
        All = Auditable | Archivable | Ordinal
    }

    /// <summary>
    /// Represents the configuration extracted from the EntityAttribute.
    /// </summary>
    private record struct EntityConfiguration(string IdType, EntityOptions Options)
    {
        public static readonly EntityConfiguration Default = new("int", EntityOptions.Default);
    }

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        RegisterPredefinedTypes(context);
        RegisterEntityGenerators(context);
    }

    /// <summary>
    /// Registers the predefined types (IEntity, IEvent, EntityAttribute) that will be available to all generated code.
    /// </summary>
    private static void RegisterPredefinedTypes(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
        {
            ctx.AddSource(AttributeFilename, SourceText.From(GenerateAttributesType(), Encoding.UTF8));
            ctx.AddSource(EntityMarkerFilename, SourceText.From(GenerateEntityMarkerType(), Encoding.UTF8));
        });
    }

    /// <summary>
    /// Registers the entity generator pipeline that processes classes marked with [Entity].
    /// </summary>
    private static void RegisterEntityGenerators(IncrementalGeneratorInitializationContext context)
    {
        // Get classes with attributes
        var classesWithAttributes = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax { AttributeLists.Count: > 0 },
                transform: static (ctx, _) =>
                    ctx.SemanticModel.GetDeclaredSymbol((ClassDeclarationSyntax)ctx.Node) as INamedTypeSymbol)
            .Where(static symbol => symbol is not null);

        // Filter to classes that carry the [Entity] attribute
        var entities = classesWithAttributes
            .Where(HasEntityAttribute)
            .Select((classSymbol, _) => classSymbol!);

        // Generate source for each entity
        context.RegisterSourceOutput(entities, (spc, classSymbol) =>
        {
            var source = GeneratePartialClass(classSymbol);
            spc.AddSource($"{classSymbol.Name}{EntityFilenameSuffix}", SourceText.From(source, Encoding.UTF8));
        });
    }

    /// <summary>
    /// Determines if a class has the EntityAttribute generic attribute.
    /// </summary>
    private static bool HasEntityAttribute(INamedTypeSymbol? classSymbol)
    {
        if (classSymbol == null) return false;
        return classSymbol
            .GetAttributes()
            .Any(a => a.AttributeClass is { Name: EntityAttributeName, IsGenericType: true, TypeArguments.Length: 1 });
    }

    /// <summary>
    /// Generates the partial class that implements IEntity and domain-event helpers.
    /// </summary>
    private static string GeneratePartialClass(INamedTypeSymbol classSymbol)
    {
        var config = ParseEntityConfiguration(classSymbol);
        var typeName = GetFullTypeName(classSymbol);
        var namespaceName = GetNamespaceDeclaration(classSymbol);

        var sb = new StringBuilder();
        AppendCodeHeader(sb, namespaceName);
        AppendClassDeclaration(sb, typeName, config);

        sb.AppendLine("{");
        GenerateProperties(sb, classSymbol, config);
        GenerateMethods(sb, typeName, config);
        sb.AppendLine("}");
        sb.AppendLine();

        return sb.ToString();
    }

    /// <summary>
    /// Gets the full type name including generic parameters if present.
    /// </summary>
    private static string GetFullTypeName(INamedTypeSymbol classSymbol)
    {
        var typeName = classSymbol.Name;
        if (classSymbol.TypeParameters.Length > 0)
        {
            typeName += $"<{string.Join(", ", classSymbol.TypeParameters.Select(t => t.Name))}>";
        }

        return typeName;
    }

    /// <summary>
    /// Gets the namespace declaration formatted for the generated code.
    /// </summary>
    private static string GetNamespaceDeclaration(INamedTypeSymbol classSymbol)
    {
        return classSymbol.ContainingNamespace.IsGlobalNamespace
            ? string.Empty
            : $"namespace {classSymbol.ContainingNamespace.ToDisplayString()};";
    }

    /// <summary>
    /// Appends the standard code header with usings and namespace.
    /// </summary>
    private static void AppendCodeHeader(StringBuilder sb, string namespaceName)
    {
        sb.AppendLine(AutoGeneratedHeader);
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine();
        sb.AppendLine(namespaceName);
        sb.AppendLine();
        sb.AppendLine(NullableEnable);
        sb.AppendLine();
    }

    /// <summary>
    /// Appends the class definition line with appropriate interfaces.
    /// </summary>
    private static void AppendClassDeclaration(StringBuilder sb, string typeName, EntityConfiguration config)
    {
        var interfaces = new List<string> { $"IEntity<{config.IdType}>" };

        if (config.Options.HasFlag(EntityOptions.Archivable))
            interfaces.Add("IArchivableEntity");

        if (config.Options.HasFlag(EntityOptions.Auditable))
            interfaces.Add("IAuditableEntity");

        if (config.Options.HasFlag(EntityOptions.Ordinal))
            interfaces.Add("IOrdinalEntity");

        interfaces.Add("IComparable");
        interfaces.Add($"IComparable<{typeName}>");

        sb.AppendLine($"public partial class {typeName} : {string.Join(", ", interfaces)}");
    }

    /// <summary>
    /// Parses the EntityAttribute to extract the full configuration.
    /// </summary>
    private static EntityConfiguration ParseEntityConfiguration(INamedTypeSymbol classSymbol)
    {
        var entityAttribute = classSymbol.GetAttributes()
            .FirstOrDefault(a => a.AttributeClass?.Name == EntityAttributeName);

        if (entityAttribute == null) return EntityConfiguration.Default;

        var idType = ExtractIdTypeFromAttribute(entityAttribute);

        var options = EntityOptions.Default;

        // Parse the options from constructor arguments
        if (entityAttribute.ConstructorArguments.Length > 0 &&
            entityAttribute.ConstructorArguments[0].Value is int entityOptions)
        {
            options = (EntityOptions)entityOptions;
        }

        return new EntityConfiguration(idType, options);
    }

    /// <summary>
    /// Extracts the Id type from the generic EntityAttribute.
    /// </summary>
    private static string ExtractIdTypeFromAttribute(AttributeData entityAttribute)
    {
        return entityAttribute.AttributeClass?.TypeArguments.Length > 0
            ? entityAttribute.AttributeClass.TypeArguments[0].ToDisplayString()
            : "int"; // default fallback
    }

    /// <summary>
    /// Generates the properties for the entity.
    /// </summary>
    private static void GenerateProperties(StringBuilder sb, INamedTypeSymbol classSymbol, EntityConfiguration config)
    {
        AppendIdProperty(sb, classSymbol, config);

        sb.AppendLine($"    // {config.Options}");

        if (config.Options.HasFlag(EntityOptions.Ordinal))
            AppendOrdinalProperty(sb, classSymbol);

        if (config.Options.HasFlag(EntityOptions.Auditable))
            AppendAuditableProperties(sb, classSymbol);

        if (config.Options.HasFlag(EntityOptions.Archivable))
            AppendArchivableProperties(sb, classSymbol);
    }

    /// <summary>
    /// Appends the Id property if not already defined in the class.
    /// </summary>
    private static void AppendIdProperty(StringBuilder sb, INamedTypeSymbol classSymbol, EntityConfiguration config)
    {
        if (classSymbol.GetMembers().Any(m => m.Name == "Id" && m.Kind == SymbolKind.Property)) return;
        sb.AppendLine("    /// <inheritdoc />");
        sb.AppendLine($"    public {config.IdType} Id {{ get; init; }}");
        sb.AppendLine();
    }


    /// <summary>
    /// Appends the Ordinal property if not already defined in the class.
    /// </summary>
    private static void AppendOrdinalProperty(StringBuilder sb, INamedTypeSymbol classSymbol)
    {
        if (classSymbol.GetMembers().Any(m => m.Name == "Ordinal" && m.Kind == SymbolKind.Property)) return;

        sb.AppendLine("    /// <inheritdoc />");
        sb.AppendLine("    public uint Ordinal { get; set; }");
        sb.AppendLine();
    }


    /// <summary>
    /// Appends auditable entity properties (CreatedOn, UpdatedOn).
    /// </summary>
    private static void AppendAuditableProperties(StringBuilder sb, INamedTypeSymbol classSymbol)
    {
        if (!classSymbol.GetMembers().Any(m => m.Name == "CreatedOn" && m.Kind == SymbolKind.Property))
        {
            sb.AppendLine("    /// <inheritdoc />");
            sb.AppendLine("    public DateTime CreatedOn { get; init; }");
        }

        sb.AppendLine();

        if (!classSymbol.GetMembers().Any(m => m.Name == "UpdatedOn" && m.Kind == SymbolKind.Property))
        {
            sb.AppendLine("    /// <inheritdoc />");
            sb.AppendLine("    public DateTime? UpdatedOn { get; set; }");
        }

        sb.AppendLine();
    }

    /// <summary>
    /// Appends archivable entity properties (IsArchived, ArchivedOn).
    /// </summary>
    private static void AppendArchivableProperties(StringBuilder sb, INamedTypeSymbol classSymbol)
    {
        if (!classSymbol.GetMembers().Any(m => m.Name == "IsArchived" && m.Kind == SymbolKind.Property))
        {
            sb.AppendLine("    /// <inheritdoc />");
            sb.AppendLine("    public bool IsArchived { get; set; }");
        }

        sb.AppendLine();

        if (!classSymbol.GetMembers().Any(m => m.Name == "ArchivedOn" && m.Kind == SymbolKind.Property))
        {
            sb.AppendLine("    /// <inheritdoc />");
            sb.AppendLine("    public DateTime? ArchivedOn { get; set; }");
        }

        sb.AppendLine();
    }


    /// <summary>
    /// Generates the methods for the entity.
    /// </summary>
    private static void GenerateMethods(StringBuilder sb, string typeName, EntityConfiguration config)
    {
        AppendEqualsMethod(sb, typeName);
        AppendIsTransientMethod(sb, config);
        AppendEqualityOperators(sb, typeName);
        AppendGetHashCodeMethod(sb);
        AppendCompareToMethods(sb, typeName);
    }

    /// <summary>
    /// Appends the Equals method override.
    /// </summary>
    private static void AppendEqualsMethod(StringBuilder sb, string typeName)
    {
        sb.AppendLine("    public override bool Equals(object? obj)");
        sb.AppendLine("    {");
        sb.AppendLine($"        if (obj is not {typeName} other) return false;");
        sb.AppendLine("        if (ReferenceEquals(this, other)) return true;");
        sb.AppendLine("        if (IsTransient() || other.IsTransient()) return false;");
        sb.AppendLine("        return base.Equals(obj);");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    /// <summary>
    /// Appends the IsTransient helper method.
    /// </summary>
    private static void AppendIsTransientMethod(StringBuilder sb, EntityConfiguration config)
    {
        sb.AppendLine("    private bool IsTransient()");
        sb.AppendLine("    {");
        sb.AppendLine($"        return Id.Equals(default({config.IdType}));");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    /// <summary>
    /// Appends the equality operators (== and !=).
    /// </summary>
    private static void AppendEqualityOperators(StringBuilder sb, string typeName)
    {
        sb.AppendLine($"    public static bool operator ==({typeName} a, {typeName} b)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (a is null && b is null) return true;");
        sb.AppendLine("        if (a is null || b is null) return false;");
        sb.AppendLine("        return a.Equals(b);");
        sb.AppendLine("    }");
        sb.AppendLine();

        sb.AppendLine($"    public static bool operator !=({typeName} a, {typeName} b)");
        sb.AppendLine("    {");
        sb.AppendLine("        return !(a == b);");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    /// <summary>
    /// Appends the GetHashCode method override.
    /// </summary>
    private static void AppendGetHashCodeMethod(StringBuilder sb)
    {
        sb.AppendLine("    public override int GetHashCode()");
        sb.AppendLine("    {");
        sb.AppendLine("        return (GetType().ToString() + Id).GetHashCode();");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    /// <summary>
    /// Appends the CompareTo method overloads (generic and non-generic).
    /// </summary>
    private static void AppendCompareToMethods(StringBuilder sb, string typeName)
    {
        sb.AppendLine($"    public int CompareTo({typeName}? other)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (other is null) return 1;");
        sb.AppendLine("        if (ReferenceEquals(this, other)) return 0;");
        sb.AppendLine("        return Id.CompareTo(other.Id);");
        sb.AppendLine("    }");
        sb.AppendLine();

        sb.AppendLine("    public int CompareTo(object? other)");
        sb.AppendLine("    {");
        sb.AppendLine($"        return CompareTo(other as {typeName});");
        sb.AppendLine("    }");
        sb.AppendLine();
    }


    /// <summary>
    /// Returns helper type definitions that are added during post-initialization.
    /// </summary>
    private static string GenerateEntityMarkerType()
    {
        // lang=c#
        return """
                using System;

                namespace Majal
                {
                    /// <summary>
                    /// Marker interface for domain entities.
                    /// </summary>
                    public interface IEntity<TId>
                    {
                        /// <summary>
                        /// The unique identifier for the entity. This property is typically set at creation and is immutable.
                        /// The type of the Id is determined by the generic parameter TId, allowing for flexibility in choosing different types of identifiers (e.g., int, Guid, string).
                        /// </summary>
                        public TId Id { get; init; }
                    }


                    /// <summary>
                    /// Marker interface for auditable domain entities.
                    /// </summary>
                    public interface IAuditableEntity 
                    {
                        /// <summary>
                        /// The date and time when the entity was created. This property is typically set once at creation and is immutable.
                        /// </summary>
                        public DateTime CreatedOn { get; init; }

                        /// <summary>
                        /// The date and time when the entity was last updated. This property is typically updated whenever the entity undergoes changes.
                        /// It is nullable to allow for entities that have not been updated since creation.
                        /// </summary>
                        public DateTime? UpdatedOn { get; set; }
                    }

                    /// <summary>
                    /// Marker interface for ordinal domain entities.
                    /// </summary>
                    public interface IOrdinalEntity 
                    {
                        /// <summary>
                        /// An optional property that can be used to define a custom ordering of entities. 
                        /// This is particularly useful in scenarios where entities need to be displayed or processed in a specific sequence.
                        /// The Ordinal property is typically a non-negative integer that indicates the position of the entity in the desired order. 
                        /// It can be set and updated as needed to maintain the correct ordering of entities.
                        /// </summary>
                        public uint Ordinal { get; set; }
                    }

                    /// <summary>
                    /// Marker interface for archivable domain entities.
                    /// </summary>
                    public interface IArchivableEntity 
                    {
                        /// <summary>
                        /// Indicates whether the entity is archived. 
                        /// This property is typically used to soft-delete entities or to mark them as inactive without physically removing them from the database.
                        /// When IsArchived is true, the entity is considered archived and should be excluded from active
                        /// queries and operations, while still retaining its data for historical reference or potential restoration.
                        /// </summary>
                        public bool IsArchived { get; set; }

                        /// <summary>
                        /// The date and time when the entity was archived. 
                        /// This property is typically set when an entity is marked as archived and can be used for auditing purposes or to determine how long an entity has been archived.
                        /// It is nullable to allow for entities that have not been archived.
                        /// </summary>
                        public DateTime? ArchivedOn { get; set; }
                    }
                }

               """;
    }


    /// <summary>
    /// Returns attribute type definitions that are added during post-initialization.
    /// </summary>
    private static string GenerateAttributesType()
    {
        // lang=c#
        return """

               

               namespace Majal
               {
                   /// <summary>
                   /// Options for configuring the EntityAttribute.
                   /// </summary>
                   [global::System.Flags]
                   public enum EntityOptions
                   {
                        Default = 0,
                        /// <summary>
                        /// Indicates that the entity should have an Ordinal property for custom ordering.
                        /// </summary>
                        Ordinal = 1 << 0,
                        /// <summary>
                        /// Indicates that the entity should be auditable.
                        /// </summary>
                        Auditable = 1 << 1,
                        /// <summary>
                        /// Indicates that the entity should be archivable.
                        /// </summary>
                        Archivable = 1 << 2,
                        /// <summary>
                        /// Indicates that the entity should have all optional features (Ordinal, Auditable, Archivable).
                        /// </summary>
                        All = Auditable | Archivable | Ordinal
                   }

                   /// <summary>
                   /// Apply to a class to indicate it is a DDD entity with a specific Id type.
                   /// The generator will create a partial class with domain-event helpers.
                   /// </summary>
                   [AttributeUsage(AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
                   public sealed class EntityAttribute<TId> : global::System.Attribute
                   {
                        /// <summary>
                        /// The options for configuring the entity generation.
                        /// </summary>
                        public EntityOptions Options { get; }

                        public EntityAttribute()
                        {
                           Options = EntityOptions.Default;
                        }
                        
                        public EntityAttribute(EntityOptions options)
                        {
                            Options = options;
                        }
                        
                   }
               }

               """;
    }
}