using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Majal;

/// <summary>
/// Generates a partial class for every class marked with [ValueObject].
/// The generated class implements IValueObject and adds equality, comparison, and hashing logic.
/// </summary>
[Generator]
public sealed class ValueObjectGenerator : IIncrementalGenerator
{
    private const string ValueObjectFilename = "IValueObject.g.cs";
    private const string ValueObjectAttributeFilename = "ValueObjectAttribute.g.cs";
    private const string AttributeName = "ValueObjectAttribute";
    private const string AutoGeneratedHeader = "// <auto-generated />";
    private const string NullableEnable = "#nullable enable";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Register marker types and attributes that will be available to all generated code
        context.RegisterPostInitializationOutput(ctx =>
        {
            ctx.AddSource(ValueObjectFilename, SourceText.From(GenerateValueObjectMarkerType(), Encoding.UTF8));
            ctx.AddSource(ValueObjectAttributeFilename, SourceText.From(GenerateAttributesType(), Encoding.UTF8));
        });

        // Build a pipeline to find and process classes marked with [ValueObject] or [ValueObject<T>]
        var symbolicClassesWithAttributes = GetClassesWithAttributes(context);
        var nonGenericAttributeSymbol = GetAttributeSymbol(context, AttributeName);
        var genericAttributeSymbol = GetAttributeSymbol(context, $"{AttributeName}`1");

        var valueObjectClasses = symbolicClassesWithAttributes
            .Combine(nonGenericAttributeSymbol)
            .Combine(genericAttributeSymbol)
            .Where(HasValueObjectAttribute)
            .Select((pair, _) => pair.Left.Left!);

        // Generate source for each value object class
        context.RegisterSourceOutput(valueObjectClasses, (spc, classSymbol) =>
        {
            var source = GeneratePartialClass(classSymbol);
            spc.AddSource($"{classSymbol.Name}.ValueObject.g.cs", SourceText.From(source, Encoding.UTF8));
        });
    }

    /// <summary>
    /// Retrieves all classes that have attributes.
    /// </summary>
    private static IncrementalValuesProvider<INamedTypeSymbol?> GetClassesWithAttributes(
        IncrementalGeneratorInitializationContext context)
    {
        return context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax { AttributeLists.Count: > 0 },
                transform: static (ctx, _) => ctx.SemanticModel.GetDeclaredSymbol((ClassDeclarationSyntax)ctx.Node))
            .Where(static s => s is not null);
    }

    /// <summary>
    /// Retrieves the attribute symbol from the compilation.
    /// </summary>
    private static IncrementalValueProvider<INamedTypeSymbol?> GetAttributeSymbol(
        IncrementalGeneratorInitializationContext context, string fullyQualifiedName)
    {
        return context.CompilationProvider
            .Select((comp, _) => comp.GetTypeByMetadataName($"Majal.{fullyQualifiedName}"));
    }

    /// <summary>
    /// Determines if a class symbol has the ValueObject attribute applied.
    /// </summary>
    private static bool HasValueObjectAttribute(
        ((INamedTypeSymbol? classSymbol, INamedTypeSymbol? nonGenericAttr), INamedTypeSymbol? genericAttr) pair)
    {
        var classSymbol = pair.Item1.classSymbol;
        var nonGenericAttr = pair.Item1.nonGenericAttr;
        var genericAttr = pair.genericAttr;

        if (classSymbol == null) return false;

        return classSymbol.GetAttributes().Any(a =>
            (nonGenericAttr != null && SymbolEqualityComparer.Default.Equals(a.AttributeClass, nonGenericAttr)) ||
            (genericAttr != null &&
             SymbolEqualityComparer.Default.Equals(a.AttributeClass?.ConstructedFrom, genericAttr))
        );
    }

    /// <summary>
    /// Extracts the generic type argument from the ValueObjectAttribute&lt;TId&gt; attribute.
    /// Returns null if the attribute is non-generic.
    /// </summary>
    private static string? ExtractGenericArgumentType(INamedTypeSymbol classSymbol)
    {
        var entityAttribute = classSymbol.GetAttributes()
            .FirstOrDefault(a => a.AttributeClass?.Name == AttributeName);

        return entityAttribute is { AttributeClass.TypeArguments.Length: > 0 }
            ? entityAttribute.AttributeClass.TypeArguments[0].ToDisplayString()
            : null;
    }

    /// <summary>
    /// Gets the public readable and writable properties from the class symbol.
    /// </summary>
    private static List<IPropertySymbol> GetPublicReadableProperties(INamedTypeSymbol classSymbol)
    {
        return
        [
            .. classSymbol.GetMembers()
                .OfType<IPropertySymbol>()
                .Where(p => p.GetMethod?.DeclaredAccessibility is Accessibility.Public)
        ];
    }

    /// <summary>
    /// Gets the public writable properties from the class symbol.
    /// </summary>
    private static List<IPropertySymbol> GetPublicWritableProperties(INamedTypeSymbol classSymbol)
    {
        return
        [
            .. classSymbol.GetMembers()
                .OfType<IPropertySymbol>()
                .Where(p => p.SetMethod?.DeclaredAccessibility is Accessibility.Public)
        ];
    }

    /// <summary>
    /// Gets the formatted namespace declaration for the class.
    /// </summary>
    private static string GetNamespaceDeclaration(INamedTypeSymbol classSymbol)
    {
        return classSymbol.ContainingNamespace.IsGlobalNamespace
            ? string.Empty
            : $"namespace {classSymbol.ContainingNamespace.ToDisplayString()};";
    }

    /// <summary>
    /// Gets the full type name including generic parameters.
    /// </summary>
    private static string GetFullTypeName(INamedTypeSymbol classSymbol)
    {
        var typeName = classSymbol.Name;

        if (classSymbol.TypeParameters.Length > 0)
        {
            typeName += $"<{string.Join(", ", classSymbol.TypeParameters.Select(t => t.Name))}>";
        }

        return typeName;
    }

    /// <summary>
    /// Generates the common header for generated code files.
    /// </summary>
    private static void AppendCodeHeader(StringBuilder sb)
    {
        sb.AppendLine(AutoGeneratedHeader);
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine("using System.Text;");
        sb.AppendLine();
    }

    /// <summary>
    /// Generates the class declaration and opening brace.
    /// </summary>
    private static void AppendClassDeclaration(StringBuilder sb, string typeName)
    {
        sb.AppendLine(NullableEnable);
        sb.AppendLine();
        sb.AppendLine($"public partial class {typeName} : IValueObject, IComparable, IComparable<{typeName}>");
        sb.AppendLine("{");
        sb.AppendLine();
        sb.AppendLine("    private int? _cachedHashCode;");
        sb.AppendLine();
    }

    /// <summary>
    /// Appends the Value property for generic value objects.
    /// </summary>
    private static void AppendValueProperty(StringBuilder sb, string? genericArgumentType)
    {
        if (genericArgumentType is null) return;
        sb.AppendLine($"    public {genericArgumentType}? Value {{ get; }}");
        sb.AppendLine();
    }

    /// <summary>
    /// Appends the GetEqualityComponents method.
    /// </summary>
    private static void AppendGetEqualityComponents(StringBuilder sb, string? genericArgumentType)
    {
        sb.AppendLine();
        if (genericArgumentType is null)
        {
            sb.AppendLine("    private partial IEnumerable<object?> GetEqualityComponents();");
        }
        else
        {
            sb.AppendLine("    private IEnumerable<object?> GetEqualityComponents() => [Value];");
        }
    }

    /// <summary>
    /// Appends the constructor for generic value objects or non-generic with properties.
    /// </summary>
    private static void AppendConstructor(StringBuilder sb, string typeName, string? genericArgumentType,
        List<IPropertySymbol> props)
    {
        if (genericArgumentType is not null)
        {
            sb.AppendLine();
            sb.AppendLine($"    public {typeName}({genericArgumentType} value)");
            sb.AppendLine("    {");
            sb.AppendLine("        Value = value;");
            sb.AppendLine("    }");
        }
        else if (props.Count > 0)
        {
            sb.AppendLine();
            var parameters = string.Join(", ", props.Select(p => $"{p.Type.ToDisplayString()} {p.Name.ToLower()}"));
            sb.AppendLine($"    public {typeName}({parameters})");
            sb.AppendLine("    {");
            foreach (var prop in props)
            {
                sb.AppendLine($"        {prop.Name} = {prop.Name.ToLower()};");
            }

            sb.AppendLine("    }");
        }
    }

    /// <summary>
    /// Appends the Equals method override.
    /// </summary>
    private static void AppendEquals(StringBuilder sb, string typeName)
    {
        sb.AppendLine();
        sb.AppendLine("    public override bool Equals(object? obj)");
        sb.AppendLine("    {");
        sb.AppendLine($"        if (obj is not {typeName} other) return false;");
        sb.AppendLine("        return GetEqualityComponents().SequenceEqual(other.GetEqualityComponents());");
        sb.AppendLine("    }");
    }

    /// <summary>
    /// Appends the equality operators (== and !=).
    /// </summary>
    private static void AppendEqualityOperators(StringBuilder sb, string typeName)
    {
        sb.AppendLine();
        sb.AppendLine($"    public static bool operator ==({typeName} a, {typeName} b)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (a is null && b is null) return true;");
        sb.AppendLine("        if (a is null || b is null) return false;");
        sb.AppendLine("        return a.Equals(b);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    public static bool operator !=({typeName} a, {typeName} b)");
        sb.AppendLine("    {");
        sb.AppendLine("        return !(a == b);");
        sb.AppendLine("    }");
    }

    /// <summary>
    /// Appends the GetHashCode override with caching.
    /// </summary>
    private static void AppendGetHashCode(StringBuilder sb)
    {
        sb.AppendLine();
        sb.AppendLine("    public override int GetHashCode()");
        sb.AppendLine("    {");
        sb.AppendLine("        if (!_cachedHashCode.HasValue)");
        sb.AppendLine("        {");
        sb.AppendLine("            _cachedHashCode = GetEqualityComponents()");
        sb.AppendLine("                .Aggregate(1, (current, obj) =>");
        sb.AppendLine("                {");
        sb.AppendLine("                    unchecked");
        sb.AppendLine("                    {");
        sb.AppendLine("                        return current * 23 + (obj?.GetHashCode() ?? 0);");
        sb.AppendLine("                    }");
        sb.AppendLine("                });");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        return _cachedHashCode.Value;");
        sb.AppendLine("    }");
    }

    /// <summary>
    /// Appends the CompareTo methods for IComparable implementation.
    /// </summary>
    private static void AppendCompareTo(StringBuilder sb, string typeName)
    {
        sb.AppendLine();
        sb.AppendLine($"    public int CompareTo({typeName}? other)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (other is null) return 1;");
        sb.AppendLine();
        sb.AppendLine("        if (ReferenceEquals(this, other)) return 0;");
        sb.AppendLine();
        sb.AppendLine("        if (this.GetType() != other.GetType())");
        sb.AppendLine(
            "            return string.Compare(this.GetType().FullName, other.GetType().FullName, StringComparison.Ordinal);");
        sb.AppendLine();
        sb.AppendLine("        return GetEqualityComponents()");
        sb.AppendLine("                 .OfType<IComparable>()");
        sb.AppendLine(
            "                 .Zip(other.GetEqualityComponents().OfType<IComparable>(), (a, b) => a?.CompareTo(b) ?? (b is null ? 0 : -1))");
        sb.AppendLine("                 .FirstOrDefault();");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    public int CompareTo(object? other)");
        sb.AppendLine("    {");
        sb.AppendLine($"        return CompareTo(other as {typeName});");
        sb.AppendLine("    }");
    }

    /// <summary>
    /// Appends the implicit conversion operator for generic value objects.
    /// </summary>
    private static void AppendImplicitOperator(StringBuilder sb, string typeName, string? genericArgumentType)
    {
        if (genericArgumentType is null) return;
        sb.AppendLine();
        sb.AppendLine($"    public static implicit operator {genericArgumentType}?({typeName}? valueObject)");
        sb.AppendLine("    {");
        sb.AppendLine("        return valueObject?.Value;");
        sb.AppendLine("    }");
    }

    /// <summary>
    /// Appends the ToString override.
    /// </summary>
    private static void AppendToString(StringBuilder sb, string? genericArgumentType, List<IPropertySymbol> properties)
    {
        sb.AppendLine();
        sb.AppendLine("    public override string ToString()");
        sb.AppendLine("    {");

        if (genericArgumentType is not null)
        {
            sb.AppendLine("        return Value?.ToString() ?? this.ToString();");
        }
        else
        {
            sb.AppendLine("        var sb = new StringBuilder();");
            sb.AppendLine("""        sb.Append("{ ");""");

            var lastProperty = properties.LastOrDefault();
            properties.ForEach(p =>
            {
                sb.AppendLine($$"""        sb.Append($"{{p.Name}} = {{{p.Name}}}");""");

                if (!lastProperty!.Equals(p, SymbolEqualityComparer.Default))
                    sb.AppendLine("""        sb.Append(", ");""");
            });

            sb.AppendLine("""        sb.Append(" }");""");
            sb.AppendLine("        return sb.ToString();");
        }

        sb.AppendLine("    }");
    }

    /// <summary>
    /// Generates the partial class that implements IValueObject and equality/comparison logic.
    /// </summary>
    private static string GeneratePartialClass(INamedTypeSymbol classSymbol)
    {
        var namespaceName = GetNamespaceDeclaration(classSymbol);
        var typeName = GetFullTypeName(classSymbol);
        var genericArgumentType = ExtractGenericArgumentType(classSymbol);
        var readableProperties = GetPublicReadableProperties(classSymbol);
        var writableProperties = GetPublicWritableProperties(classSymbol);

        var sb = new StringBuilder();

        AppendCodeHeader(sb);

        sb.AppendLine(namespaceName);
        sb.AppendLine();

        AppendClassDeclaration(sb, typeName);

        AppendValueProperty(sb, genericArgumentType);

        sb.AppendLine();

        AppendConstructor(sb, typeName, genericArgumentType, writableProperties);

        AppendEquals(sb, typeName);
        AppendEqualityOperators(sb, typeName);
        AppendGetHashCode(sb);
        AppendCompareTo(sb, typeName);

        AppendGetEqualityComponents(sb, genericArgumentType);

        AppendImplicitOperator(sb, typeName, genericArgumentType);
        AppendToString(sb, genericArgumentType, readableProperties);

        sb.AppendLine("}");
        sb.AppendLine();

        return sb.ToString();
    }

    /// <summary>
    /// Returns helper type definitions that are added during post-initialization.
    /// </summary>
    private static string GenerateValueObjectMarkerType()
    {
        // lang=c#
        return """

               namespace Majal
               {
                   /// <summary>
                   /// Marker interface for domain value objects.
                   /// </summary>
                   public interface IValueObject { }
               }

               """;
    }


    /// <summary>
    /// Returns attribute type definitions that are added during post-initialization.
    /// </summary>
    private static string GenerateAttributesType()
    {
        // lang=c#
        return """

               using System;

               namespace Majal
               {
                 
                   /// <summary>
                   /// Apply to a class to indicate it is a DDD value object.
                   /// </summary>
                   [AttributeUsage(AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
                   public sealed class ValueObjectAttribute : Attribute
                   {
                   }

                   /// <summary>
                   /// Apply to a class to indicate it is a DDD value object with a specific Value type.
                   /// </summary>
                   [AttributeUsage(AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
                   public sealed class ValueObjectAttribute<TValue> : Attribute
                   {
                   }
               }

               """;
    }
}