//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Majal source generator
// </auto-generated>
//------------------------------------------------------------------------------

namespace Majal;

/// <summary>
/// Configuration for the EntityAttribute.
/// </summary>
[global::System.Flags]
public enum EntityConfiguration
{
    Default = 0,

    /// <summary>
    /// Indicates that the entity should have an Ordinal property for custom ordering.
    /// </summary>
    Ordinal = 1 << 0,

    /// <summary>
    /// Indicates that the entity should be auditable.
    /// </summary>
    Auditable = 1 << 1,

    /// <summary>
    /// Indicates that the entity should be archivable.
    /// </summary>
    Archivable = 1 << 2,

    /// <summary>
    /// Indicates that the entity should have all optional features (Ordinal, Auditable, Archivable).
    /// </summary>
    All = Auditable | Archivable | Ordinal
}