//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Majal source generator
// </auto-generated>
//------------------------------------------------------------------------------

namespace Majal;

/// <summary>
/// Marker interface for auditable domain entities.
/// </summary>
public interface IAuditableEntity
{
    /// <summary>
    /// The date and time when the entity was created. This property is typically set once at creation and is immutable.
    /// </summary>
    global::System.DateTime CreatedOn { get; }

    /// <summary>
    /// The date and time when the entity was last updated. This property is typically updated whenever the entity undergoes changes.
    /// It is nullable to allow for entities that have not been updated since creation.
    /// </summary>
    global::System.DateTime? UpdatedOn { get; }
}