using Majal.Common.Abstractions;
using static Majal.Common.Abstractions.Constants;

namespace Majal.Generators.Ordinals;

public class OrdinalTemplate : BaseTemplate
{
    public OrdinalGenerator.OrdinalData Data { get; init; }

    public override string TransformText()
    {
        Clear();
        WriteLine("// <auto-generated />");
        WriteLine("");
        WriteLine("#nullable enable");
        WriteLine("");
        WriteLine(Data.Namespace);
        WriteLine("");
        WriteLine("/// <summary>");
        WriteLine($"/// Provides ordinal ordering support for <see cref=\"{Data.TypeName}\"/>.");
        WriteLine("/// </summary>");
        WriteLine($"public partial class {Data.TypeName} : {MajalNamespace}.IOrdinal");
        WriteLine("{");
        PushIndent();
        WriteLine("/// <inheritdoc />");
        WriteLine($"public required {UIntType} Ordinal {{ get; set; }}");
        WriteLine("");
        WriteLine("/// <summary>Assigns ordinal positions based on the order of the supplied entities.</summary>");
        WriteLine($"public static void Reorder(global::System.Collections.Generic.IReadOnlyList<{Data.TypeName}> entities)");
        WriteLine("{");
        PushIndent();
        WriteLine("for (var i = 0; i < entities.Count; i++)");
        WriteLine("{");
        PushIndent();
        WriteLine("entities[i].Ordinal = (uint)i;");
        PopIndent();
        WriteLine("}");
        PopIndent();
        WriteLine("}");
        PopIndent();
        WriteLine("}");

        return ToString();
    }
}