using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;
using Majal.Common;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Majal.Generators;

/// <summary>
/// Generates a partial class for every class marked with [Aggregate].
/// The generated class implements IAggregate and adds domain-event plumbing.
/// </summary>
[Generator]
public sealed class AggregateGenerator : IIncrementalGenerator
{
    // Record struct to hold the data needed to generate the aggregate root class
    private readonly record struct AggregateData(string Name, string Namespace, string DomainEventType)
    {
        public string Name { get; } = Name;
        public string Namespace { get; } = Namespace;
        public string DomainEventType { get; } = DomainEventType;
    }

    // Constants for source generation
    private const string AggregateFilenameSuffix = ".Aggregate.g.cs";
    private const string AggregateMarkerFilename = "IAggregate.g.cs";
    private const string AttributeFilename = "AggregateAttribute.g.cs";
    private const string EntityAttributeName = "EntityAttribute";
    private const string AggregateAttributeName = "AggregateAttribute";
    private const string AggregateAttributeFullName = "Majal.AggregateAttribute`1";
    private const string AutoGeneratedHeader = "// <auto-generated />";
    private const string NullableEnable = "#nullable enable";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        RegisterPredefinedTypes(context);
        RegisterAggregateGenerators(context);
    }

    /// <summary>
    /// Registers the predefined types (IAggregate, AggregateAttribute) that will be available to all generated code.
    /// </summary>
    private static void RegisterPredefinedTypes(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
        {
            ctx.AddSource(AttributeFilename, Sources.AggregateAttributeSource);
            ctx.AddSource(AggregateMarkerFilename, Sources.AggregateMarkerInterfaceSource);
        });
    }

    /// <summary>
    /// Registers the aggregate generator pipeline that processes classes marked with [Aggregate] and [Entity].
    /// </summary>
    private static void RegisterAggregateGenerators(IncrementalGeneratorInitializationContext context)
    {
        // Get classes with attributes
        var entities = context.SyntaxProvider
            .ForAttributeWithMetadataName(AggregateAttributeFullName,
                predicate: (node, _) => node is ClassDeclarationSyntax, transform: GetDataToGenerate)
            .Where(static m => m is not null)
            .Select(static (m, _) => m!.Value);

        // Generate source for each aggregate
        context.RegisterSourceOutput(entities, (spc, classSymbol) =>
        {
            var source = GeneratePartialClass(classSymbol);
            spc.AddSource($"{classSymbol.Name}{AggregateFilenameSuffix}", SourceText.From(source, Encoding.UTF8));
        });
    }

    /// <summary>
    /// Extracts the necessary information from the class symbol to generate the aggregate class.
    /// </summary>
    /// <param name="context">the generator context</param>
    /// <param name="ct">the cancellation token</param>
    /// <returns>the data needed to generate the aggregate</returns>
    private static AggregateData? GetDataToGenerate(GeneratorAttributeSyntaxContext context, CancellationToken ct)
    {
        if (context.TargetSymbol is not INamedTypeSymbol classSymbol) return null;

        var typeName = classSymbol.Name;

        if (classSymbol.TypeParameters.Length > 0)
            typeName += $"<{string.Join(", ", classSymbol.TypeParameters.Select(t => t.Name))}>";


        var aggregateRootAttribute = classSymbol.GetAttributes()
            .FirstOrDefault(a => a.AttributeClass?.Name == AggregateAttributeName);

        var hasEntityAttribute = classSymbol.GetAttributes()
            .Any(a => a.AttributeClass is { Name: EntityAttributeName, IsGenericType: true, TypeArguments.Length: 1 });

        if (aggregateRootAttribute?.AttributeClass is not { TypeArguments.Length: > 0 } ||
            !hasEntityAttribute) return null;

        return new AggregateData(
            Name: typeName,
            Namespace: $"namespace {classSymbol.ContainingNamespace.ToDisplayString()};",
            DomainEventType: aggregateRootAttribute.AttributeClass.TypeArguments[0].ToDisplayString()
        );
    }

    /// <summary>
    /// Appends the standard code header with usings and namespace.
    /// </summary>
    private static void AppendCodeHeader(StringBuilder sb, AggregateData data)
    {
        sb.AppendLine(AutoGeneratedHeader);
        sb.AppendLine();
        sb.AppendLine(data.Namespace);
        sb.AppendLine();
        sb.AppendLine(NullableEnable);
        sb.AppendLine();
    }

    /// <summary>
    /// Appends the class definition line with appropriate interfaces.
    /// </summary>
    private static void AppendClassDeclaration(StringBuilder sb, AggregateData data)
    {
        List<string> interfaces = [$"global::Majal.IAggregate<{data.DomainEventType}>"];

        sb.AppendLine($"public partial class {data.Name} : {string.Join(", ", interfaces)}");
        sb.AppendLine("{");
        sb.AppendLine();
    }


    /// <summary>
    /// Generates the properties for the aggregates.
    /// </summary>
    private static void GenerateProperties(StringBuilder sb, AggregateData data)
    {
        AppendAggregateProperties(sb, data.DomainEventType);
    }

    /// <summary>
    /// Appends aggregates properties (Events collection).
    /// </summary>
    private static void AppendAggregateProperties(StringBuilder sb, string genericEventType)
    {
        sb.AppendLine(
            $"    private readonly global::System.Collections.Generic.List<{genericEventType}> _events = [];");
        sb.AppendLine("    /// <inheritdoc />");
        sb.AppendLine(
            $"    public global::System.Collections.Generic.IEnumerable<{genericEventType}> Events => _events;");
        sb.AppendLine();
        sb.AppendLine();
    }

    /// <summary>
    /// Generates the methods for the aggregates.
    /// </summary>
    private static void GenerateMethods(StringBuilder sb, AggregateData data)
    {
        AppendPublishMethod(sb, data.DomainEventType);
        AppendClearMethod(sb);
    }

    /// <summary>
    /// Appends the Publish method for aggregates.
    /// </summary>
    private static void AppendPublishMethod(StringBuilder sb, string genericEventType)
    {
        sb.AppendLine("    /// <inheritdoc />");
        sb.AppendLine($"    public void Publish({genericEventType} @event)");
        sb.AppendLine("    {");
        sb.AppendLine("        _events.Add(@event);");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    /// <summary>
    /// Appends the Clear method for aggregates.
    /// </summary>
    private static void AppendClearMethod(StringBuilder sb)
    {
        sb.AppendLine("    /// <inheritdoc />");
        sb.AppendLine("    public void Clear()");
        sb.AppendLine("    {");
        sb.AppendLine("        _events.Clear();");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    /// <summary>
    /// Generates the common footer for generated code files.
    /// </summary>
    private static void AppendCodeFooter(StringBuilder sb)
    {
        sb.AppendLine("}");
        sb.AppendLine();
    }

    /// <summary>
    /// Generates the partial class that implements IAggregate of TDomainEvent and domain-event helpers.
    /// </summary>
    private static string GeneratePartialClass(AggregateData data)
    {
        var sb = new StringBuilder();

        AppendCodeHeader(sb, data);
        AppendClassDeclaration(sb, data);
        GenerateProperties(sb, data);
        GenerateMethods(sb, data);
        AppendCodeFooter(sb);

        return sb.ToString();
    }
}