using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Majal.Generators;

/// <summary>
/// Generates a partial class for every class marked with [Entity].
/// The generated class implements IEntity and adds domain-event plumbing.
/// </summary>
[Generator]
public sealed class EntityGenerator : IIncrementalGenerator
{
    // Constants for source generation
    private const string EntityFilenameSuffix = ".Entity.g.cs";
    private const string EntityAttributeName = "EntityAttribute";
    private const string AttributeFilename = "EntityAttribute.g.cs";
    private const string EntityMarkerInterfaceFilename = "IEntity.g.cs";
    private const string AuditableEntityMarkerInterfaceFilename = "IAudiableEntity.g.cs";
    private const string ArchivableMarkerInterfaceFilename = "IArchivableEntity.g.cs";
    private const string OrdinalEntityMarkerInterfaceFilename = "IOrdinalEntity.g.cs";
    private const string AutoGeneratedHeader = "// <auto-generated />";
    private const string NullableEnable = "#nullable enable";


    /// <summary>
    /// Represents the configuration extracted from the EntityAttribute.
    /// </summary>
    private record struct EntityConfiguration(string IdType, EntityOptions Options)
    {
        public static readonly EntityConfiguration Default = new("global::System.Int32", EntityOptions.Default);
    }

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        RegisterPredefinedTypes(context);
        RegisterEntityGenerators(context);
    }

    /// <summary>
    /// Registers the predefined types (IEntity, IAuditableEntity, IArchivableEntity, IOrdinalEntity, EntityAttribute)
    /// that will be available to all generated code.
    /// </summary>
    private static void RegisterPredefinedTypes(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
        {
            ctx.AddSource(AttributeFilename, EmbeddedSources.EntityAttributeSource);
            ctx.AddSource(EntityMarkerInterfaceFilename, EmbeddedSources.EntityMarkerInterfaceSource);
            ctx.AddSource(AuditableEntityMarkerInterfaceFilename, EmbeddedSources.AuditableEntityMarkerInterfaceSource);
            ctx.AddSource(ArchivableMarkerInterfaceFilename, EmbeddedSources.ArchivableEntityMarkerInterfaceSource);
            ctx.AddSource(OrdinalEntityMarkerInterfaceFilename, EmbeddedSources.OrdinalEntityMarkerInterfaceSource);
        });
    }

    /// <summary>
    /// Registers the entity generator pipeline that processes classes marked with [Entity].
    /// </summary>
    private static void RegisterEntityGenerators(IncrementalGeneratorInitializationContext context)
    {
        // Get classes with attributes
        var classesWithAttributes = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax { AttributeLists.Count: > 0 },
                transform: static (ctx, _) =>
                    ctx.SemanticModel.GetDeclaredSymbol((ClassDeclarationSyntax)ctx.Node) as INamedTypeSymbol)
            .Where(static symbol => symbol is not null);

        // Filter to classes that carry the [Entity] attribute
        var entities = classesWithAttributes
            .Where(HasEntityAttribute)
            .Select((classSymbol, _) => classSymbol!);

        // Generate source for each entity
        context.RegisterSourceOutput(entities, (spc, classSymbol) =>
        {
            var source = GeneratePartialClass(classSymbol);
            spc.AddSource($"{classSymbol.Name}{EntityFilenameSuffix}", SourceText.From(source, Encoding.UTF8));
        });
    }

    /// <summary>
    /// Determines if a class has the EntityAttribute generic attribute.
    /// </summary>
    private static bool HasEntityAttribute(INamedTypeSymbol? classSymbol)
    {
        if (classSymbol == null) return false;
        return classSymbol
            .GetAttributes()
            .Any(a => a.AttributeClass is { Name: EntityAttributeName, IsGenericType: true, TypeArguments.Length: 1 });
    }

    /// <summary>
    /// Generates the partial class that implements IEntity and domain-event helpers.
    /// </summary>
    private static string GeneratePartialClass(INamedTypeSymbol classSymbol)
    {
        var config = ParseEntityConfiguration(classSymbol);
        var typeName = GetFullTypeName(classSymbol);
        var namespaceName = GetNamespaceDeclaration(classSymbol);

        var sb = new StringBuilder();
        AppendCodeHeader(sb, namespaceName);
        AppendClassDeclaration(sb, typeName, config);

        sb.AppendLine("{");
        GenerateProperties(sb, classSymbol, config);
        GenerateMethods(sb, typeName, config);
        sb.AppendLine("}");
        sb.AppendLine();

        return sb.ToString();
    }

    /// <summary>
    /// Gets the full type name including generic parameters if present.
    /// </summary>
    private static string GetFullTypeName(INamedTypeSymbol classSymbol)
    {
        var typeName = classSymbol.Name;
        if (classSymbol.TypeParameters.Length > 0)
        {
            typeName += $"<{string.Join(", ", classSymbol.TypeParameters.Select(t => t.Name))}>";
        }

        return typeName;
    }

    /// <summary>
    /// Gets the namespace declaration formatted for the generated code.
    /// </summary>
    private static string GetNamespaceDeclaration(INamedTypeSymbol classSymbol)
    {
        return classSymbol.ContainingNamespace.IsGlobalNamespace
            ? string.Empty
            : $"namespace {classSymbol.ContainingNamespace.ToDisplayString()};";
    }

    /// <summary>
    /// Appends the standard code header with usings and namespace.
    /// </summary>
    private static void AppendCodeHeader(StringBuilder sb, string namespaceName)
    {
        sb.AppendLine(AutoGeneratedHeader);
        sb.AppendLine();
        sb.AppendLine(namespaceName);
        sb.AppendLine();
        sb.AppendLine(NullableEnable);
        sb.AppendLine();
    }

    /// <summary>
    /// Appends the class definition line with appropriate interfaces.
    /// </summary>
    private static void AppendClassDeclaration(StringBuilder sb, string typeName, EntityConfiguration config)
    {
        var interfaces = new List<string> { $"global::Majal.IEntity<{config.IdType}>" };

        if (config.Options.HasFlag(EntityOptions.Archivable))
            interfaces.Add("global::Majal.IArchivableEntity");

        if (config.Options.HasFlag(EntityOptions.Auditable))
            interfaces.Add("global::Majal.IAuditableEntity");

        if (config.Options.HasFlag(EntityOptions.Ordinal))
            interfaces.Add("global::Majal.IOrdinalEntity");

        interfaces.Add("global::System.IComparable");
        interfaces.Add($"global::System.IComparable<{typeName}>");

        sb.AppendLine($"public partial class {typeName} : {string.Join(", ", interfaces)}");
    }

    /// <summary>
    /// Parses the EntityAttribute to extract the full configuration.
    /// </summary>
    private static EntityConfiguration ParseEntityConfiguration(INamedTypeSymbol classSymbol)
    {
        var entityAttribute = classSymbol.GetAttributes()
            .FirstOrDefault(a => a.AttributeClass?.Name == EntityAttributeName);

        if (entityAttribute == null) return EntityConfiguration.Default;

        var idType = ExtractIdTypeFromAttribute(entityAttribute);

        var options = EntityOptions.Default;

        // Parse the options from constructor arguments
        if (entityAttribute.ConstructorArguments.Length > 0 &&
            entityAttribute.ConstructorArguments[0].Value is int entityOptions)
        {
            options = (EntityOptions)entityOptions;
        }

        return new EntityConfiguration(idType, options);
    }

    /// <summary>
    /// Extracts the Id type from the generic EntityAttribute.
    /// </summary>
    private static string ExtractIdTypeFromAttribute(AttributeData entityAttribute)
    {
        return entityAttribute.AttributeClass?.TypeArguments.Length > 0
            ? entityAttribute.AttributeClass.TypeArguments[0].ToDisplayString()
            : "global::System.Int32"; // default fallback
    }

    /// <summary>
    /// Generates the properties for the entity.
    /// </summary>
    private static void GenerateProperties(StringBuilder sb, INamedTypeSymbol classSymbol, EntityConfiguration config)
    {
        AppendIdProperty(sb, classSymbol, config);

        if (config.Options.HasFlag(EntityOptions.Ordinal))
            AppendOrdinalProperty(sb, classSymbol);

        if (config.Options.HasFlag(EntityOptions.Auditable))
            AppendAuditableProperties(sb, classSymbol);

        if (config.Options.HasFlag(EntityOptions.Archivable))
            AppendArchivableProperties(sb, classSymbol);
    }

    /// <summary>
    /// Appends the Id property if not already defined in the class.
    /// </summary>
    private static void AppendIdProperty(StringBuilder sb, INamedTypeSymbol classSymbol, EntityConfiguration config)
    {
        if (classSymbol.GetMembers().Any(m => m.Name == "Id" && m.Kind == SymbolKind.Property)) return;
        sb.AppendLine("    /// <inheritdoc />");
        sb.AppendLine($"    public {config.IdType} Id {{ get; init; }}");
        sb.AppendLine();
    }


    /// <summary>
    /// Appends the Ordinal property if not already defined in the class.
    /// </summary>
    private static void AppendOrdinalProperty(StringBuilder sb, INamedTypeSymbol classSymbol)
    {
        if (classSymbol.GetMembers().Any(m => m.Name == "Ordinal" && m.Kind == SymbolKind.Property)) return;

        sb.AppendLine("    /// <inheritdoc />");
        sb.AppendLine("    public global::System.UInt32 Ordinal { get; set; }");
        sb.AppendLine();
    }


    /// <summary>
    /// Appends auditable entity properties (CreatedOn, UpdatedOn).
    /// </summary>
    private static void AppendAuditableProperties(StringBuilder sb, INamedTypeSymbol classSymbol)
    {
        if (!classSymbol.GetMembers().Any(m => m.Name == "CreatedOn" && m.Kind == SymbolKind.Property))
        {
            sb.AppendLine("    /// <inheritdoc />");
            sb.AppendLine("    public global::System.DateTime CreatedOn { get; init; }");
        }

        sb.AppendLine();

        if (!classSymbol.GetMembers().Any(m => m.Name == "UpdatedOn" && m.Kind == SymbolKind.Property))
        {
            sb.AppendLine("    /// <inheritdoc />");
            sb.AppendLine("    public global::System.DateTime? UpdatedOn { get; set; }");
        }

        sb.AppendLine();
    }

    /// <summary>
    /// Appends archivable entity properties (IsArchived, ArchivedOn).
    /// </summary>
    private static void AppendArchivableProperties(StringBuilder sb, INamedTypeSymbol classSymbol)
    {
        if (!classSymbol.GetMembers().Any(m => m.Name == "IsArchived" && m.Kind == SymbolKind.Property))
        {
            sb.AppendLine("    /// <inheritdoc />");
            sb.AppendLine("    public global::System.Boolean IsArchived { get; set; }");
        }

        sb.AppendLine();

        if (!classSymbol.GetMembers().Any(m => m.Name == "ArchivedOn" && m.Kind == SymbolKind.Property))
        {
            sb.AppendLine("    /// <inheritdoc />");
            sb.AppendLine("    public global::System.DateTime? ArchivedOn { get; set; }");
        }

        sb.AppendLine();
    }


    /// <summary>
    /// Generates the methods for the entity.
    /// </summary>
    private static void GenerateMethods(StringBuilder sb, string typeName, EntityConfiguration config)
    {
        AppendEqualsMethod(sb, typeName);
        AppendIsTransientMethod(sb, config);
        AppendEqualityOperators(sb, typeName);
        AppendGetHashCodeMethod(sb);
        AppendCompareToMethods(sb, typeName);
    }

    /// <summary>
    /// Appends the Equals method override.
    /// </summary>
    private static void AppendEqualsMethod(StringBuilder sb, string typeName)
    {
        sb.AppendLine("    public override global::System.Boolean Equals(object? obj)");
        sb.AppendLine("    {");
        sb.AppendLine($"        if (obj is not {typeName} other) return false;");
        sb.AppendLine("        if (ReferenceEquals(this, other)) return true;");
        sb.AppendLine("        if (IsTransient() || other.IsTransient()) return false;");
        sb.AppendLine("        return base.Equals(obj);");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    /// <summary>
    /// Appends the IsTransient helper method.
    /// </summary>
    private static void AppendIsTransientMethod(StringBuilder sb, EntityConfiguration config)
    {
        sb.AppendLine("    private global::System.Boolean IsTransient()");
        sb.AppendLine("    {");
        sb.AppendLine($"        return Id.Equals(default({config.IdType}));");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    /// <summary>
    /// Appends the equality operators (== and !=).
    /// </summary>
    private static void AppendEqualityOperators(StringBuilder sb, string typeName)
    {
        sb.AppendLine($"    public static global::System.Boolean operator ==({typeName} a, {typeName} b)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (a is null && b is null) return true;");
        sb.AppendLine("        if (a is null || b is null) return false;");
        sb.AppendLine("        return a.Equals(b);");
        sb.AppendLine("    }");
        sb.AppendLine();

        sb.AppendLine($"    public static global::System.Boolean operator !=({typeName} a, {typeName} b)");
        sb.AppendLine("    {");
        sb.AppendLine("        return !(a == b);");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    /// <summary>
    /// Appends the GetHashCode method override.
    /// </summary>
    private static void AppendGetHashCodeMethod(StringBuilder sb)
    {
        sb.AppendLine("    public override global::System.Int32 GetHashCode()");
        sb.AppendLine("    {");
        sb.AppendLine("        return (GetType().ToString() + Id).GetHashCode();");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    /// <summary>
    /// Appends the CompareTo method overloads (generic and non-generic).
    /// </summary>
    private static void AppendCompareToMethods(StringBuilder sb, string typeName)
    {
        sb.AppendLine($"    public global::System.Int32 CompareTo({typeName}? other)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (other is null) return 1;");
        sb.AppendLine("        if (ReferenceEquals(this, other)) return 0;");
        sb.AppendLine("        return Id.CompareTo(other.Id);");
        sb.AppendLine("    }");
        sb.AppendLine();

        sb.AppendLine("    public global::System.Int32 CompareTo(object? other)");
        sb.AppendLine("    {");
        sb.AppendLine($"        return CompareTo(other as {typeName});");
        sb.AppendLine("    }");
        sb.AppendLine();
    }
}