using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;
using Majal.Common;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Majal.Generators;

/// <summary>
/// Generates a partial class for every class marked with [Entity].
/// The generated class implements IEntity and adds domain-event plumbing.
/// </summary>
[Generator]
public sealed class EntityGenerator : IIncrementalGenerator
{
    // Record struct to hold the data needed to generate the entity class
    private readonly record struct EntityData
    {
        public string Name { get; }
        public string Namespace { get; }
        public string IdType { get; }
        public bool HasConstructor { get; }
        public EquatableList<string> Properties { get; }
        public EntityConfiguration? Configuration { get; }

        public EntityData(string name, string @namespace, string[] properties, string idType,
            bool hasConstructor, EntityConfiguration? configuration = null)
        {
            Name = name;
            Namespace = @namespace;
            HasConstructor = hasConstructor;
            IdType = idType;
            Properties = new EquatableList<string>(properties);
            Configuration = configuration;
        }
    }


    // Constants for source generation
    private const string EntityFilenameSuffix = ".Entity.g.cs";
    private const string EntityAttributeFullName = "Majal.EntityAttribute`1";
    private const string EntityAttributeName = "EntityAttribute";
    private const string AttributeFilename = "EntityAttribute.g.cs";
    private const string EntityMarkerInterfaceFilename = "IEntity.g.cs";
    private const string EntityConfigurationFilename = "EntityConfiguration.g.cs";
    private const string AuditableEntityMarkerInterfaceFilename = "IAudiableEntity.g.cs";
    private const string ArchivableMarkerInterfaceFilename = "IArchivableEntity.g.cs";
    private const string OrdinalEntityMarkerInterfaceFilename = "IOrdinalEntity.g.cs";
    private const string AutoGeneratedHeader = "// <auto-generated />";
    private const string NullableEnable = "#nullable enable";


    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        RegisterPredefinedTypes(context);
        RegisterEntityGenerators(context);
    }

    /// <summary>
    /// Registers the predefined types (IEntity, IAuditableEntity, IArchivableEntity, IOrdinalEntity, EntityAttribute)
    /// that will be available to all generated code.
    /// </summary>
    private static void RegisterPredefinedTypes(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
        {
            ctx.AddSource(AttributeFilename, Sources.EntityAttributeSource);
            ctx.AddSource(EntityMarkerInterfaceFilename, Sources.EntityMarkerInterfaceSource);
            ctx.AddSource(AuditableEntityMarkerInterfaceFilename, Sources.AuditableEntityMarkerInterfaceSource);
            ctx.AddSource(ArchivableMarkerInterfaceFilename, Sources.ArchivableEntityMarkerInterfaceSource);
            ctx.AddSource(OrdinalEntityMarkerInterfaceFilename, Sources.OrdinalEntityMarkerInterfaceSource);
            ctx.AddSource(EntityConfigurationFilename, Sources.EntityConfigurationSource);
        });
    }

    /// <summary>
    /// Registers the entity generator pipeline that processes classes marked with [Entity].
    /// </summary>
    private static void RegisterEntityGenerators(IncrementalGeneratorInitializationContext context)
    {
        // Get classes with attributes
        var entitiesToGenerate = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                EntityAttributeFullName,
                predicate: (node, _) => node is ClassDeclarationSyntax,
                transform: GetDataToGenerate
            );

        // Filter to classes that carry the [Entity] attribute
        var entities = entitiesToGenerate
            .Where(static m => m is not null)
            .Select(static (m, _) => m!.Value);

        // Generate source for each entity
        context.RegisterSourceOutput(entities, (spc, classSymbol) =>
        {
            var source = GeneratePartialClass(classSymbol);
            spc.AddSource($"{classSymbol.Name}{EntityFilenameSuffix}", SourceText.From(source, Encoding.UTF8));
        });
    }

    /// <summary>
    /// Extracts the necessary information from the class symbol to generate the entity class.
    /// </summary>
    /// <param name="context"></param>
    /// <param name="ct"></param>
    /// <returns>EntityToGenerate?</returns>
    private static EntityData? GetDataToGenerate(GeneratorAttributeSyntaxContext context, CancellationToken ct)
    {
        if (context.TargetSymbol is not INamedTypeSymbol classSymbol) return null;

        var typeName = classSymbol.Name;

        if (classSymbol.TypeParameters.Length > 0)
            typeName += $"<{string.Join(", ", classSymbol.TypeParameters.Select(t => t.Name))}>";

        var attributes = classSymbol.GetAttributes().ToArray();

        var entityAttribute = attributes
            .FirstOrDefault(a => a.AttributeClass?.Name == EntityAttributeName);

        if (entityAttribute?.AttributeClass is not { TypeArguments.Length: > 0 }) return null;

        return new EntityData(
            name: typeName,
            @namespace: $"namespace {classSymbol.ContainingNamespace.ToDisplayString()};",
            hasConstructor: classSymbol.Constructors.Any(c => !c.IsImplicitlyDeclared),
            properties:
            [
                .. classSymbol.GetMembers().OfType<IPropertySymbol>().Where(p => p.Kind == SymbolKind.Property)
                    .Select(p => p.Name)
            ],
            idType: entityAttribute.AttributeClass.TypeArguments[0].ToDisplayString(),
            configuration: attributes
                .FirstOrDefault(a => a.AttributeClass?.Name == EntityAttributeName)
                ?.ConstructorArguments.FirstOrDefault().Value is int configuration
                ? (EntityConfiguration)configuration
                : null
        );
    }

    /// <summary>
    /// Appends the standard code header with usings and namespace.
    /// </summary>
    private static void AppendCodeHeader(StringBuilder sb, EntityData data)
    {
        sb.AppendLine(AutoGeneratedHeader);
        sb.AppendLine();
        sb.AppendLine(data.Namespace);
        sb.AppendLine();
        sb.AppendLine(NullableEnable);
        sb.AppendLine();
    }

    /// <summary>
    /// Appends the class definition line with appropriate interfaces.
    /// </summary>
    private static void AppendClassDeclaration(StringBuilder sb, EntityData data)
    {
        var interfaces = new List<string> { $"global::Majal.IEntity<{data.IdType}>" };

        if (data.Configuration?.HasFlag(EntityConfiguration.Archivable) == true)
            interfaces.Add("global::Majal.IArchivableEntity");

        if (data.Configuration?.HasFlag(EntityConfiguration.Auditable) == true)
            interfaces.Add("global::Majal.IAuditableEntity");

        if (data.Configuration?.HasFlag(EntityConfiguration.Ordinal) == true)
            interfaces.Add("global::Majal.IOrdinalEntity");

        interfaces.Add("global::System.IComparable");
        interfaces.Add($"global::System.IComparable<{data.Name}>");

        sb.AppendLine($"public partial class {data.Name} : {string.Join(", ", interfaces)}");
        sb.AppendLine("{");
        sb.AppendLine();
    }

    /// <summary>
    /// Appends the private constructor.
    /// </summary>
    private static void AppendPrivateConstructor(StringBuilder sb, EntityData data)
    {
        if (data.HasConstructor) return;

        sb.AppendLine("     // private constructor for ORMs");
        sb.AppendLine($"    private {data.Name}()");
        sb.AppendLine("    {");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    /// <summary>
    /// Generates the properties for the entity.
    /// </summary>
    private static void GenerateProperties(StringBuilder sb, EntityData data)
    {
        AppendIdProperty(sb, data);

        if (data.Configuration?.HasFlag(EntityConfiguration.Ordinal) == true)
            AppendOrdinalProperty(sb, data);

        if (data.Configuration?.HasFlag(EntityConfiguration.Auditable) == true)
            AppendAuditableProperties(sb, data);

        if (data.Configuration?.HasFlag(EntityConfiguration.Archivable) == true)
            AppendArchivableProperties(sb, data);
    }

    /// <summary>
    /// Appends the Id property if not already defined in the class.
    /// </summary>
    private static void AppendIdProperty(StringBuilder sb, EntityData data)
    {
        if (data.Properties.Contains("Id", StringComparer.OrdinalIgnoreCase)) return;

        sb.AppendLine("    /// <inheritdoc />");
        sb.AppendLine($"    public {data.IdType} Id {{ get; init; }}");
        sb.AppendLine();
    }


    /// <summary>
    /// Appends the Ordinal property if not already defined in the class.
    /// </summary>
    private static void AppendOrdinalProperty(StringBuilder sb, EntityData entityData)
    {
        if (entityData.Properties.Contains("Ordinal", StringComparer.OrdinalIgnoreCase)) return;
        sb.AppendLine("    /// <inheritdoc />");
        sb.AppendLine("    public global::System.UInt32 Ordinal { get; set; }");
        sb.AppendLine();
    }


    /// <summary>
    /// Appends auditable entity properties (CreatedOn, UpdatedOn).
    /// </summary>
    private static void AppendAuditableProperties(StringBuilder sb, EntityData data)
    {
        if (!data.Properties.Contains("CreatedOn", StringComparer.OrdinalIgnoreCase))
        {
            sb.AppendLine("    /// <inheritdoc />");
            sb.AppendLine("    public global::System.DateTime CreatedOn { get; init; }");
        }

        sb.AppendLine();

        if (!data.Properties.Contains("UpdatedOn", StringComparer.OrdinalIgnoreCase))
        {
            sb.AppendLine("    /// <inheritdoc />");
            sb.AppendLine("    public global::System.DateTime? UpdatedOn { get; set; }");
        }

        sb.AppendLine();
    }

    /// <summary>
    /// Appends archivable entity properties (IsArchived, ArchivedOn).
    /// </summary>
    private static void AppendArchivableProperties(StringBuilder sb, EntityData data)
    {
        if (!data.Properties.Contains("IsArchived", StringComparer.OrdinalIgnoreCase))
        {
            sb.AppendLine("    /// <inheritdoc />");
            sb.AppendLine("    public global::System.Boolean IsArchived { get; set; }");
        }

        sb.AppendLine();

        if (!data.Properties.Contains("ArchivedOn", StringComparer.OrdinalIgnoreCase))
        {
            sb.AppendLine("    /// <inheritdoc />");
            sb.AppendLine("    public global::System.DateTime? ArchivedOn { get; set; }");
        }

        sb.AppendLine();
    }


    /// <summary>
    /// Generates the methods for the entity.
    /// </summary>
    private static void GenerateMethods(StringBuilder sb, EntityData data)
    {
        AppendEqualsMethod(sb, data);
        AppendIsTransientMethod(sb, data);
        AppendEqualityOperators(sb, data);
        AppendGetHashCodeMethod(sb);
        AppendCompareToMethods(sb, data);
    }

    /// <summary>
    /// Appends the Equals method override.
    /// </summary>
    private static void AppendEqualsMethod(StringBuilder sb, EntityData data)
    {
        sb.AppendLine("    public override global::System.Boolean Equals(object? obj)");
        sb.AppendLine("    {");
        sb.AppendLine($"        if (obj is not {data.Name} other) return false;");
        sb.AppendLine("        if (ReferenceEquals(this, other)) return true;");
        sb.AppendLine("        if (IsTransient() || other.IsTransient()) return false;");
        sb.AppendLine("        return base.Equals(obj);");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    /// <summary>
    /// Appends the IsTransient helper method.
    /// </summary>
    private static void AppendIsTransientMethod(StringBuilder sb, EntityData data)
    {
        sb.AppendLine("    private global::System.Boolean IsTransient()");
        sb.AppendLine("    {");
        sb.AppendLine($"        return Id.Equals(default({data.IdType}));");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    /// <summary>
    /// Appends the equality operators (== and !=).
    /// </summary>
    private static void AppendEqualityOperators(StringBuilder sb, EntityData data)
    {
        sb.AppendLine(
            $"    public static global::System.Boolean operator ==({data.Name} a, {data.Name} b)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (a is null && b is null) return true;");
        sb.AppendLine("        if (a is null || b is null) return false;");
        sb.AppendLine("        return a.Equals(b);");
        sb.AppendLine("    }");
        sb.AppendLine();

        sb.AppendLine(
            $"    public static global::System.Boolean operator !=({data.Name} a, {data.Name} b)");
        sb.AppendLine("    {");
        sb.AppendLine("        return !(a == b);");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    /// <summary>
    /// Appends the GetHashCode method override.
    /// </summary>
    private static void AppendGetHashCodeMethod(StringBuilder sb)
    {
        sb.AppendLine("    public override global::System.Int32 GetHashCode()");
        sb.AppendLine("    {");
        sb.AppendLine("        return (GetType().ToString() + Id).GetHashCode();");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    /// <summary>
    /// Appends the CompareTo method overloads
    /// </summary>
    private static void AppendCompareToMethods(StringBuilder sb, EntityData data)
    {
        sb.AppendLine($"    public global::System.Int32 CompareTo({data.Name}? other)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (other is null) return 1;");
        sb.AppendLine("        if (ReferenceEquals(this, other)) return 0;");
        sb.AppendLine("        return Id.CompareTo(other.Id);");
        sb.AppendLine("    }");
        sb.AppendLine();

        sb.AppendLine("    public global::System.Int32 CompareTo(object? other)");
        sb.AppendLine("    {");
        sb.AppendLine($"        return CompareTo(other as {data.Name});");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    /// <summary>
    /// Generates the common footer for generated code files.
    /// </summary>
    private static void AppendCodeFooter(StringBuilder sb)
    {
        sb.AppendLine("}");
        sb.AppendLine();
    }

    /// <summary>
    /// Generates the partial class that implements IEntity and domain-event helpers.
    /// </summary>
    private static string GeneratePartialClass(EntityData data)
    {
        var sb = new StringBuilder();
        
        AppendCodeHeader(sb, data);
        AppendClassDeclaration(sb, data);
        AppendPrivateConstructor(sb, data);
        GenerateProperties(sb, data);
        GenerateMethods(sb, data);
        AppendCodeFooter(sb);
        
        return sb.ToString();
    }
}