<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <NoWarn>$(NoWarn);CS1591</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <Using Include="Majal" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.5" />
        <PackageReference Include="SQLitePCLRaw.lib.e_sqlite3" Version="2.1.12" />
        <PackageReference Include="Majal" Version="$(PackageVersion)"  />
        <PackageReference Include="Majal.EntityFrameworkCore" Version="$(PackageVersion)" />
        <PackageReference Include="Majal.DataTransferObjects" Version="$(PackageVersion)" />
    </ItemGroup>

</Project>