using Majal.Generators;
using Microsoft.CodeAnalysis;
using static Majal.Abstractions.Constants;

namespace Majal.Templates;

public class AggregateTemplate(AggregateGenerator.AggregateData data) : BaseTemplate
{

    public override string TransformText()
    {
        Clear();
        WriteLine("// <auto-generated />");
        WriteLine("");
        WriteLine("#nullable enable");
        WriteLine("");
        WriteLine(data.Namespace);
        WriteLine("");
        WriteLine($"public partial class {data.TypeName} : {MajalNamespace}.IAggregate<{data.DomainEventType}>");
        WriteLine("{");
        PushIndent();
        WriteLine($"private readonly {GenericsNamespace}.List<{data.DomainEventType}> _events = [];");
        WriteLine("");
        WriteLine("/// <inheritdoc />");
        WriteLine($"public {GenericsNamespace}.IEnumerable<{data.DomainEventType}> Events => _events;");
        WriteLine("");
        WriteLine("/// <inheritdoc />");
        WriteLine($"public void Publish({data.DomainEventType} @event)");
        WriteLine("{");
        PushIndent();
        WriteLine("_events.Add(@event);");
        PopIndent();
        WriteLine("}");
        WriteLine("");
        WriteLine("/// <inheritdoc />");
        WriteLine("public void Clear()");
        WriteLine("{");
        PushIndent();
        WriteLine("_events.Clear();");
        PopIndent();
        WriteLine("}");
        PopIndent();
        WriteLine("}");

        return ToString();
    }
}