using Majal.Generators;
using Microsoft.CodeAnalysis;
using static Majal.Abstractions.Constants;

namespace Majal.Templates;

public class AggregateTemplate : BaseTemplate
{
    public AggregateGenerator.AggregateData Data { get; init; }

    public override string TransformText()
    {
        Clear();
        WriteLine("// <auto-generated />");
        WriteLine("");
        WriteLine("#nullable enable");
        WriteLine("");
        WriteLine(Data.Namespace);
        WriteLine("");
        WriteLine($"public partial class {Data.TypeName} : {MajalNamespace}.IAggregate<{Data.DomainEventType}>");
        WriteLine("{");
        PushIndent();
        WriteLine($"private readonly {GenericsNamespace}.List<{Data.DomainEventType}> _events = [];");
        WriteLine("");
        WriteLine("/// <inheritdoc />");
        WriteLine($"public {GenericsNamespace}.IEnumerable<{Data.DomainEventType}> Events => _events;");
        WriteLine("");
        WriteLine("/// <inheritdoc />");
        WriteLine($"public void Publish({Data.DomainEventType} @event)");
        WriteLine("{");
        PushIndent();
        WriteLine("_events.Add(@event);");
        PopIndent();
        WriteLine("}");
        WriteLine("");
        WriteLine("/// <inheritdoc />");
        WriteLine("public void Clear()");
        WriteLine("{");
        PushIndent();
        WriteLine("_events.Clear();");
        PopIndent();
        WriteLine("}");
        PopIndent();
        WriteLine("}");

        return ToString();
    }
}