using static Majal.Abstractions.Constants;

namespace Majal.Templates;

public class ArchivableConventionTemplate : BaseTemplate
{
    public override string TransformText()
    {
        Clear();
        WriteLine("// <auto-generated />");
        WriteLine("");
        WriteLine("namespace Majal;");
        WriteLine("");
        WriteLine("#nullable enable");
        WriteLine("");
        WriteLine("public class ArchivableFilterConvention()");
        WriteLine($"    : {EfCoreConventions}.IModelFinalizingConvention");
        WriteLine("{");
        PushIndent();
        WriteLine("public void ProcessModelFinalizing(");
        WriteLine($"    {EfCoreBuilders}.IConventionModelBuilder modelBuilder,");
        WriteLine($"    {EfCoreConventions}.IConventionContext<{EfCoreBuilders}.IConventionModelBuilder> context)");
        WriteLine("{");
        PushIndent();
        WriteLine("foreach (var entityType in modelBuilder.Metadata.GetEntityTypes())");
        WriteLine("{");
        PushIndent();
        WriteLine("// Check if the entity implements IArchivable");
        WriteLine($"if (!typeof({MajalNamespace}.IArchivable).IsAssignableFrom(entityType.ClrType)) continue;");
        WriteLine("");
        WriteLine("// If it's a derived type and its base type also implements IArchivable, skip it");
        WriteLine("// because the filter should be applied to the root of the hierarchy.");
        WriteLine($"if (entityType.BaseType != null && typeof({MajalNamespace}.IArchivable).IsAssignableFrom(entityType.BaseType.ClrType)) continue;");
        WriteLine("");
        WriteLine("// Equivalent to: t => t.IsArchived");
        WriteLine($"""var parameter = {ExpressionsType}.Parameter(entityType.ClrType, "t");""");
        WriteLine($"var property = {ExpressionsType}.Property(parameter, ");
        WriteLine($"    nameof({MajalNamespace}.IArchivable.IsArchived));");
        WriteLine("");
        WriteLine("//  !(t.IsArchived)");
        WriteLine($"var body = {ExpressionsType}.Not(property);");
        WriteLine($"var lambda = {ExpressionsType}.Lambda(body, parameter);");
        WriteLine("");
        WriteLine("// Set the query filter");
        WriteLine("entityType.SetQueryFilter(nameof(IArchivable), lambda);");
        PopIndent();
        WriteLine("}");
        PopIndent();
        WriteLine("}");
        PopIndent();
        WriteLine("}");
        WriteLine("");
        
        WriteLine("public static class ArchivableEfCoreExtensions");
        WriteLine("{");
        PushIndent();
        WriteLine($"public static {LinqNamespace}.IQueryable<TEntity> IgnoreArchivableFilter<TEntity>(");
        WriteLine($"    this {LinqNamespace}.IQueryable<TEntity> source)");
        WriteLine("             where TEntity : class");
        WriteLine("{");
        PushIndent();
        WriteLine($"return {EfCoreNamespace}.EntityFrameworkQueryableExtensions");
        WriteLine($"    .IgnoreQueryFilters(source, [nameof({MajalNamespace}.IArchivable)]);");
        PopIndent();
        WriteLine("}");
        PopIndent();
        WriteLine("}");

        return ToString();
    }
}