using static Majal.Abstractions.Constants;
using Majal.Generators;

namespace Majal.Templates;

public class ArchivableTemplate : BaseTemplate
{
    public ArchivableGenerator.ArchivableData Data { get; init; }

    public override string TransformText()
    {
        Clear();
        WriteLine("// <auto-generated />");
        WriteLine("");
        WriteLine("#nullable enable");
        WriteLine("");
        WriteLine(Data.Namespace);
        WriteLine("");
        WriteLine("/// <summary>");
        WriteLine($"/// Provides archivable soft-delete support for <see cref=\"{Data.TypeName}\"/>.");
        WriteLine("/// </summary>");
        WriteLine($"public partial class {Data.TypeName} : {MajalNamespace}.IArchivable");
        WriteLine("{");
        PushIndent();
        WriteLine("/// <inheritdoc />");
        WriteLine($"public {BoolType} IsArchived {{ get; set; }}");
        WriteLine("");
        WriteLine("/// <inheritdoc />");
        WriteLine($"public {SystemNamespace}.DateTimeOffset? ArchivedOn {{ get; set; }}");
        PopIndent();
        WriteLine("}");

        return ToString();
    }
}