using Majal.Generators;

namespace Majal.Templates;

public class ArchivableInterceptorTemplate : BaseTemplate
{
    private const string ThreadingNamespace = "global::System.Threading";
    private const string TasksNamespace = $"{ThreadingNamespace}.Tasks";
    private const string EfCoreNamespace = "global::Microsoft.EntityFrameworkCore";
    private const string DiagnosticsNamespace = $"{EfCoreNamespace}.Diagnostics";
    private const string IntType = "global::System.Int32";

    public override string TransformText()
    {
        Clear();
        WriteLine("// <auto-generated />");
        WriteLine("");
        WriteLine("namespace Majal;");
        WriteLine("");
        WriteLine("#nullable enable");
        WriteLine("");
        WriteLine($"public class ArchivableSaveChangesInterceptor : {DiagnosticsNamespace}.SaveChangesInterceptor");
        WriteLine("{");
        PushIndent("    ");
        WriteLine($"public override {DiagnosticsNamespace}.InterceptionResult<{IntType}> SavingChanges(");
        WriteLine($"    {DiagnosticsNamespace}.DbContextEventData eventData,");
        WriteLine($"    {DiagnosticsNamespace}.InterceptionResult<{IntType}> result)");
        WriteLine("{");
        PushIndent("    ");
        WriteLine("if (eventData.Context is null)");
        WriteLine("    return base.SavingChanges(eventData, result);");
        WriteLine("");
        WriteLine("UpdateArchivableEntities(eventData.Context!);");
        WriteLine("");
        WriteLine("return base.SavingChanges(eventData, result);");
        PopIndent();
        WriteLine("}");
        WriteLine("");
        WriteLine(
            $"public override {TasksNamespace}.ValueTask<{DiagnosticsNamespace}.InterceptionResult<{IntType}>> SavingChangesAsync(");
        WriteLine($"    {DiagnosticsNamespace}.DbContextEventData eventData, ");
        WriteLine($"    {DiagnosticsNamespace}.InterceptionResult<{IntType}> result, ");
        WriteLine($"    {ThreadingNamespace}.CancellationToken ct)");
        WriteLine("{");
        PushIndent("    ");
        WriteLine("if (eventData.Context is null)");
        WriteLine("    return base.SavingChangesAsync(eventData, result, ct);");
        WriteLine("");
        WriteLine("UpdateArchivableEntities(eventData.Context!);");
        WriteLine("");
        WriteLine("return base.SavingChangesAsync(eventData, result, ct);");
        PopIndent();
        WriteLine("}");
        WriteLine("");
        WriteLine($"private static void UpdateArchivableEntities({EfCoreNamespace}.DbContext context)");
        WriteLine("{");
        PushIndent("    ");
        WriteLine("var entries = context.ChangeTracker");
        WriteLine("    .Entries<global::Majal.IArchivable>()");
        WriteLine($"    .Where(e => e.State == {EfCoreNamespace}.EntityState.Deleted);");
        WriteLine("");
        WriteLine("foreach (var entry in entries)");
        WriteLine("{");
        PushIndent("    ");
        WriteLine("if (entry.Entity is global::Majal.IArchivable entity)");
        WriteLine("{");
        PushIndent("    ");
        WriteLine($"entry.State = {EfCoreNamespace}.EntityState.Modified;");
        WriteLine("entity.ArchivedOn = global::System.DateTimeOffset.UtcNow;");
        WriteLine("entity.IsArchived = true;");
        PopIndent();
        WriteLine("}");
        PopIndent();
        WriteLine("}");
        PopIndent();
        WriteLine("}");
        PopIndent();
        WriteLine("}");

        return ToString();
    }
}