using static Majal.Abstractions.Constants;


namespace Majal.Templates;

public class ArchivableInterceptorTemplate : BaseTemplate
{
    public override string TransformText()
    {
        Clear();
        WriteLine("// <auto-generated />");
        WriteLine("");
        WriteLine("namespace Majal;");
        WriteLine("");
        WriteLine("#nullable enable");
        WriteLine("");
        WriteLine($"public class ArchivableSaveChangesInterceptor : {EfCoreDiagnosticsNamespace}.SaveChangesInterceptor");
        WriteLine("{");
        PushIndent();
        WriteLine($"public override {EfCoreDiagnosticsNamespace}.InterceptionResult<{IntType}> SavingChanges(");
        WriteLine($"    {EfCoreDiagnosticsNamespace}.DbContextEventData eventData,");
        WriteLine($"    {EfCoreDiagnosticsNamespace}.InterceptionResult<{IntType}> result)");
        WriteLine("{");
        PushIndent();
        WriteLine("if (eventData.Context is null)");
        WriteLine("    return base.SavingChanges(eventData, result);");
        WriteLine("");
        WriteLine("UpdateArchivableEntities(eventData.Context!);");
        WriteLine("");
        WriteLine("return base.SavingChanges(eventData, result);");
        PopIndent();
        WriteLine("}");
        WriteLine("");
        WriteLine(
            $"public override {TasksNamespace}.ValueTask<{EfCoreDiagnosticsNamespace}.InterceptionResult<{IntType}>> SavingChangesAsync(");
        WriteLine($"    {EfCoreDiagnosticsNamespace}.DbContextEventData eventData, ");
        WriteLine($"    {EfCoreDiagnosticsNamespace}.InterceptionResult<{IntType}> result, ");
        WriteLine($"    {ThreadingNamespace}.CancellationToken ct)");
        WriteLine("{");
        PushIndent();
        WriteLine("if (eventData.Context is null)");
        WriteLine("    return base.SavingChangesAsync(eventData, result, ct);");
        WriteLine("");
        WriteLine("UpdateArchivableEntities(eventData.Context!);");
        WriteLine("");
        WriteLine("return base.SavingChangesAsync(eventData, result, ct);");
        PopIndent();
        WriteLine("}");
        WriteLine("");
        WriteLine($"private static void UpdateArchivableEntities({EfCoreNamespace}.DbContext context)");
        WriteLine("{");
        PushIndent();
        WriteLine("var entries = context.ChangeTracker");
        WriteLine($"    .Entries<{MajalNamespace}.IArchivable>()");
        WriteLine($"    .Where(e => e.State == {EfCoreNamespace}.EntityState.Deleted);");
        WriteLine("");
        WriteLine("foreach (var entry in entries)");
        WriteLine("{");
        PushIndent();
        WriteLine($"if (entry.Entity is {MajalNamespace}.IArchivable entity)");
        WriteLine("{");
        PushIndent();
        WriteLine($"entry.State = {EfCoreNamespace}.EntityState.Modified;");
        WriteLine($"entity.ArchivedOn = {SystemNamespace}.DateTimeOffset.UtcNow;");
        WriteLine("entity.IsArchived = true;");
        PopIndent();
        WriteLine("}");
        PopIndent();
        WriteLine("}");
        PopIndent();
        WriteLine("}");
        PopIndent();
        WriteLine("}");

        return ToString();
    }
}