namespace Majal.Templates;

public class ArchivableConventionTemplate : BaseTemplate
{
    private const string MajalNamespace = "global::Majal";
    
    private const string ExpressionsNamespace = "global::System.Linq.Expressions";
    private const string ExpressionsType = $"{ExpressionsNamespace}.Expression";

    private const string EfCoreNamespace = "global::Microsoft.EntityFrameworkCore";
    private const string EfCoreBuilders = $"{EfCoreNamespace}.Metadata.Builders";
    private const string EfCoreConventions = $"{EfCoreNamespace}.Metadata.Conventions";

    public override string TransformText()
    {
        Clear();
        WriteLine("// <auto-generated />");
        WriteLine("");
        WriteLine("namespace Majal;");
        WriteLine("");
        WriteLine("#nullable enable");
        WriteLine("");
        WriteLine("public class ArchivableFilterConvention()");
        WriteLine($"    : {EfCoreConventions}.IModelFinalizingConvention");
        WriteLine("{");
        PushIndent("    ");
        WriteLine("public void ProcessModelFinalizing(");
        WriteLine($"    {EfCoreBuilders}.IConventionModelBuilder modelBuilder,");
        WriteLine($"    {EfCoreConventions}.IConventionContext<{EfCoreBuilders}.IConventionModelBuilder> context)");
        WriteLine("{");
        PushIndent("    ");
        WriteLine("foreach (var entityType in modelBuilder.Metadata.GetEntityTypes())");
        WriteLine("{");
        PushIndent("    ");
        WriteLine("// Check if the entity implements IArchivable");
        WriteLine($"if (!typeof({MajalNamespace}.IArchivable).IsAssignableFrom(entityType.ClrType)) continue;");
        WriteLine("");
        WriteLine("// Equivalent to: t => t.IsArchived");
        WriteLine($"""var parameter = {ExpressionsType}.Parameter(entityType.ClrType, "t");""");
        WriteLine($"var property = {ExpressionsType}.Property(parameter, ");
        WriteLine($"    nameof({MajalNamespace}.IArchivable.IsArchived));");
        WriteLine("");
        WriteLine("//  !(t.IsArchived)");
        WriteLine($"var body = {ExpressionsType}.Not(property);");
        WriteLine($"var lambda ={ExpressionsType}.Lambda(body, parameter);");
        WriteLine("");
        WriteLine("// Set the query filter");
        WriteLine("entityType.SetQueryFilter(lambda);");
        PopIndent();
        WriteLine("}");
        PopIndent();
        WriteLine("}");
        PopIndent();
        WriteLine("}");

        return ToString();
    }
}