using Majal.Generators;

namespace Majal.Templates;

public class ArchivableTemplate : BaseTemplate
{
    public ArchivableGenerator.ArchivableData Data { get; init; }

    public override string TransformText()
    {
        Clear();
        WriteLine("// <auto-generated />");
        WriteLine("");
        WriteLine("#nullable enable");
        WriteLine("");
        WriteLine(Data.Namespace);
        WriteLine("");
        WriteLine($"public partial class {Data.TypeName} : global::Majal.IArchivable");
        WriteLine("{");
        PushIndent("    ");
        WriteLine("/// <inheritdoc />");
        WriteLine("public global::System.Boolean IsArchived { get; set; }");
        WriteLine("");
        WriteLine("/// <inheritdoc />");
        WriteLine("public global::System.DateTimeOffset? ArchivedOn { get; set; }");
        PopIndent();
        WriteLine("}");

        return ToString();
    }
}