using Majal.Generators;

namespace Majal.Templates;

public class AuditableTemplate : BaseTemplate
{
    public AuditableGenerator.AuditableData Data { get; init; }

    public override string TransformText()
    {
        Clear();
        WriteLine("// <auto-generated />");
        WriteLine("");
        WriteLine("#nullable enable");
        WriteLine("");
        WriteLine(Data.Namespace);
        WriteLine("");
        WriteLine($"public partial class {Data.TypeName} : global::Majal.IAuditable");
        WriteLine("{");
        PushIndent("    ");
        WriteLine("/// <inheritdoc />");
        WriteLine("public System.DateTimeOffset CreatedOn { get; set; }");
        WriteLine("");
        WriteLine("/// <inheritdoc />");
        WriteLine("public System.DateTimeOffset? UpdatedOn { get; set; }");
        PopIndent();
        WriteLine("}");

        return ToString();
    }
}