using static Majal.Abstractions.Constants;

namespace Majal.Templates;

public class AuditableInterceptorTemplate : BaseTemplate
{
    public override string TransformText()
    {
        Clear();
        WriteLine("// <auto-generated />");
        WriteLine("");
        WriteLine("namespace Majal;");
        WriteLine("");
        WriteLine("#nullable enable");
        WriteLine("");
        WriteLine($"public class AuditableSaveChangesInterceptor : {EfCoreDiagnosticsNamespace}.SaveChangesInterceptor");
        WriteLine("{");
        PushIndent();
        WriteLine($"public override {EfCoreDiagnosticsNamespace}.InterceptionResult<{IntType}> SavingChanges(");
        WriteLine($"    {EfCoreDiagnosticsNamespace}.DbContextEventData eventData,");
        WriteLine($"    {EfCoreDiagnosticsNamespace}.InterceptionResult<{IntType}> result)");
        WriteLine("{");
        PushIndent();
        WriteLine("if (eventData.Context is null)");
        WriteLine("    return base.SavingChanges(eventData, result);");
        WriteLine("");
        WriteLine("UpdateAuditableEntities(eventData.Context!);");
        WriteLine("");
        WriteLine("return base.SavingChanges(eventData, result);");
        PopIndent();
        WriteLine("}");
        WriteLine("");
        WriteLine(
            $"public override {TasksNamespace}.ValueTask<{EfCoreDiagnosticsNamespace}.InterceptionResult<{IntType}>> SavingChangesAsync(");
        WriteLine($"    {EfCoreDiagnosticsNamespace}.DbContextEventData eventData,");
        WriteLine($"    {EfCoreDiagnosticsNamespace}.InterceptionResult<{IntType}> result,");
        WriteLine("    global::System.Threading.CancellationToken ct)");
        WriteLine("{");
        PushIndent();
        WriteLine("if (eventData.Context is null)");
        WriteLine("    return base.SavingChangesAsync(eventData, result, ct);");
        WriteLine("");
        WriteLine("UpdateAuditableEntities(eventData.Context!);");
        WriteLine("");
        WriteLine("return base.SavingChangesAsync(eventData, result, ct);");
        PopIndent();
        WriteLine("}");
        WriteLine("");
        WriteLine($"private static void UpdateAuditableEntities({EfCoreNamespace}.DbContext context)");
        WriteLine("{");
        PushIndent();
        WriteLine("var entries = context.ChangeTracker");
        WriteLine($"    .Entries<{MajalNamespace}.IAuditable>()");
        WriteLine(
            $"    .Where(e => e.State is {EfCoreNamespace}.EntityState.Added or {EfCoreNamespace}.EntityState.Modified);");
        WriteLine("");
        WriteLine("foreach (var entry in entries)");
        WriteLine("{");
        PushIndent();
        WriteLine($"if (entry.Entity is {MajalNamespace}.IAuditable entity)");
        WriteLine("{");
        PushIndent();
        WriteLine($"if (entry.State == {EfCoreNamespace}.EntityState.Added)");
        WriteLine("{");
        PushIndent();
        WriteLine($"entity.CreatedOn = {SystemNamespace}.DateTimeOffset.UtcNow;");
        PopIndent();
        WriteLine("}");
        WriteLine($"else if (entry.State == {EfCoreNamespace}.EntityState.Modified)");
        WriteLine("{");
        PushIndent();
        WriteLine($"entity.UpdatedOn = {SystemNamespace}.DateTimeOffset.UtcNow;");
        PopIndent();
        WriteLine("}");
        PopIndent();
        WriteLine("}");
        PopIndent();
        WriteLine("}");
        PopIndent();
        WriteLine("}");
        PopIndent();
        WriteLine("}");

        return ToString();
    }
}