using static Majal.Abstractions.Constants;

using Majal.Generators;

namespace Majal.Templates;

public class AuditableTemplate : BaseTemplate
{
    public AuditableGenerator.AuditableData Data { get; init; }

    public override string TransformText()
    {
        Clear();
        WriteLine("// <auto-generated />");
        WriteLine("");
        WriteLine("#nullable enable");
        WriteLine("");
        WriteLine(Data.Namespace);
        WriteLine("");
        WriteLine("/// <summary>");
        WriteLine($"/// Provides auditing timestamps for <see cref=\"{Data.TypeName}\"/>.");
        WriteLine("/// </summary>");
        WriteLine($"public partial class {Data.TypeName} : {MajalNamespace}.IAuditable");
        WriteLine("{");
        PushIndent();
        WriteLine("/// <inheritdoc />");
        WriteLine($"public {SystemNamespace}.DateTimeOffset CreatedOn {{ get; set; }}");
        WriteLine("");
        WriteLine("/// <inheritdoc />");
        WriteLine($"public {SystemNamespace}.DateTimeOffset? UpdatedOn {{ get; set; }}");
        PopIndent();
        WriteLine("}");

        return ToString();
    }
}