using Majal.Abstractions;
using Majal.Generators;

namespace Majal.Templates;

public class DtoTemplate : BaseTemplate
{
    public DtoGenerator.DtoData Data { get; init; }

    public override string TransformText()
    {
        Clear();

        WriteLine("// <auto-generated />");
        WriteLine("");
        WriteLine("#nullable enable");
        WriteLine("");
        WriteLine(Data.Namespace);
        WriteLine("");

        GenerateDto(Data, false);

        return ToString();
    }

    private void GenerateDto(DtoGenerator.DtoData dto, bool isNested)
    {
        var typeKeyword = dto.IsRecord ? "record" : "class";

        if (!string.IsNullOrWhiteSpace(dto.XmlDocs))
        {
            WriteLine(dto.XmlDocs!);
        }

        if (dto.DerivedTypes.Count > 0)
        {
            WriteLine("[global::System.Text.Json.Serialization.JsonPolymorphic]");
            foreach (var dt in dto.DerivedTypes)
            {
                Write($"[{Constants.JsonSerializationNamespace}.JsonDerivedType(typeof({dt.DtoName})");
                WriteLine($""", typeDiscriminator: "{ToSnakeCase(dt.Discriminator)}")]""");
            }
        }

        var isBase = isNested && dto.DerivedTypes.Count > 0 && string.IsNullOrWhiteSpace(dto.BaseDtoName);
        var inheritance = string.IsNullOrWhiteSpace(dto.BaseDtoName) ? "" : $" : {dto.BaseDtoName}";
        var modifer = isBase ? "abstract " : !isNested ? "partial " : "";
        
        WriteLine($"public {modifer}{typeKeyword} {dto.DtoName}{inheritance}");
        WriteLine("{");
        PushIndent();

        foreach (var param in dto.Parameters)
        {
            var propertyName = ToPascalCase(param.Name);
            var requiredKeyword = param.IsNullable ? "" : "required ";
            if (!string.IsNullOrWhiteSpace(param.XmlDocs))
            {
                WriteLine(param.XmlDocs!);
            }

            WriteLine($"public {requiredKeyword}{param.ResolvedType} {propertyName} {{ get; init; }}");
        }

        if (dto.NestedDtos.Count > 0)
        {
            WriteLine("");
            foreach (var nested in dto.NestedDtos)
            {
                GenerateDto(nested, true);
                WriteLine("");
            }
        }

        PopIndent();
        WriteLine("}");
    }

    private static string ToPascalCase(string input)
    {
        if (string.IsNullOrEmpty(input)) return input;
        return char.ToUpperInvariant(input[0]) + input.Substring(1);
    }

    private static string ToSnakeCase(string input)
    {
        if (string.IsNullOrEmpty(input)) return input;
        return char.ToLowerInvariant(input[0]) + input.Substring(1);
    }
}