using Majal.Generators;

namespace Majal.Templates;

public class DtoTemplate : BaseTemplate
{
    public DtoGenerator.DtoData Data { get; init; }

    public override string TransformText()
    {
        Clear();

        WriteLine("// <auto-generated />");
        WriteLine("");
        WriteLine("#nullable enable");
        WriteLine("");
        WriteLine(Data.Namespace);
        WriteLine("");

        GenerateDto(Data);

        return ToString();
    }

    private void GenerateDto(DtoGenerator.DtoData dto)
    {
        var typeKeyword = dto.IsRecord ? "record" : (dto.IsStruct ? "struct" : "class");
        
        if (!string.IsNullOrWhiteSpace(dto.XmlDocs))
        {
            WriteLine(dto.XmlDocs!);
        }

        WriteLine($"public partial {typeKeyword} {dto.DtoName}");
        WriteLine("{");
        PushIndent();

        foreach (var param in dto.Parameters)
        {
            var propertyName = ToPascalCase(param.Name);
            var requiredKeyword = param.IsNullable ? "" : "required ";
            if (!string.IsNullOrWhiteSpace(param.XmlDocs))
            {
                WriteLine(param.XmlDocs!);
            }
            WriteLine($"public {requiredKeyword}{param.ResolvedType} {propertyName} {{ get; init; }}");
        }

        if (dto.NestedDtos.Count > 0)
        {
            WriteLine("");
            foreach (var nested in dto.NestedDtos)
            {
                GenerateDto(nested);
                WriteLine("");
            }
        }

        PopIndent();
        WriteLine("}");
    }

    private static string ToPascalCase(string input)
    {
        if (string.IsNullOrEmpty(input)) return input;
        return char.ToUpperInvariant(input[0]) + input.Substring(1);
    }
}
