using Majal.Generators;
using static Majal.Abstractions.Constants;

namespace Majal.Templates;

public class EntityTemplate(EntityGenerator.EntityData data) : BaseTemplate
{
    public override string TransformText()
    {
        Clear();
        WriteLine("// <auto-generated />");
        WriteLine("");
        WriteLine("#nullable enable");
        WriteLine("");
        WriteLine(data.Namespace);
        WriteLine("");

        string[] interfaces =
        [
            $"{MajalNamespace}.IEntity<{data.IdType}>",
            $"{SystemNamespace}.IComparable",
            $"{SystemNamespace}.IComparable<{data.TypeName}>"
        ];

        WriteLine($"public partial class {data.TypeName} : {string.Join(", ", interfaces)}");
        WriteLine("{");
        PushIndent();

        if (!data.HasConstructor)
        {
            WriteLine($"protected {data.RawTypeName}()");
            WriteLine("{");
            WriteLine("}");
        }

        if (!data.Properties.Contains("Id"))
        {
            WriteLine("/// <inheritdoc />");
            WriteLine($"public {data.IdType} Id {{ get; set; }} = default!;");
        }

        WriteLine("");
        WriteLine($"public override {BoolType} Equals({ObjectType}? obj)");
        WriteLine("{");
        PushIndent();
        WriteLine($"if (obj is not {data.TypeName} other) return false;");
        WriteLine("if (ReferenceEquals(this, other)) return true;");
        WriteLine("if (IsTransient() || other.IsTransient()) return false;");
        WriteLine("return Id.Equals(other.Id);");
        PopIndent();
        WriteLine("}");
        WriteLine("");
        WriteLine($"private {BoolType} IsTransient()");
        WriteLine("{");
        PushIndent();
        WriteLine($"return Id.Equals(default({data.IdType}));");
        PopIndent();
        WriteLine("}");
        WriteLine("");
        WriteLine($"public static {BoolType} operator ==({data.TypeName}? a, {data.TypeName}? b)");
        WriteLine("{");
        PushIndent();
        WriteLine("if (a is null && b is null) return true;");
        WriteLine("if (a is null || b is null) return false;");
        WriteLine("return a.Equals(b);");
        PopIndent();
        WriteLine("}");
        WriteLine("");
        WriteLine($"public static {BoolType} operator !=({data.TypeName}? a, {data.TypeName}? b)");
        WriteLine("{");
        PushIndent();
        WriteLine("return !(a == b);");
        PopIndent();
        WriteLine("}");
        WriteLine("");
        WriteLine($"public override {IntType} GetHashCode()");
        WriteLine("{");
        PushIndent();
        WriteLine("return (GetType().ToString() + Id).GetHashCode();");
        PopIndent();
        WriteLine("}");
        WriteLine("");
        WriteLine($"public {IntType} CompareTo({data.TypeName}? other)");
        WriteLine("{");
        PushIndent();
        WriteLine("if (other is null) return 1;");
        WriteLine("if (ReferenceEquals(this, other)) return 0;");
        WriteLine("return Id.CompareTo(other.Id);");
        PopIndent();
        WriteLine("}");
        WriteLine("");
        WriteLine("/// <inheritdoc />");
        WriteLine($"public {IntType} CompareTo({ObjectType}? other)");
        WriteLine("{");
        PushIndent();
        WriteLine($"return CompareTo(other as {data.TypeName});");
        PopIndent();
        WriteLine("}");

        PopIndent();
        WriteLine("}");

        return ToString();
    }
}