using Majal.Generators;

namespace Majal.Templates;

public class EntityTemplate : BaseTemplate
{
    public EntityGenerator.EntityData Data { get; init; }

    public override string TransformText()
    {
        Clear();
        WriteLine("// <auto-generated />");
        WriteLine("");
        WriteLine("#nullable enable");
        WriteLine("");
        WriteLine(Data.Namespace);
        WriteLine("");

        string[] interfaces =
        [
            $"global::Majal.IEntity<{Data.IdType}>",
            "global::System.IComparable",
            $"global::System.IComparable<{Data.TypeName}>"
        ];

        WriteLine($"public partial class {Data.TypeName} : {string.Join(", ", interfaces)}");
        WriteLine("{");
        PushIndent("    ");

        if (!Data.HasConstructor)
        {
            WriteLine($"private {Data.TypeName}()");
            WriteLine("{");
            WriteLine("}");
        }

        if (!Data.Properties.Contains("Id"))
        {
            WriteLine("/// <inheritdoc />");
            WriteLine($"public {Data.IdType} Id {{ get; set; }} = default!;");
        }

        WriteLine("");
        WriteLine("public override global::System.Boolean Equals(object? obj)");
        WriteLine("{");
        PushIndent("    ");
        WriteLine($"if (obj is not {Data.TypeName} other) return false;");
        WriteLine("if (ReferenceEquals(this, other)) return true;");
        WriteLine("if (IsTransient() || other.IsTransient()) return false;");
        WriteLine("return Id.Equals(other.Id);");
        PopIndent();
        WriteLine("}");
        WriteLine("");
        WriteLine("private global::System.Boolean IsTransient()");
        WriteLine("{");
        PushIndent("    ");
        WriteLine($"return Id.Equals(default({Data.IdType}));");
        PopIndent();
        WriteLine("}");
        WriteLine("");
        WriteLine($"public static global::System.Boolean operator ==({Data.TypeName}? a, {Data.TypeName}? b)");
        WriteLine("{");
        PushIndent("    ");
        WriteLine("if (a is null && b is null) return true;");
        WriteLine("if (a is null || b is null) return false;");
        WriteLine("return a.Equals(b);");
        PopIndent();
        WriteLine("}");
        WriteLine("");
        WriteLine($"public static global::System.Boolean operator !=({Data.TypeName}? a, {Data.TypeName}? b)");
        WriteLine("{");
        PushIndent("    ");
        WriteLine("return !(a == b);");
        PopIndent();
        WriteLine("}");
        WriteLine("");
        WriteLine("public override global::System.Int32 GetHashCode()");
        WriteLine("{");
        PushIndent("    ");
        WriteLine("return (GetType().ToString() + Id).GetHashCode();");
        PopIndent();
        WriteLine("}");
        WriteLine("");
        WriteLine($"public global::System.Int32 CompareTo({Data.TypeName}? other)");
        WriteLine("{");
        PushIndent("    ");
        WriteLine("if (other is null) return 1;");
        WriteLine("if (ReferenceEquals(this, other)) return 0;");
        WriteLine("return Id.CompareTo(other.Id);");
        PopIndent();
        WriteLine("}");
        WriteLine("");
        WriteLine("/// <inheritdoc />");
        WriteLine("public global::System.Int32 CompareTo(global::System.Object? other)");
        WriteLine("{");
        PushIndent("    ");
        WriteLine($"return CompareTo(other as {Data.TypeName});");
        PopIndent();
        WriteLine("}");

        PopIndent();
        WriteLine("}");

        return ToString();
    }
}