using Majal.Generators;
using static Majal.Abstractions.Constants;

namespace Majal.Templates;

public class EntityTemplate : BaseTemplate
{
    public EntityGenerator.EntityData Data { get; init; }

    public override string TransformText()
    {
        Clear();
        WriteLine("// <auto-generated />");
        WriteLine("");
        WriteLine("#nullable enable");
        WriteLine("");
        WriteLine(Data.Namespace);
        WriteLine("");

        string[] interfaces =
        [
            $"{MajalNamespace}.IEntity<{Data.IdType}>",
            $"{SystemNamespace}.IComparable",
            $"{SystemNamespace}.IComparable<{Data.TypeName}>"
        ];

        WriteLine($"public partial class {Data.TypeName} : {string.Join(", ", interfaces)}");
        WriteLine("{");
        PushIndent();

        if (!Data.HasConstructor)
        {
            WriteLine($"private {Data.TypeName}()");
            WriteLine("{");
            WriteLine("}");
        }

        if (!Data.Properties.Contains("Id"))
        {
            WriteLine("/// <inheritdoc />");
            WriteLine($"public {Data.IdType} Id {{ get; set; }} = default!;");
        }

        WriteLine("");
        WriteLine($"public override {BoolType} Equals({ObjectType}? obj)");
        WriteLine("{");
        PushIndent();
        WriteLine($"if (obj is not {Data.TypeName} other) return false;");
        WriteLine("if (ReferenceEquals(this, other)) return true;");
        WriteLine("if (IsTransient() || other.IsTransient()) return false;");
        WriteLine("return Id.Equals(other.Id);");
        PopIndent();
        WriteLine("}");
        WriteLine("");
        WriteLine($"private {BoolType} IsTransient()");
        WriteLine("{");
        PushIndent();
        WriteLine($"return Id.Equals(default({Data.IdType}));");
        PopIndent();
        WriteLine("}");
        WriteLine("");
        WriteLine($"public static {BoolType} operator ==({Data.TypeName}? a, {Data.TypeName}? b)");
        WriteLine("{");
        PushIndent();
        WriteLine("if (a is null && b is null) return true;");
        WriteLine("if (a is null || b is null) return false;");
        WriteLine("return a.Equals(b);");
        PopIndent();
        WriteLine("}");
        WriteLine("");
        WriteLine($"public static {BoolType} operator !=({Data.TypeName}? a, {Data.TypeName}? b)");
        WriteLine("{");
        PushIndent();
        WriteLine("return !(a == b);");
        PopIndent();
        WriteLine("}");
        WriteLine("");
        WriteLine($"public override {IntType} GetHashCode()");
        WriteLine("{");
        PushIndent();
        WriteLine("return (GetType().ToString() + Id).GetHashCode();");
        PopIndent();
        WriteLine("}");
        WriteLine("");
        WriteLine($"public {IntType} CompareTo({Data.TypeName}? other)");
        WriteLine("{");
        PushIndent();
        WriteLine("if (other is null) return 1;");
        WriteLine("if (ReferenceEquals(this, other)) return 0;");
        WriteLine("return Id.CompareTo(other.Id);");
        PopIndent();
        WriteLine("}");
        WriteLine("");
        WriteLine("/// <inheritdoc />");
        WriteLine($"public {IntType} CompareTo({ObjectType}? other)");
        WriteLine("{");
        PushIndent();
        WriteLine($"return CompareTo(other as {Data.TypeName});");
        PopIndent();
        WriteLine("}");

        PopIndent();
        WriteLine("}");

        return ToString();
    }
}