using static Majal.Abstractions.Constants;
using Majal.Generators;

namespace Majal.Templates;

public class OrdinalTemplate : BaseTemplate
{
    public OrdinalGenerator.OrdinalData Data { get; init; }

    public override string TransformText()
    {
        Clear();
        WriteLine("// <auto-generated />");
        WriteLine("");
        WriteLine("#nullable enable");
        WriteLine("");
        WriteLine(Data.Namespace);
        WriteLine("");
        WriteLine("/// <summary>");
        WriteLine($"/// Provides ordinal ordering support for <see cref=\"{Data.TypeName}\"/>.");
        WriteLine("/// </summary>");
        WriteLine($"public partial class {Data.TypeName} : {MajalNamespace}.IOrdinal");
        WriteLine("{");
        PushIndent();
        WriteLine("/// <inheritdoc />");
        WriteLine($"public required {UIntType} Ordinal {{ get; set; }}");
        PopIndent();
        WriteLine("}");

        return ToString();
    }
}