using Majal.Generators;

namespace Majal.Templates;

public class OrdinalTemplate : BaseTemplate
{
    public OrdinalGenerator.OrdinalData Data { get; init; } 

    public override string TransformText()
    {
        Clear();
        WriteLine("// <auto-generated />");
        WriteLine("");
        WriteLine("#nullable enable");
        WriteLine("");
        WriteLine(Data.Namespace);
        WriteLine("");
        WriteLine($"public partial class {Data.TypeName} : global::Majal.IOrdinal");
        WriteLine("{");
        PushIndent("    ");
        WriteLine("/// <inheritdoc />");
        WriteLine("public required global::System.UInt32 Ordinal { get; set; }");
        PopIndent();
        WriteLine("}");

        return ToString();
    }
}
