namespace Majal.Templates;

public class TranslatableConventionTemplate : BaseTemplate
{
    private const string MajalNamespace = "global::Majal";
    
    private const string ExpressionsNamespace = "global::System.Linq.Expressions";
    private const string ExpressionsType = $"{ExpressionsNamespace}.Expression";

    private const string EfCoreNamespace = "global::Microsoft.EntityFrameworkCore";
    private const string EfCoreBuilders = $"{EfCoreNamespace}.Metadata.Builders";
    private const string EfCoreConventions = $"{EfCoreNamespace}.Metadata.Conventions";

    public override string TransformText()
    {
        Clear();
        WriteLine("// <auto-generated />");
        WriteLine("");
        WriteLine("namespace Majal;");
        WriteLine("");
        WriteLine("#nullable enable");
        WriteLine("");
        WriteLine("public class TranslatableConvention<TContext>(TContext dbContext)");
        WriteLine($"    : {EfCoreConventions}.IModelFinalizingConvention");
        WriteLine($"    where TContext : {EfCoreNamespace}.DbContext, {MajalNamespace}.ITranslatableDbContext");
        WriteLine("{");
        PushIndent("    ");
        WriteLine("public void ProcessModelFinalizing(");
        WriteLine($"    {EfCoreBuilders}.IConventionModelBuilder modelBuilder,");
        WriteLine($"    {EfCoreConventions}.IConventionContext<{EfCoreBuilders}.IConventionModelBuilder> context)");
        WriteLine("{");
        PushIndent("    ");
        WriteLine("foreach (var entityType in modelBuilder.Metadata.GetEntityTypes())");
        WriteLine("{");
        PushIndent("    ");
        WriteLine("// Check if the entity implements ITranslatable");
        WriteLine($"if (!typeof({MajalNamespace}.ITranslatable).IsAssignableFrom(entityType.ClrType)) continue;");
        WriteLine("");
        WriteLine("// Equivalent to: t => t.Locale");
        WriteLine($"""var parameter = {ExpressionsType}.Parameter(entityType.ClrType, "t");""");
        WriteLine($"var property = {ExpressionsType}.Property(parameter, ");
        WriteLine($"    nameof({MajalNamespace}.ITranslatable.Locale));");
        WriteLine("");
        WriteLine("// dbContext.CurrentLocale");
        WriteLine($"var dbContextExpr = {ExpressionsType}.Constant(dbContext);");
        WriteLine($"var currentLocale = {ExpressionsType}.Property(dbContextExpr, ");
        WriteLine($"    nameof({MajalNamespace}.ITranslatableDbContext.CurrentLocale));");
        WriteLine("");
        WriteLine($"var body = {ExpressionsType}.Equal(property, currentLocale);");
        WriteLine($"var lambda ={ExpressionsType}.Lambda(body, parameter);");
        WriteLine("");
        WriteLine("// Set the query filter");
        WriteLine("entityType.SetQueryFilter(lambda);");
        PopIndent();
        WriteLine("}");
        PopIndent();
        WriteLine("}");
        PopIndent();
        WriteLine("}");

        return ToString();
    }
}