using static Majal.Abstractions.Constants;

namespace Majal.Templates;

public class TranslatableConventionTemplate : BaseTemplate
{
    public override string TransformText()
    {
        Clear();
        WriteLine("// <auto-generated />");
        WriteLine("");
        WriteLine("namespace Majal;");
        WriteLine("");
        WriteLine("#nullable enable");
        WriteLine("");
        WriteLine("public class TranslatableFilterConvention<TLocale,TContext>(TContext dbContext)");
        WriteLine($"    : {EfCoreConventions}.IModelFinalizingConvention");
        WriteLine($"    where TContext : {EfCoreNamespace}.DbContext, {MajalNamespace}.ITranslatableDbContext<TLocale>");
        WriteLine("{");
        PushIndent();
        WriteLine("public void ProcessModelFinalizing(");
        WriteLine($"    {EfCoreBuilders}.IConventionModelBuilder modelBuilder,");
        WriteLine($"    {EfCoreConventions}.IConventionContext<{EfCoreBuilders}.IConventionModelBuilder> context)");
        WriteLine("{");
        PushIndent();
        WriteLine("foreach (var entityType in modelBuilder.Metadata.GetEntityTypes())");
        WriteLine("{");
        PushIndent();
        WriteLine("// Check if the entity implements ITranslatable");
        WriteLine($"if (!typeof({MajalNamespace}.ITranslatable<TLocale>).IsAssignableFrom(entityType.ClrType)) continue;");
        WriteLine("");
        WriteLine("// If it's a derived type and its base type also implements ITranslatable, skip it");
        WriteLine("// because the filter should be applied to the root of the hierarchy.");
        WriteLine("if (entityType.BaseType != null && ");
        WriteLine($"        typeof({MajalNamespace}.ITranslatable<TLocale>)");
        WriteLine("             .IsAssignableFrom(entityType.BaseType.ClrType)) continue;");
        WriteLine("");
        WriteLine("// Equivalent to: t => t.Locale");
        WriteLine($"""var parameter = {ExpressionsType}.Parameter(entityType.ClrType, "t");""");
        WriteLine($"var property = {ExpressionsType}.Property(parameter, ");
        WriteLine($"    nameof({MajalNamespace}.ITranslatable<>.Locale));");
        WriteLine("");
        WriteLine("// dbContext.CurrentLocale");
        WriteLine($"var dbContextExpr = {ExpressionsType}.Constant(dbContext);");
        WriteLine($"var currentLocale = {ExpressionsType}.Property(dbContextExpr, ");
        WriteLine($"    nameof({MajalNamespace}.ITranslatableDbContext<>.Locale));");
        WriteLine("");
        WriteLine($"var body = {ExpressionsType}.Equal(property, currentLocale);");
        WriteLine($"var lambda = {ExpressionsType}.Lambda(body, parameter);");
        WriteLine("");
        WriteLine("// Set the query filter");
        WriteLine("entityType.SetQueryFilter(nameof(ITranslatable<>), lambda);");
        PopIndent();
        WriteLine("}");
        PopIndent();
        WriteLine("}");
        PopIndent();
        WriteLine("}");
        WriteLine("");

        WriteLine("public static class TranslatableEfCoreExtensions");
        WriteLine("{");
        PushIndent();
        WriteLine($"public static {LinqNamespace}.IQueryable<TEntity> IgnoreTranslatableFilter<TEntity>(");
        WriteLine($"    this {LinqNamespace}.IQueryable<TEntity> source)");
        WriteLine("             where TEntity : class");
        WriteLine("{");
        PushIndent();
        WriteLine($"return {EfCoreNamespace}.EntityFrameworkQueryableExtensions");
        WriteLine($"    .IgnoreQueryFilters(source, [nameof({MajalNamespace}.ITranslatable<> )]);");
        PopIndent();
        WriteLine("}");
        PopIndent();
        WriteLine("}");

        return ToString();
    }
}