using Majal.Generators;

namespace Majal.Templates;

public class TranslatableTemplate : BaseTemplate
{
    public TranslatableGenerator.TranslatableData Data { get; init; }
    
    public override string TransformText()
    {
        Clear();
        WriteLine("// <auto-generated />");
        WriteLine("");
        WriteLine("#nullable enable");
        WriteLine("");
        WriteLine(Data.Namespace);
        WriteLine("");
        WriteLine($"public partial class {Data.TypeName} : global::Majal.ITranslatable");
        WriteLine("{");
        PushIndent("    ");
        WriteLine("/// <inheritdoc />");
        WriteLine("public required string Locale { get; set; }");
        PopIndent();
        WriteLine("}");

        return ToString();
    }
}