using Majal.Generators;
using static Majal.Abstractions.Constants;

namespace Majal.Templates;

public class ValueObjectConfigurationTemplate(ValueObjectGenerator.ValueObjectData[] valueObjects) : BaseTemplate
{
    public override string TransformText()
    {
        Clear();
        WriteLine("// <auto-generated />");
        WriteLine("");
        WriteLine("namespace Majal;");
        WriteLine("");
        WriteLine("#nullable enable");
        WriteLine("");
        WriteLine("/// <summary>Provides EF Core model-configuration extensions for source-generated value objects.</summary>");
        WriteLine("public static class ValueObjectExtensions");
        WriteLine("{");
        PushIndent();
        WriteLine("/// <summary>Registers EF Core scalar-property conventions (conversion and max-length) for all value objects in this assembly.</summary>");
        WriteLine($"public static void RegisterValueObjectsConventions(this {EfCoreNamespace}.ModelConfigurationBuilder config)");
        WriteLine("{");
        PushIndent();

        foreach (var valueObject in valueObjects)
        {
            var @namespace = valueObject.Namespace.Replace("namespace ", "").Replace(";", "");
            var fullTypeName = $"{@namespace}.{valueObject.TypeName}";
            WriteLine($"config.Properties<{fullTypeName}>()");
            PushIndent();
            if (valueObject is { MaxLength: { } maxLength, Value.GenericType: "string" })
            {
                WriteLine($".HaveMaxLength({maxLength})");
            }

            WriteLine($".HaveConversion<{fullTypeName}.{ValueObjectTemplate.EfCoreValueConverterTypeName}>();");
            PopIndent();
            WriteLine("");
        }

        PopIndent();
        WriteLine("}");
        PopIndent();
        WriteLine("}");
        PopIndent();

        return ToString();
    }
}