namespace Majal.Templates;

public class ValueObjectConventionTemplate : BaseTemplate
{
    private const string MajalNamespace = "global::Majal";

    private const string SystemNamespace = "global::System";

    private const string EfCoreNamespace = "global::Microsoft.EntityFrameworkCore";
    private const string EfCoreBuilders = $"{EfCoreNamespace}.Metadata.Builders";
    private const string EfCoreConventions = $"{EfCoreNamespace}.Metadata.Conventions";
    private const string EfCoreValueConversion = $"{EfCoreNamespace}.Storage.ValueConversion";

    public override string TransformText()
    {
        Clear();
        WriteLine("// <auto-generated />");
        WriteLine("");
        WriteLine("namespace Majal;");
        WriteLine("");
        WriteLine("#nullable enable");
        WriteLine("");
        WriteLine($"public class ValueObjectConvention : {EfCoreConventions}.IModelFinalizingConvention");
        WriteLine("{");
        PushIndent("    ");
        WriteLine("public void ProcessModelFinalizing(");
        WriteLine($"    {EfCoreBuilders}.IConventionModelBuilder modelBuilder,");
        WriteLine($"    {EfCoreConventions}.IConventionContext<{EfCoreBuilders}.IConventionModelBuilder> context)");
        WriteLine("{");
        PushIndent("    ");
        WriteLine("foreach (var entityType in modelBuilder.Metadata.GetEntityTypes())");
        WriteLine("{");
        PushIndent("    ");
        WriteLine("foreach (var property in entityType.GetProperties())");
        WriteLine("{");
        PushIndent("    ");
        WriteLine("var clrType = property.ClrType;");
        WriteLine(" // 1. Check if the entityType type has the ValueObjectAttribute<T>");

        WriteLine("var valueObjectAttr = clrType");
        WriteLine($" .GetCustomAttributes(typeof({MajalNamespace}.ValueObjectAttribute<>), false)");
        WriteLine(" .FirstOrDefault(a =>");
        WriteLine("     a.GetType().IsGenericType &&");
        WriteLine($"     a.GetType().GetGenericTypeDefinition() == typeof({MajalNamespace}.ValueObjectAttribute<>));");

        WriteLine("");
        WriteLine("if (valueObjectAttr == null) continue;");
        WriteLine("");

        WriteLine(" // 2. Find the nested class inheriting from ValueConverter<clrType, ?>");
        WriteLine("var converterType = clrType");
        WriteLine(" .GetNestedTypes()");
        WriteLine(" .FirstOrDefault(t =>");
        WriteLine("     t.BaseType is { IsGenericType: true } &&");
        WriteLine("     t.BaseType.GetGenericTypeDefinition() ==");
        WriteLine($"     typeof({EfCoreValueConversion}.ValueConverter<,>) &&");
        WriteLine("     t.BaseType.GetGenericArguments()[0] == clrType");
        WriteLine(" );");
        WriteLine("");

        WriteLine("if (converterType == null) continue;");
        WriteLine("");
        WriteLine(" // 3. Apply the converter to the entityType");
        WriteLine("property.SetValueConverter(");
        WriteLine($"    ({EfCoreValueConversion}.ValueConverter)");
        WriteLine($"{SystemNamespace}.Activator.CreateInstance(converterType)!);");
        WriteLine("");
        PopIndent();
        WriteLine("}");
        PopIndent();
        WriteLine("}");
        PopIndent();
        WriteLine("}");
        PopIndent();
        WriteLine("}");
        PopIndent();

        return ToString();
    }
}