using Majal.Generators;
using static Majal.Abstractions.Constants;

namespace Majal.Templates;

public class ValueObjectTemplate : BaseTemplate
{
    public bool EnableEfCore { get; init; }
    public ValueObjectGenerator.ValueObjectData Data { get; init; }

    public const string FactoryMethodName = "Create";

    public override string TransformText()
    {
        Clear();
        
        WriteLine("// <auto-generated />");
        WriteLine("");
        WriteLine("#nullable enable");
        WriteLine("");
        WriteLine(Data.Namespace);
        WriteLine("");

        string[] interfaces =
        [
            Data.IsGeneric ? $"{MajalNamespace}.IValueObject<{Data.ValueType}>" : $"{MajalNamespace}.IValueObject",
            $"{SystemNamespace}.IEquatable<{Data.TypeName}>",
            $"{SystemNamespace}.IComparable",
            $"{SystemNamespace}.IComparable<{Data.TypeName}>",
        ];

        if (Data.IsGeneric)
        {
            WriteLine($"[{ComponentModelNamespace}.TypeConverterAttribute(typeof({Data.TypeName}.ValueObjectTypeConverter))]");
            WriteLine($"[{JsonSerializationNamespace}.JsonConverterAttribute(typeof({Data.TypeName}.JsonValueConverter))]");
        }

        WriteLine($"public partial struct {Data.TypeName} : {string.Join(", ", interfaces)}");
        WriteLine("{");
        PushIndent();

        if (Data.IsGeneric)
        {
            if (EnableEfCore)
            {
                WriteLine("public sealed class EFCoreValueConverter :");
                WriteLine($"    {EfCoreValueConversion}.ValueConverter<{Data.TypeName}, {Data.ValueType}>");
                WriteLine("{");
                PushIndent();
                WriteLine($"public EFCoreValueConverter() : base(v => v.Value, v => {FactoryMethodName}(v))");
                WriteLine("{");
                WriteLine("}");
                PopIndent();
                WriteLine("}");
                WriteLine("");
            }

            WriteLine("public sealed class ValueObjectTypeConverter : ");
            PushIndent();
            WriteLine($"{ComponentModelNamespace}.TypeConverter");
            PopIndent();
            WriteLine("{");
            PushIndent();
            WriteLine($"public override {BoolType} CanConvertFrom(");
            PushIndent();
            WriteLine($"{ComponentModelNamespace}.ITypeDescriptorContext? context,");
            WriteLine($"{TypeType} sourceType) =>");
            WriteLine("    sourceType == typeof(string) || base.CanConvertFrom(context, sourceType);");
            WriteLine("");
            PopIndent();

            WriteLine($"public override {ObjectType}? ConvertFrom(");
            PushIndent();
            WriteLine($"{ComponentModelNamespace}.ITypeDescriptorContext? context,");
            WriteLine($"{GlobalizationNamespace}.CultureInfo? culture,");
            WriteLine($"{ObjectType} value) =>");
            WriteLine($"    value is string s ? {Data.TypeName}.Parse(s) : base.ConvertFrom(context, culture, value);");
            PopIndent();
            PopIndent();
            WriteLine("}");
            WriteLine("");

            WriteLine("public sealed class JsonValueConverter :");
            WriteLine($"    {JsonSerializationNamespace}.JsonConverter<{Data.TypeName}>");
            WriteLine("{");
            PushIndent();
            WriteLine("");
            WriteLine($"public override {Data.TypeName} Read(");
            PushIndent();
            WriteLine($"ref {JsonNamespace}.Utf8JsonReader reader,");
            WriteLine($"{TypeType} typeToConvert,");
            WriteLine($"{JsonNamespace}.JsonSerializerOptions options) =>");
            WriteLine($"     {Data.TypeName}.Parse(reader.GetString()!);");
            PopIndent();

            WriteLine("");
            WriteLine("public override void Write(");
            PushIndent();
            WriteLine($"{JsonNamespace}.Utf8JsonWriter writer,");
            WriteLine($"{Data.TypeName} value,");
            WriteLine($"{JsonNamespace}.JsonSerializerOptions options) =>");
            WriteLine("     writer.WriteStringValue(value.ToString());");
            PopIndent();

            PopIndent();
            WriteLine("}");
            WriteLine("");
            WriteLine("");

            WriteLine($"public required {Data.ValueType} Value {{ get; init; }}");
            WriteLine("");

            if (!Data.HasCreateMethod)
            {
                WriteLine($"public static {Data.TypeName} {FactoryMethodName}({Data.ValueType} value)");
                WriteLine("{");
                PushIndent();
                WriteLine($"return new {Data.TypeName}()");
                WriteLine("{");
                PushIndent();
                WriteLine("Value = value");
                PopIndent();
                WriteLine("};");
                PopIndent();
                WriteLine("}");
                WriteLine("");
            }

            WriteLine($"private static {Data.TypeName} Parse({StringType} value)");
            WriteLine("{");
            PushIndent();
            WriteLine("string".Equals(Data.ValueType, StringComparison.OrdinalIgnoreCase)
                ? $"return {FactoryMethodName}(value);"
                : $"return {FactoryMethodName}({Data.ValueType}.Parse(value));");
            PopIndent();
            WriteLine("}");
            WriteLine("");

            WriteLine($"public static explicit operator {Data.ValueType}({Data.TypeName} valueObject) => ");
            PushIndent();
            WriteLine("valueObject.Value;");
            PopIndent();

            WriteLine("");

            WriteLine($"public static explicit operator {Data.TypeName}({Data.ValueType} value) => Create(value);");
            WriteLine("");

            if (!Data.HasToStringMethod)
            {
                WriteLine($"public override {StringType} ToString()");
                WriteLine("{");
                PushIndent();
                WriteLine("return Value.ToString();");
                PopIndent();
                WriteLine("}");
                WriteLine("");
            }

            WriteLine($"private {Data.ValueType} GetEqualityComponents() => Value;");
        }

        WriteLine("");

        if (Data.Properties.Count > 0)
        {
            WriteLine(Data.Properties.Count == 1
                ? $"private partial {Data.Properties[0].Type} GetEqualityComponents();"
                : $"private partial ({string.Join(", ", Data.Properties.Select(p => p.Type))}) GetEqualityComponents();");

            WriteLine("");

            var createArgs = string.Join(", ", Data.Properties.Select(p => $"{p.Type} {ToCamelCase(p.Name)}"));
            WriteLine($"public static partial {Data.TypeName} Create({createArgs});");
            WriteLine("");

            if (!Data.HasToStringMethod)
            {
                WriteLine($"public override {StringType} ToString()");
                WriteLine("{");
                PushIndent();
                WriteLine($"var sb = new {SystemNamespace}.Text.StringBuilder();");
                WriteLine("""sb.Append("{ ");""");
                for (var i = 0; i < Data.Properties.Count; i++)
                {
                    var prop = Data.Properties[i];
                    Write($$"""sb.Append($"{{prop.Name}} = { {{prop.Name}} }");""");
                    if (i < Data.Properties.Count - 1) Write(""" sb.Append(", "); """);
                    WriteLine("");
                }

                WriteLine("""sb.Append(" }");""");
                WriteLine("return sb.ToString();");
                PopIndent();
                WriteLine("}");
            }
        }


        WriteLine("");

        WriteLine($"public {IntType} CompareTo({Data.TypeName} other) => ");
        PushIndent();
        WriteLine("this.GetEqualityComponents().CompareTo(other.GetEqualityComponents());");
        PopIndent();
        WriteLine("");

        WriteLine($"public {IntType} CompareTo({ObjectType}? other) => ");
        PushIndent();
        WriteLine($"this.CompareTo(({Data.TypeName}?)other);");
        PopIndent();
        WriteLine("");

        WriteLine($"public {BoolType} Equals({Data.TypeName} other) =>");
        PushIndent();
        WriteLine("this.GetEqualityComponents().Equals(other.GetEqualityComponents());");
        PopIndent();
        WriteLine("");

        WriteLine($"public override {BoolType} Equals({ObjectType}? obj) => ");
        PushIndent();
        WriteLine($"obj is {Data.TypeName} other && Equals(({Data.TypeName})other);");
        PopIndent();
        WriteLine("");

        WriteLine($"public static {BoolType} operator ==({Data.TypeName} left, {Data.TypeName} right) => ");
        PushIndent();
        WriteLine("left.Equals(right);");
        PopIndent();
        WriteLine("");

        WriteLine($"public static {BoolType} operator !=({Data.TypeName} left, {Data.TypeName} right) =>");
        PushIndent();
        WriteLine("!left.Equals(right);");
        PopIndent();
        WriteLine("");

        WriteLine($"public static {BoolType} operator <({Data.TypeName} left, {Data.TypeName} right) => ");
        PushIndent();
        WriteLine("left.CompareTo(right) < 0;");
        PopIndent();
        WriteLine("");

        WriteLine($"public static {BoolType} operator >({Data.TypeName} left, {Data.TypeName} right) =>");
        PushIndent();
        WriteLine("left.CompareTo(right) > 0;");
        PopIndent();
        WriteLine("");

        WriteLine($"public override {IntType} GetHashCode() => ");
        PushIndent();
        WriteLine("this.GetEqualityComponents().GetHashCode();");
        PopIndent();
        WriteLine("");

        PopIndent();
        WriteLine("}");

        return ToString();
    }

    private static string ToCamelCase(string str)
    {
        if (string.IsNullOrEmpty(str)) return str;
        return char.ToLower(str[0]) + str.Substring(1);
    }
}