using Majal.Common.Abstractions;
using Microsoft.CodeAnalysis;
using static Majal.Common.Abstractions.Constants;

namespace Majal.Generators.Dtos;

public class DtoForTemplate : BaseTemplate
{
    public DtoForGenerator.DtoData Data { get; init; }

    public override string TransformText()
    {
        Clear();

        WriteLine("// <auto-generated />");
        WriteLine("");
        WriteLine("#nullable enable");
        WriteLine("");
        WriteLine(Data.Namespace);
        WriteLine("");

        if (Data.ParentTypeDeclarations.Count > 0)
        {
            foreach (var declaration in Data.ParentTypeDeclarations)
            {
                WriteLine(declaration);
                WriteLine("{");
                PushIndent();
            }

            GenerateDto(Data, false);

            for (var i = 0; i < Data.ParentTypeDeclarations.Count; i++)
            {
                PopIndent();
                WriteLine("}");
            }
        }
        else
        {
            GenerateDto(Data, false);
        }

        return ToString();
    }

    private void GenerateDto(DtoForGenerator.DtoData dto, bool isNested)
    {
        var typeKeyword = dto.IsRecord ? "record" : "class";

        if (!string.IsNullOrWhiteSpace(dto.XmlDocs))
        {
            WriteLine(dto.XmlDocs!);
        }

        if (dto.DerivedTypes.Count > 0)
        {
            Write($"[{JsonSerializationNamespace}.JsonPolymorphic(UnknownDerivedTypeHandling = ");
            WriteLine($"{JsonSerializationNamespace}.JsonUnknownDerivedTypeHandling.FailSerialization)]");

            foreach (var dt in dto.DerivedTypes)
            {
                Write($"[{JsonSerializationNamespace}.JsonDerivedType(typeof({dt.DtoName})");
                WriteLine($""", typeDiscriminator: "{ToSnakeCase(dt.Discriminator)}")]""");
            }
        }

        var isBase = dto.DerivedTypes.Count > 0 && string.IsNullOrWhiteSpace(dto.BaseDtoName);
        var inheritance = string.IsNullOrWhiteSpace(dto.BaseDtoName) ? "" : $" : {dto.BaseDtoName}";
        var modifier = "partial ";

        if (isBase) modifier = "abstract " + modifier;

        var accessModifier = dto.Accessibility switch
        {
            Accessibility.Private => "private",
            Accessibility.Internal => "internal",
            Accessibility.Protected => "protected",
            _ => "public"
        };

        WriteLine($"{accessModifier} {modifier}{typeKeyword} {dto.DtoName}{inheritance}");
        WriteLine("{");
        PushIndent();

        foreach (var param in dto.Parameters)
        {
            var propertyName = ToPascalCase(param.Name);
            var requiredKeyword = param.IsNullable ? "" : "required ";
            if (!string.IsNullOrWhiteSpace(param.XmlDocs))
            {
                WriteLine(param.XmlDocs!);
            }

            WriteLine($"public {requiredKeyword}{param.ResolvedType} {propertyName} {{ get; init; }}");
        }

        if (dto.NestedDtos.Count > 0)
        {
            WriteLine("");
            foreach (var nested in dto.NestedDtos)
            {
                GenerateDto(nested, true);
                WriteLine("");
            }
        }

        PopIndent();
        WriteLine("}");
    }

    private static string ToPascalCase(string input)
    {
        if (string.IsNullOrEmpty(input)) return input;
        return char.ToUpperInvariant(input[0]) + input.Substring(1);
    }

    private static string ToSnakeCase(string input)
    {
        if (string.IsNullOrEmpty(input)) return input;
        return char.ToLowerInvariant(input[0]) + input.Substring(1);
    }
}