//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Majal source generator
// </auto-generated>
//------------------------------------------------------------------------------

namespace Majal;

/// <summary>
/// Apply to a class to indicate it is a DDD aggregate type.
/// The generator will create a partial class with domain-event helpers.
/// </summary>
[global::System.AttributeUsage(global::System.AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
public sealed class AggregateAttribute<TDomainEvent> : global::System.Attribute
{
}