<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <NoWarn>$(NoWarn);CS1591</NoWarn>
        <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
        <CompilerGeneratedFilesOutputPath>$(BaseIntermediateOutputPath)Generated</CompilerGeneratedFilesOutputPath>
    </PropertyGroup>

    <ItemGroup>
        <Using Include="Majal" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
        <PackageReference Include="MicroElements.AspNetCore.OpenApi.FluentValidation" Version="7.1.4" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.8" />
        <PackageReference Include="Scalar.AspNetCore" Version="2.14.0" />
        <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" Version="10.2.3" />
        <PackageReference Include="WolverineFx.Http.FluentValidation" Version="5.39.1" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.6">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.5" />
        <PackageReference Include="SQLitePCLRaw.lib.e_sqlite3" Version="2.1.12" />
        <PackageReference Include="Majal" Version="$(PackageVersion)"  />
        <PackageReference Include="Majal.EntityFrameworkCore" Version="$(PackageVersion)" />
        <PackageReference Include="Majal.DataTransferObjects" Version="$(PackageVersion)" />
    </ItemGroup>

</Project>